### ISSUE TITLE
Проблема повторной установки

### ISSUE THREAD

**Issue by drfischer2** [qzeleza/kvas#10]
Kvas_beta_18

При попытке установть 18-ую получаю такую ошибку:

Настройка файлов конфигурации пакета                                sed: unmatch              ed '/'
Отсутствует файл /opt/etc/ndm/netfilter.d/100-dns-local
Проблема повторной установки. Удалите и установите пакет заново.
Collected errors:
 * pkg_run_script: package "kvas" postinst script returned status 1.
 * opkg_configure: kvas.postinst returned 1.

Удалял повторно- не помогло.

https://i120.fastpic.org/big/2022/1012/86/b190cca2b4c8a26e69b437aa80413986.png

**Comment by qzeleza** [comment]
Попробуйте полностью удалить пакет со всеми зависимостями и архивами:
1. `kvas adguard off` в случае, если был установлен adguard
2. `opkg remove kvas --autoremove` 
3. `rm -r /opt/etc/.kvas`

Далее, пробуйте установить пакет заново.
Жду обратной связи по проблеме. Если не поможет, то прошу так же прислать информацию о роутере и прошивке.

**Comment by drfischer2** [comment]
AdGuard установлен не был, поэтому 1 пропустил. После выполнения 2,3 пунктов вроде установка прошла, КВАС заработал, однако в конце установки появились следующие ошибки:


```
Collected errors:
 * resolve_conffiles: Existing conffile /opt/etc/crontab is different from the conffile in the new package. The new conffile will be placed at /opt/etc/crontab-opkg.
 * resolve_conffiles: Existing conffile /opt/etc/dnsmasq.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/dnsmasq.conf-opkg.
```

**Comment by qzeleza** [comment]
> AdGuard установлен не был, поэтому 1 пропустил. После выполнения 2,3 пунктов вроде установка прошла, КВАС заработал, однако в конце установки появились следующие ошибки:
> 
> ```
> Collected errors:
>  * resolve_conffiles: Existing conffile /opt/etc/crontab is different from the conffile in the new package. The new conffile will be placed at /opt/etc/crontab-opkg.
>  * resolve_conffiles: Existing conffile /opt/etc/dnsmasq.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/dnsmasq.conf-opkg.
> ```

Можете игнорировать эти сообщения, так как речь идет о создании архивных копий, обозначенных в сообщении файлах.

**Comment by drfischer2** [comment]
> Можете игнорировать эти сообщения, так как речь идет о создании архивных копий, обозначенных в сообщении файлах.

понял. спасибо.
