### ISSUE TITLE
Поправить на wiki уоманду уделаения хоста из списка "белых"

### ISSUE THREAD

**Issue by PiomClone** [qzeleza/kvas#101]
**Опишите проблему.**
Сейчас на вики "kvas rm google     - удаляем все хосты со словом google внутри, из списка разблокировки."
**Какие шаги, привели к ошибке/проблеме?**
1. [Перейти на вкии '...'](https://github.com/qzeleza/kvas/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0)

**Какие ожидания о поведении программы?**
kvas del google     - удаляем хосты с упоминанием "google" из списочного файла.

**Comment by qzeleza** [comment]
Поясните пожалуйста, в чем проблема конкретно?

**Comment by qzeleza** [comment]
Вопрос закрывается в следствии отсутствия четкого описания самой проблемы.

**Comment by anisart** [comment]
Вот поясняющая картинка. Сам сначала не понимал, что происходит, пока на эту ишью не пришел
![image](https://github.com/qzeleza/kvas/assets/693481/a387352e-8827-43dd-a68c-0ac3c1be22d4)
