### ISSUE TITLE
Не работает обход после чистой установки Kvas

### ISSUE THREAD

**Issue by GamePanderDC** [qzeleza/kvas#106]
Здравствуйте! Поставил Entware с нуля на чистую флешку, по инструкции с гита установил Kvas, прописал данные на подключение к Shadowsocks, но как бы я не старался, обход не фурычит. Во время проверки IP на сайте показывается белый IP адрес провайдера и всё на этом.
Прилагаю дебаг инфо ниже:
`-------------------------------------------------------------------
Версия пакета 1.1.7 release-6
-------------------------------------------------------------------
Текущая дата и время Thu Feb  8 01:34:24 MSK 2024

-------------------------------------------------------------------
Информация о роутере
-------------------------------------------------------------------
Страна: RU
Модель: KN-1011
Продукт: Giga
Страна_: EA
Тип архитектуры: mipsel

Журнал установки пакета:
-------------------------------------------------------------------
УСТАНОВЛЕН файл списка разблокировки ПО УМОЛЧАНИЮ.
УСТАНОВЛЕН файл конфигурации пакета Квас ПО УМОЛЧАНИЮ.
УСТАНОВЛЕН файл конфигурации Shadowsocks ПО УМОЛЧАНИЮ.
УСТАНОВЛЕН файл конфигурации dnsmasq ПО УМОЛЧАНИЮ.
Текущее VPN соединение: SHADOWSOCKS
Шифрование DNS трафика (dnscrypt-proxy2) ВКЛЮЧЕНО.
Блокировка рекламы НЕ УСТАНОВЛЕНА..
-------------------------------------------------------------------
Установка завершена: 08/02/2024 01:22:15

-------------------------------------------------------------------
Список ошибок из системного журнала
-------------------------------------------------------------------
 Opkg::Manager: /opt/etc/ndm/netfilter.d/100-proxy-redirect: exit code 2.
 Feb  8 01:32:10
 Opkg::Manager: /opt/etc/ndm/netfilter.d/100-proxy-redirect: exit code 2.
 Feb  8 01:34:02

Доступные VPN интерфейсы в системе
-------------------------------------------------------------------
shadowsocks = [shadowsocks | shadowsocks]
warp = [Wireguard0 | warp]
wgcf-profile = [Wireguard1 | wgcf-profile]
hit-vpn = [Wireguard2 | hit-vpn]

-------------------------------------------------------------------
Состояние службы dnsmasq по команде
/opt/etc/init.d/S56dnsmasq status                         ЗАПУЩЕНА
-------------------------------------------------------------------
Выборка из файла конфигурации dnsmasq: /opt/etc/dnsmasq.conf
-------------------------------------------------------------------
user=nobody
pid-file=/var/run/opt-dnsmasq.pid
interface=br0
listen-address=192.168.1.1
listen-address=127.0.0.1
port=53
addn-hosts=/opt/etc/hosts
conf-dir=/opt/etc/dnsmasq.d/,*.dnsmasq
proxy-dnssec

Состояние службы dnscrypt-proxy2                          ЗАПУЩЕНА
-------------------------------------------------------------------
Отчет по прослушиванию порта dnscrypt-proxy [9153]
команда: netstat -ltunp | grep "dnscrypt"
-------------------------------------------------------------------
tcp 0 0 :::9153 :::* LISTEN 15281/dnscrypt-prox
udp 0 0 :::9153 :::* 15281/dnscrypt-prox

-------------------------------------------------------------------
Выборка из файла конфигурации dnscrypt-proxy2 /opt/etc/dnscrypt-proxy.toml
-------------------------------------------------------------------
listen_addresses = ['[::]:9153']
cache = false

-------------------------------------------------------------------
Список разблокировки в /opt/etc/dnsmasq.d/kvas.dnsmasq (все записи)
-------------------------------------------------------------------
ipset=/:.*2ip\.ru:/unblock
ipset=/:.*4pda\.ru:/unblock
ipset=/:.*ads-twitter\.com:/unblock
ipset=/:.*bing\.com:/unblock
ipset=/:.*browserleaks\.com:/unblock
ipset=/:.*kinozal\.tv:/unblock
ipset=/:.*live\.com:/unblock
ipset=/:.*meta\.com:/unblock
ipset=/:.*microsoft\.com:/unblock
ipset=/:.*microsoft365\.com:/unblock
ipset=/:.*netflix\.com:/unblock
ipset=/:.*oaistatic\.com:/unblock
ipset=/:.*openai\.com:/unblock
ipset=/:.*openwrt\.org:/unblock
ipset=/:.*whatsapp\.net:/unblock
ipset=/myip2.ru/unblock
ipset=/:.*rutracker\.org:/unblock

-------------------------------------------------------------------
Состояние службы shadowsocks                              ЗАПУЩЕНА
-------------------------------------------------------------------
Отчет по прослушиванию порта shadowsocks [1181]
команда: netstat -ltunp | grep "ss-redir"
-------------------------------------------------------------------
tcp 0 0 :::1181 :::* LISTEN 15219/ss-redir

-------------------------------------------------------------------
Выборка из файла конфигурации shadowsocks /opt/etc/shadowsocks.json
-------------------------------------------------------------------
{
  "local_port": 1181,
  "method": "chacha20-ietf-poly1305",
  "timeout": 86400,
  "local_address": "::",
  "dns_ipv6": false,
  "fast_open": false
}

-------------------------------------------------------------------
Переустановка iptables для shadowsocks завершена           УСПЕШНО
-------------------------------------------------------------------
Правила перенаправления трафика unblock в iptables
команда: iptables-save | grep -E 'SHADOWSOCKS|VPNREDIR|unblock'
-------------------------------------------------------------------
:SHADOWSOCKS - [0:0]
-A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
-A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
-A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
-A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
-A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
-A SHADOWSOCKS -d 89.208.103.172/32 -j RETURN

-------------------------------------------------------------------
Список разблокировки /opt/etc/hosts.list (все записи)
-------------------------------------------------------------------
*2ip.ru
*4pda.ru
*ads-twitter.com
*bing.com
*browserleaks.com
*kinozal.tv
*live.com
*meta.com
*microsoft.com
*microsoft365.com
*netflix.com
*oaistatic.com
*openai.com
*openwrt.org
*rutracker.org
*whatsapp.net
myip2.ru

-------------------------------------------------------------------
DNS сервер, используемый в /opt/apps/kvas/bin/main/ipset
-------------------------------------------------------------------
@127.0.0.1:9153

-------------------------------------------------------------------
Проверка наличия ip адресов хостов в таблице ipset
команда 'ipset list unblock'
-------------------------------------------------------------------
2ip.ru --> 195.201.201.35                                В ТАБЛИЦЕ
4pda.ru --> 104.21.68.2|172.67.183.145                   В ТАБЛИЦЕ
ads-twitter.com                                         АДРЕСА НЕТ
bing.com --> 204.79.197.200|13.107.21.200                В ТАБЛИЦЕ
browserleaks.com --> 104.236.69.55                       В ТАБЛИЦЕ
kinozal.tv --> 172.67.189.243|104.21.89.161              В ТАБЛИЦЕ
live.com --> 204.79.197.212                              В ТАБЛИЦЕ
meta.com --> 157.240.0.13                                В ТАБЛИЦЕ
microsoft.com --> 20.112.250.133|20.231.239.246|20.76.201В ТАБЛИЦЕ
microsoft365.com --> 13.107.6.156                        В ТАБЛИЦЕ
netflix.com --> 18.200.8.190|54.155.246.232|54.73.148.11ОТСУТСВУЕТ
oaistatic.com --> 188.114.99.224|188.114.98.224         ОТСУТСВУЕТ
openai.com --> 13.107.213.67|13.107.246.67               В ТАБЛИЦЕ
openwrt.org --> 64.226.122.113                           В ТАБЛИЦЕ
rutracker.org --> 104.21.32.39|172.67.182.196            В ТАБЛИЦЕ
whatsapp.net --> 163.70.151.60                          ОТСУТСВУЕТ
myip2.ru --> 81.90.181.105                               В ТАБЛИЦЕ
-------------------------------------------------------------------`

**Comment by GamePanderDC** [comment]
> ## Здравствуйте! Поставил Entware с нуля на чистую флешку, по инструкции с гита установил Kvas, прописал данные на подключение к Shadowsocks, но как бы я не старался, обход не фурычит. Во время проверки IP на сайте показывается белый IP адрес провайдера и всё на этом.
> Прилагаю дебаг инфо ниже:
> `-------------------------------------------------------------------
> Версия пакета 1.1.7 release-6
> Текущая дата и время Thu Feb 8 01:34:24 MSK 2024
> 
> ## Информация о роутере
> Страна: RU Модель: KN-1011 Продукт: Giga Страна_: EA Тип архитектуры: mipsel
> 
> ## Журнал установки пакета:
> ## УСТАНОВЛЕН файл списка разблокировки ПО УМОЛЧАНИЮ.
> УСТАНОВЛЕН файл конфигурации пакета Квас ПО УМОЛЧАНИЮ.
> УСТАНОВЛЕН файл конфигурации Shadowsocks ПО УМОЛЧАНИЮ.
> УСТАНОВЛЕН файл конфигурации dnsmasq ПО УМОЛЧАНИЮ.
> Текущее VPN соединение: SHADOWSOCKS
> Шифрование DNS трафика (dnscrypt-proxy2) ВКЛЮЧЕНО.
> Блокировка рекламы НЕ УСТАНОВЛЕНА..
> Установка завершена: 08/02/2024 01:22:15
> 
> ## Список ошибок из системного журнала
> Opkg::Manager: /opt/etc/ndm/netfilter.d/100-proxy-redirect: exit code 2. Feb 8 01:32:10 Opkg::Manager: /opt/etc/ndm/netfilter.d/100-proxy-redirect: exit code 2. Feb 8 01:34:02
> 
> ## Доступные VPN интерфейсы в системе
> shadowsocks = [shadowsocks | shadowsocks] warp = [Wireguard0 | warp] wgcf-profile = [Wireguard1 | wgcf-profile] hit-vpn = [Wireguard2 | hit-vpn]
> 
> ## Состояние службы dnsmasq по команде
> /opt/etc/init.d/S56dnsmasq status ЗАПУЩЕНА
> ## Выборка из файла конфигурации dnsmasq: /opt/etc/dnsmasq.conf
> user=nobody pid-file=/var/run/opt-dnsmasq.pid interface=br0 listen-address=192.168.1.1 listen-address=127.0.0.1 port=53 addn-hosts=/opt/etc/hosts conf-dir=/opt/etc/dnsmasq.d/,*.dnsmasq proxy-dnssec
> 
> ## Состояние службы dnscrypt-proxy2 ЗАПУЩЕНА
> ## Отчет по прослушиванию порта dnscrypt-proxy [9153]
> команда: netstat -ltunp | grep "dnscrypt"
> tcp 0 0 :::9153 :::* LISTEN 15281/dnscrypt-prox udp 0 0 :::9153 :::* 15281/dnscrypt-prox
> 
> ## Выборка из файла конфигурации dnscrypt-proxy2 /opt/etc/dnscrypt-proxy.toml
> listen_addresses = ['[::]:9153'] cache = false
> 
> ## Список разблокировки в /opt/etc/dnsmasq.d/kvas.dnsmasq (все записи)
> ipset=/:.*2ip.ru:/unblock ipset=/:.*4pda.ru:/unblock ipset=/:.*ads-twitter.com:/unblock ipset=/:.*bing.com:/unblock ipset=/:.*browserleaks.com:/unblock ipset=/:.*kinozal.tv:/unblock ipset=/:.*live.com:/unblock ipset=/:.*meta.com:/unblock ipset=/:.*microsoft.com:/unblock ipset=/:.*microsoft365.com:/unblock ipset=/:.*netflix.com:/unblock ipset=/:.*oaistatic.com:/unblock ipset=/:.*openai.com:/unblock ipset=/:.*openwrt.org:/unblock ipset=/:.*whatsapp.net:/unblock ipset=/myip2.ru/unblock ipset=/:.*rutracker.org:/unblock
> 
> ## Состояние службы shadowsocks ЗАПУЩЕНА
> ## Отчет по прослушиванию порта shadowsocks [1181]
> команда: netstat -ltunp | grep "ss-redir"
> tcp 0 0 :::1181 :::* LISTEN 15219/ss-redir
> 
> ## Выборка из файла конфигурации shadowsocks /opt/etc/shadowsocks.json
> { "local_port": 1181, "method": "chacha20-ietf-poly1305", "timeout": 86400, "local_address": "::", "dns_ipv6": false, "fast_open": false }
> 
> ## Переустановка iptables для shadowsocks завершена УСПЕШНО
> ## Правила перенаправления трафика unblock в iptables
> команда: iptables-save | grep -E 'SHADOWSOCKS|VPNREDIR|unblock'
> :SHADOWSOCKS - [0:0] -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN -A SHADOWSOCKS -d 89.208.103.172/32 -j RETURN
> 
> ## Список разблокировки /opt/etc/hosts.list (все записи)
> *2ip.ru *4pda.ru *ads-twitter.com *bing.com *browserleaks.com *kinozal.tv *live.com *meta.com *microsoft.com *microsoft365.com *netflix.com *oaistatic.com *openai.com *openwrt.org *rutracker.org *whatsapp.net myip2.ru
> 
> ## DNS сервер, используемый в /opt/apps/kvas/bin/main/ipset
> @127.0.0.1:9153
> 
> ## Проверка наличия ip адресов хостов в таблице ipset
> команда 'ipset list unblock'
> 2ip.ru --> 195.201.201.35 В ТАБЛИЦЕ 4pda.ru --> 104.21.68.2|172.67.183.145 В ТАБЛИЦЕ ads-twitter.com АДРЕСА НЕТ bing.com --> 204.79.197.200|13.107.21.200 В ТАБЛИЦЕ browserleaks.com --> 104.236.69.55 В ТАБЛИЦЕ kinozal.tv --> 172.67.189.243|104.21.89.161 В ТАБЛИЦЕ live.com --> 204.79.197.212 В ТАБЛИЦЕ meta.com --> 157.240.0.13 В ТАБЛИЦЕ microsoft.com --> 20.112.250.133|20.231.239.246|20.76.201В ТАБЛИЦЕ microsoft365.com --> 13.107.6.156 В ТАБЛИЦЕ netflix.com --> 18.200.8.190|54.155.246.232|54.73.148.11ОТСУТСВУЕТ oaistatic.com --> 188.114.99.224|188.114.98.224 ОТСУТСВУЕТ openai.com --> 13.107.213.67|13.107.246.67 В ТАБЛИЦЕ openwrt.org --> 64.226.122.113 В ТАБЛИЦЕ rutracker.org --> 104.21.32.39|172.67.182.196 В ТАБЛИЦЕ whatsapp.net --> 163.70.151.60 ОТСУТСВУЕТ myip2.ru --> 81.90.181.105 В ТАБЛИЦЕ -------------------------------------------------------------------`

Откатившись на версию 1.1.5 final - обход заработал.

**Comment by badigit** [comment]
Подтверждаю, после обновления r5->r7 маршрут через приватную сеть не работает. При тесте - показывает
Таблица ipset                                                           ПУСТА
[debug3.log](https://github.com/qzeleza/kvas/files/14217664/debug3.log)

**Comment by qzeleza** [comment]
@badigit  Зачем же все в кучу сваливать? У Вас у обоих разные типы подключений. 
По VPN - прошу создать отдельный тикет. 

В первом случае - в **iptables** я не вижу правил для. **ssr**. 
Прошу Вас прислать вывод команды `iptables-save | grep -E 'SHADOWSOCKS|unblock'`

**Comment by badigit** [comment]
Извините, конечно, но не особо понятно , по какому критерию определять "в кучу или не в кучу", и как это угадать ДО отладки)

У [GamePanderDC](https://github.com/GamePanderDC) -Не работает обход и у меня не работает обход. 
У меня и у него возврат на r5 помог. 

Причины могут быть разными, но это будет понятно Bам - после изучения отладки.
А на момент описания, я вижу только то что у нас общие проблемы, и потому написал сюда.
Мне не сложно делать разные issue каждый раз. Но не возникнет ли уже там вопрос - зачем дублируется одно и тоже?

**Comment by qzeleza** [comment]
@badigit примите пожалуйста, что проблемы при разных подключениях - разные.  И чтобы понять, что не так - важно их разделять. 

Частично Вы правы, в том, что простой пользователь мог бы этого не обнаружить изначально, но к таковым я Вас не отношу, Вы регулярно участвуете в отладке и пишите тикеты, для Вас, по моему, не составляет труда прочитать файл отладки и понять, что подключения разные, от сюда и проблема может быть иной.

**Comment by x-tropic** [comment]
@qzeleza здравствуйте! не стал делать отдельный тикет пока что...
Есть ошибка в релизе 7 и она заключается в том. что при установке этой версии, и её настройки, в конце пишет что таблица ipset пуста. Если импортировать свой список, то все работает.
Но, если выполнить kvas test. то таблица ipset опять окажется пуста!
Команда kvas debug по итогу заполняет таблицу ipset и всё работает, а также я вижу записи по команде ipset list unblock.
В общем, команда kvas test ломает заполнение таблицы ipset и также она по какой-то причине оказывается пустой сразу после установки и первоначальной настройки кваса.

**Comment by qzeleza** [comment]
>  если выполнить kvas test. то таблица ipset опять окажется пуста! 

Хорошо, спасибо посмотрю.

**Comment by qzeleza** [comment]
Возможно, что проблема связана с малой задержкой после обработки адресов. В новой версии добавь небольшую паузу.

**Comment by x-tropic** [comment]
> Возможно, что проблема связана с малой задержкой после обработки адресов. В новой версии добавь небольшую паузу.

По поводу доступа к устройству, отписал в личку на форуме кинетика.
