### ISSUE TITLE
Белый список ресурсов для adblock

### ISSUE THREAD

**Issue by Kolyk07** [qzeleza/kvas#11]
Нужен белый список ресурсов который будет игнорировать правила черного списка Adblock. В Квас бета 18,  при активации adblock подгружаются правила для блокировки с ресурсов указанных в файле adblock.sources. В них присутствует блокировка некоторых необходимых ресурсов, например ad.admitad.com и s.click.aliexpress.com. Эти ресурсы нужны для генерации ссылок на онлайн магазины на алиэкспресс. По сути если их не убрать из списка блокировок adblock то не возможно попасть на необходимый мне ресурс. Например при включенном adblock c текущими фильтрами вы не сможете с ресурса https://mysku.club/ попасть по генерируемым там ссылкам в магазины на алиэкспресс. 
Конечно я могу отключить одно из подгружаемых правил  в файле adblock.sources закомментировав #https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

**Comment by qzeleza** [comment]
Какой Вы видите реализацию данного функционала?

**Comment by piroman21** [comment]
Приветствую.
Например как вариант.
Есть файл, например с именем adblock.whitelist
В нем содержатся имена доменов. Например

ad.admitad.com
s.click.aliexpress.com

Скрипт создания конфига для dnsmasq в конце своей работы смотрит адреса из adblock.whitelist и если они есть в adblock.dnsmasq удаляет их от туда.

**Comment by Kolyk07** [comment]
Всех приветствую. Я имею тоже самое видение которое предложил piroman21.

**Comment by qzeleza** [comment]
Вышла бета 19 - описание на [форуме](https://forum.keenetic.com/topic/14415-пробуем-квас-shadowsocks-и-другие-vpn-клиенты/?do=findComment&comment=154477) или в [HISTORY](https://github.com/qzeleza/kvas/blob/main/HISTORY.md).

**Comment by Kolyk07** [comment]
Проверил, работает! Но получается что мы на этот ресурс попадаем через vpn, а его не блокирует РКН, его кто то, по какой то причине добавил в список блокировки в одном из правил для adblock. Мне кажется это как из пушки по воробьям.. В любом случае спасибо за проделанную работу! Но предложенный вариант ранее, как мне кажется проще.

**Comment by qzeleza** [comment]
Доброго дня,
Идея ясна, не подумал, об этом, так как для меня это не критично. 
В следующей бете постараюсь реализовать вариант предложенный Вами, правда он не проще (с точки зрения реализации), так как в этом случае, необходимо писать механизм добавления и проверки доменов в этот самый файл).

**Comment by Kolyk07** [comment]
Мысли в слух..., а если на этапе сопоставления дублей в этих правилах..

**Comment by qzeleza** [comment]
Поясните пожалуйста.

**Comment by Kolyk07** [comment]
Как предлагалось выше мы создаем создаем файл adblock.whitelist в который заносим ресурсы которые должны быть исключены из блокируемых, а когда выполняется скрипт в файле adblock.sources по поиску в нем дублей ресурсов, мы в нем добавляем и ссылку на сопоставление с adblock.whitelist, как будто это правило уже есть и в итоге получается что в итоговом файле эти ресурсы будут исключены. Ну как то так... может я и не прав.. просто мысли в слух ..

**Comment by qzeleza** [comment]
Будет реализована в 20 бете.

**Comment by qzeleza** [comment]
Выпущена 20 бета пакета. Проверяем.
Жду обратной связи.

**Comment by Kolyk07** [comment]
Хочу уточнить, а где находится файл с белым списком доменов или как он называется? Что то не могу его найти (,

**Comment by qzeleza** [comment]
/opt/etc/hosts.list - основной список исключений для VPN
/opt/etc/ads_exception.list - список исключений для блокировщика рекламы.

**Comment by qzeleza** [comment]
Жду обратной связи!

**Comment by Kolyk07** [comment]
Понял почему не мог найти файл .. его просто не было )))) Пока не добавил в список исключений домен ad.admitad.com, после этого файл был создан и скрипт отработал, но в этот раз не в одном правиле на блокировку он не попал ( вот для чего и нужен белый список) видимо кто то его включил в прошлый раз по ошибке, а сейчас эту ошибку поправил.  Но я нашел на чем потестировать... ,) Так вот новый скрипт работает, но есть одно но.. нужно каждый раз после добавления домена давать команду kvas update

**Comment by qzeleza** [comment]
> Так вот новый скрипт работает, но есть одно но.. нужно каждый раз после добавления домена давать команду kvas update

Хорошо в 21 бете подправлю.

**Comment by Kolyk07** [comment]
Нашел еще один небольшой баг, если запустить команду kvas adblock результат выдает информацию что блокировка рекламы отключена, а по факту работает (проверял в браузере). При воде команды kvas adblock on, пишет что блокировка уже включена.
![2022-11-10_08-23-43](https://user-images.githubusercontent.com/56149342/201008430-6104c22c-b78e-4e28-aa6c-7b3e50844d47.png)

**Comment by qzeleza** [comment]
> При воде команды kvas adblock on, пишет что блокировка уже включена.

В 21 бете исправлено и проверено.
