### ISSUE TITLE
Происходит выгрузка из памяти adguard при обновлении списков рекламы

### ISSUE THREAD

**Issue by dimmed55** [qzeleza/kvas#112]
Здравствуйте, при каждом обновлении списков адгард уходит в 100% процессора на минуты 2 
позже видимо происходит отрубание "зависшего" процесса самим роутером и по итогу днс сервер с адгардом не запущен , а роутер и все остальное работает, но интернет не дает т.к днс не запущен
 
С моей точки зрения это можно пофиксить скриптом, который будет просто проверять включен ли адгард раз в 5 минут , если вдруг его нет , запустит.  Если такое уже реализовано и не поднимает упавший процесс
, то почему то не работает
- Производитель: Keenetic
- Версия ОС 4.0.7
- Тип устройства Ultra (KN-1811) EAEU

**Comment by qzeleza** [comment]
Ничего не понял из Вашего сообщения. Прошу внятно пояснить причину и предоставить информацию о том, что в этом на 100% виноват Квас.

**Comment by dimmed55** [comment]
> Ничего не понял из Вашего сообщения. Прошу внятно пояснить причину и предоставить информацию о том, что в этом на 100% виноват Квас.

Квас не виноват, я вас прошу в следующей версии просто добавить скрипт- проверяльщик включен ли адгард, если он используется в качестве днс сервера 

Подробнее пишу про проблему - 
Пользуюсь вашей сборкой с адгардом 
и при любом изменении правил фильтрации адгарда   выходит вот это  https://postimg.cc/dL6P6PCW
т.е система убивает процесс за не достатком памяти , так вот скрипт  мог бы проверять включен ли адгард и включать его, если система его прибила

**Comment by dimmed55** [comment]
> `kvas adguard`

да, включает, уже после отрубания, но это надо вручную сделать когда роутрер снес процесс , а мне  надо чтобы что то восстанавливало этот процесс, если он выключился на автомате , я про это

**Comment by qzeleza** [comment]
Если это не проблема Кваса, а Вашего роутера (память, процессор и пр.) не совсем ясно, с какой целью писать об этом здесь? 

Тикет закрываю в связи с тем, что запрос не относится непосредственно к самому пакету.
