### ISSUE TITLE
[Feature request] Роутинг устройств

### ISSUE THREAD

**Issue by olegchomp** [qzeleza/kvas#113]
Было бы здорово иметь возможность: 
1) Полностью переключать весь трафик с устройства (группы/политики) через Shadowsocks. В интерфейсе Keenetic нет такой возможности (только для VPN)
2) Задавать DNS для определенных ресурсов. Пример: ChatGPT не открывается при запуске через Shadowsocks, при проверке через DNS Leak сервисы, определяется реальный адресс. Если в браузере сменить DNS например на Comss, то все начинает работать. Было бы здорово иметь возможность, направить только определенные сайты через этот или аналогичные DNS.

**Comment by ALTernateF13** [comment]
Первое довольно легко [достигается с помощью iptables](https://forum.keenetic.com/topic/14415-%D0%BF%D1%80%D0%BE%D0%B1%D1%83%D0%B5%D0%BC-%D0%BA%D0%B2%D0%B0%D1%81/?do=findComment&comment=180481).

> при проверке через DNS Leak сервисы, определяется реальный адрес

А можете подсказать конкретный сервис для проверки, который нас распознаёт? Просто у меня CGPT открывается прекрасно.

Вы точно не забыли:
1. Включить шифрование DNS через _kvas crypt_.
2. В «Управление» → «Параметры системы» → «Изменить набор компонентов» добавить «Прокси-сервер DNS-over-TLS» и «Прокси-сервер DNS-over-HTTPS».
3. В «Сетевые правила» → «Интернет-фильтры» → «Настройка DNS» оставить только с поддержкой DoT или DoH. Никаких провайдерных DNS! У меня, например, 1.1.1.1, 1.0.0.1 (cloudflare-dns.com); 8.8.8.8, 8.8.4.4 (dns.google); 9.9.9.9 (dns.quad9.net).

**Comment by olegchomp** [comment]
> Первое довольно легко [достигается с помощью iptables](https://forum.keenetic.com/topic/14415-%D0%BF%D1%80%D0%BE%D0%B1%D1%83%D0%B5%D0%BC-%D0%BA%D0%B2%D0%B0%D1%81/?do=findComment&comment=180481).

очень пытался понять, но после ifconfig не понял как найти нужный мне ПК (подключен через порт)

> А можете подсказать конкретный сервис для проверки, который нас распознаёт? Просто у меня CGPT открывается прекрасно.

https://www.dnsleaktest.com/

> В «Сетевые правила» → «Интернет-фильтры» → «Настройка DNS» оставить только с поддержкой DoT или DoH. Никаких провайдерных DNS! У меня, например, 1.1.1.1, 1.0.0.1 (cloudflare-dns.com); 8.8.8.8, 8.8.4.4 (dns.google); 9.9.9.9 (dns.quad9.net).

в случае с DoH сервера будут:
https://cloudflare-dns.com/dns-query
https://dns.google/dns-query
и тд.

**Comment by ALTernateF13** [comment]
> при проверке через DNS Leak сервисы, определяется реальный адрес. Если в браузере сменить DNS например на Comss, то все начинает работать

В общем, переход на шифрованные общественные DNS решил вторую проблему? Если нет, то я бы подозревал SS или VPN-сервис в дырявости. А то у меня [dnsleaktest.com](https://www.dnsleaktest.com/) утверждает, что я из США и IP не найдены даже в Extended test.

**Comment by olegchomp** [comment]
> В общем, переход на шифрованные общественные DNS решил вторую проблему? 

Решение было сменить DNS на DoH сервера.

Осталось только с роутингом устройтва разобраться. Вроде как полезная функция, но из коробки ее нету )

**Comment by ALTernateF13** [comment]
> не понял как найти нужный мне ПК (подключен через порт)
Расписано [тут](https://forum.keenetic.com/topic/14415-%D0%BF%D1%80%D0%BE%D0%B1%D1%83%D0%B5%D0%BC-%D0%BA%D0%B2%D0%B0%D1%81/?do=findComment&comment=180607)

**Comment by qzeleza** [comment]
Инструкция [добавлена](https://github.com/qzeleza/kvas/wiki/Эффективная-работа#защита-dns-трафика)
