### ISSUE TITLE
IKEv2 + SS не работает на некоторых моделях

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#114]
Сейчас правила iptables (_-s 192.168.2.0/24 -i eth3_) основаны на диапазоне IP, ограниченном в интерфейсе WAN (чтобы не перегружать роутер, навешивая правило с диапазоном на все интерфейсы). 

Как выяснилось, более простые Кинетики могут быть созданы на базе одного сетевого интерфейса (например, Hopper), а не двух (например, Giga). Во втором случае WAN порт eth3, в первом WAN в eth2.2 ([на форуме проверили это](https://forum.keenetic.com/topic/14415-%D0%BF%D1%80%D0%BE%D0%B1%D1%83%D0%B5%D0%BC-%D0%BA%D0%B2%D0%B0%D1%81/?do=findComment&comment=180450)). 

В функции _get_entware_ikev2_inface_ надо делать проверку _ifconfig eth3_ (или любым другим способом — доступен же список интерфейсов, проверять там наличие) и если он есть, то возвращать _eth3_. Иначе _eth2.2_.

**Comment by qzeleza** [comment]
Хорошо, в новой версии постараюсь учесть этот момент.

**Comment by x-tropic** [comment]
> Вроде как у человека с Keenetic Hopper всё заработало из коробки, вопрос можно закрывать

да, это я жаловался. Теперь всё ок, проблема решена.

**Comment by AltGrF13** [comment]
> всё ок, проблема решена

Я бы рекомендовал ещё на форуме отписаться в ответ на релиз, что на Hopper теперь из коробки работает связка IKEv2+ShadowSocks. Возможно, кого-то это подтолкнёт обновиться; техническое описание многим не понятно)

**Comment by qzeleza** [comment]
> Я бы рекомендовал ещё на форуме отписаться в ответ на релиз, что на Hopper теперь из коробки работает связка IKEv2+ShadowSocks. Возможно, кого-то это подтолкнёт обновиться; техническое описание многим не понятно)

Справитесь?)
