### ISSUE TITLE
Добавить в инструкцию по установке про DNS

### ISSUE THREAD

**Issue by ALTernateF13** [qzeleza/kvas#115]
Уже раза 3 встречалось (форум, вопрос тут); когда люди используют КВАС для получения доступа к американским ресурсам, которые нас блокируют, с нешифрованным DNS провайдера. Этим самым палятся, а потом советуют настраивать это в браузере. Т.к. момент действительно не самый очевидный, то предлагаю в документацию «[Установка пакета на устройство](https://github.com/qzeleza/kvas/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0-%D0%BD%D0%B0-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE)» пункт «ПРИМЕЧАНИЕ» переименовать в «Примечание про локальные домены» и добавить ещё одно:

Примечание про шифрование DNS
Непосредственно обхода может быть недостаточно (читаем про DNS Leak), крайне рекомендуется перейти на шифрованные популярные DNS. Для этого:
1. В админке роутера «Управление» → «Параметры системы» → «Изменить набор компонентов» добавить «Прокси-сервер DNS-over-TLS» или «Прокси-сервер DNS-over-HTTPS».
2. В админке роутера «Сетевые правила» → «Интернет-фильтры» → «Настройка DNS» оставить только с поддержкой DoT или DoH (иконка с зелёным замочком и соответствующая подпись). Никаких местных провайдерных DNS! Чаще всего используют: 1.1.1.1, 1.0.0.1 (cloudflare-dns.com); 8.8.8.8, 8.8.4.4 (dns.google); 9.9.9.9 (dns.quad9.net).
3. Проверить _kvas crypt_ и, если отключено, сделать _kvas crypt on_.

**Comment by ALTernateF13** [comment]
Минимум двоим это [помогло восстановить](https://github.com/qzeleza/kvas/issues/113#issuecomment-2022299082) обход у блокирующих россиян ресурсов.

В той задаче был минимум один хороший совет — проверять IP и на [www.dnsleaktest.com](https://www.dnsleaktest.com/). Сайт в фоне скармливает браузеру уникальный поддомен, наша ОСь запрашивает его DNS-запись; и если используется нешифрованный/местный DNS, то сервис проверки DNS Leak вычислит минимум провайдера/страну не взирая на тоннель.

**Comment by qzeleza** [comment]
Благодарю Вас. 
СОотвествующий раздел добавлен в [Wiki](https://github.com/qzeleza/kvas/wiki/Эффективная-работа#защита-dns-трафика)

**Comment by ALTernateF13** [comment]
Спасибо за уточнение про `kvas crypt on`, знания о его природе были не верны)
