### ISSUE TITLE
Не качает скрипт для обновления (upgrade)

### ISSUE THREAD

**Issue by walkman99** [qzeleza/kvas#118]
Запускаю _curl -sO http://kvas.zeleza.ru/upgrade && sh upgrade_ - создается файл _upgrade_ нулевой длины, никаких сообщений нет. Попробовал на компьютере - аналогично. В браузере на ПК открывается. 
Не понимаю, в чем дело.

**Comment by qzeleza** [comment]
Внимательно перечитайте [инструкцию](https://github.com/qzeleza/kvas/wiki/Установка-пакета#установка-пакета-на-устройство). Проблема в аргументах  curl

**Comment by walkman99** [comment]
Спасибо. На странице https://github.com/qzeleza/kvas/ устаревшая информация, я брал строку оттуда.

**Comment by qzeleza** [comment]
Спасибо, информацию обновил.
