### ISSUE TITLE
Добавить в инструкцию про спам в системном журнале

### ISSUE THREAD

**Issue by ALTernateF13** [qzeleza/kvas#119]
После установки КВАС в логе очень сложно бывает что-то найти, но речь сейчас о системных сообщениях крона `(root) CMD (/opt/bin/run-parts` (коих на скрине больше половины)
![image](https://github.com/qzeleza/kvas/assets/8899868/360f03fa-22e0-4813-8b40-2bf21cf8c939)

На форуме [есть решение](https://forum.keenetic.com/topic/233-logger-cron-%D0%BA%D0%B0%D0%BA-%D1%83%D0%B1%D1%80%D0%B0%D1%82%D1%8C-%D0%BB%D0%B8%D1%88%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F/?do=findComment&comment=4474). Это не подавляет логи крона, только logger запуска.

Предлагаю в [Эффективная работа](https://github.com/qzeleza/kvas/wiki/%D0%AD%D1%84%D1%84%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%B0%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0) добавить что-то вроде:

## Уменьшение спама в системном журнале
1. От `(root) CMD (/opt/bin/run-parts`
   - В файле `/opt/etc/init.d/S10cron` заменить строку `ARGS="-s"` на `ARGS=""`
   - `/opt/etc/init.d/S10cron restart`
2. От `failed to load names from /opt/etc/hosts: No such file or directory` выполнить `touch /opt/etc/hosts`

**Comment by qzeleza** [comment]
не совсем ясно, как системные сообщения крона относятся к Квасу?

**Comment by ALTernateF13** [comment]
По второму, КВАС устанавливает dnsmasq, подменяет ему настройки на свои, где указано `addn-hosts=/opt/etc/hosts`. Т.е. указывает dnsmasq обращаться к этому файлу, но сам файл не создаёт при его отсутствии. В итоге мы и наблюдаем спам от dnsmasq, не от КВАСа, да. Но сами же ему указали этот файл проверять.

**Comment by qzeleza** [comment]
Добро, по второму пункту поправлю. 
Благодарю.
