### ISSUE TITLE
через какое-то время пропадает обход 

### ISSUE THREAD

**Issue by goldfoxigor** [qzeleza/kvas#12]
Добрый день! 
Версия скрипта 1.0-beta-18
  Через какое-то неопределённое время  пропадает обход. При вводе команды kvas test проблем не обнаружено, при вводе kvas debug тоже самое, проблем вроде как нет, единственное логи ошибок из системного журнала
 Список ошибок из системного журнала
-----------------------------------------------------------------------------------
 Cloud::Agent: can not connect to the cloud server.
 Oct 16 06:18:20
 Cloud::Agent: can not connect to the cloud server.
 Oct 16 07:18:26
 Core::Ndss: [18184] HTTP error: 403 (request forbidden).
 Oct 16 08:12:41
 Cloud::Agent: can not connect to the cloud server.
 Oct 16 08:18:31
 Cloud::Agent: can not connect to the cloud server.
 Oct 16 09:18:36
 failed to load names from /opt/etc/hosts: No such file or directory
 Oct 16 10:16:54
 Cloud::Agent: can not connect to the cloud server.
 Oct 16 10:18:41

 и после команды kvas debug сразу начинает работать обход. Вот и приходиться с утра вводить команду kvas debug и на следующий день так же!

**Comment by qzeleza** [comment]
Прошу приложить файл отладки по команде **kvas debug**

**Comment by goldfoxigor** [comment]
log
[log.txt](https://github.com/qzeleza/kvas/files/9797267/log.txt)

**Comment by qzeleza** [comment]
Вышла бета 19 - описание на [форуме](https://forum.keenetic.com/topic/14415-пробуем-квас-shadowsocks-и-другие-vpn-клиенты/?do=findComment&comment=154477) или в [HISTORY](https://github.com/qzeleza/kvas/blob/main/HISTORY.md).
Проверяем работу.

**Comment by goldfoxigor** [comment]
спасибо! сейчас попробую установить и протестировать.

**Comment by goldfoxigor** [comment]
19 бета не работает! ставил начисто. вернулся на 17-ю

**Comment by goldfoxigor** [comment]
LOG почему то не прикрепляется

**Comment by goldfoxigor** [comment]
[log1.txt](https://github.com/qzeleza/kvas/files/9900826/log1.txt)

**Comment by qzeleza** [comment]
По логу видно, что iptables правила при установке не прописались. 
Также видна ошибка о том, что подключение к серверу не состоялось - проверьте данные о подключению по SSR.

**Comment by qzeleza** [comment]
После проверки запустите kvas update
