### ISSUE TITLE
Перестал работать маршрут через vpn при обновлении  1.1.7-r-8 >> 1.1.8 r-1

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#122]
**Опишите проблему.**
После обновления через kvas upgrade - маршрут через vpn работать перестал.

**Приложите снимки экрана или сам текст с консоли.**
Журнал обновления [жжж.txt](https://github.com/qzeleza/kvas/files/14971394/default.txt)
Обращает внимание, строка 
`Наличие правил разблокировки в iptable                               ПРАВИЛ НЕТ
`
и  таблица iptable по журналу журналу заполнилась только со второго раза

kvas test тоже показывает что правил нет, и со второго раза заполняет.
[ttt.txt](https://github.com/qzeleza/kvas/files/14971408/ttt.txt)

**Заполните информацию о системе на роутере:**
дебаг [ddd.txt](https://github.com/qzeleza/kvas/files/14971403/ddd.txt)

**Доп. информация:**
выполнение kvas adguard off \ on  не помогло (не работает в обоих вариантах)

**Comment by badigit** [comment]
rollback на 1.1.7 r8 всё заработало.

**Comment by qzeleza** [comment]
Спасибо. 
Постараюсь сегодня выпустить обновление, если получится.

**Comment by badigit** [comment]
Спасибо, r2 все решает
