### ISSUE TITLE
Моменты по dns hosts *

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#125]
**Опишите проблему.**
Попробовал команды реализованные в данном коммите
https://github.com/qzeleza/kvas/commit/cd36c45caa14d140de2cea557a154582e034ebde

1. dns hosts кажется не срабатывает как "list", а срабатывает как edit
```
~ # kvas dns hosts
------------------------------------------------------------------------------------------------------
Замена DNS на hosts в dnsmasq завершена                                                     С ОШИБКОЙ 
------------------------------------------------------------------------------------------------------ 
```

2. Это ломает конфиг dnsmasq..
строка server=127.0.0.1#9153
превращается в server=hosts
dnsmasq падает и не поднимается.

Причиной может быть и то что у меня в hosts есть реально есть хост "server"
127.0.0.1 localhost
::1 localhost
10.36.0.22 1csrv
10.36.0.12 server

3. также команды dns hosts (пока) не отдаются в kvas help.

**Comment by qzeleza** [comment]
Прошу прощения за задержку с ответом и благодарю за терпение. 
Прочитал и затем успешно позабыл(

Касаемо вопроса Вашего - то вкралась ошибка - команда должна быть `kvas hosts`, а не `kvas dns hosts` 
Остальные команды edit и add - у меня не заработали - в следующем релизе поправлю.

Еще раз благодарю Вас.

**Comment by qzeleza** [comment]
Ошибки все еще присутствуют?

**Comment by badigit** [comment]
В 1.1.9
kvas dns не выдает ничего
~ # kvas dns
----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
~ #

kvas hosts - работает
kvas help - не показывает что существует kvas hosts

kvas hosts add smart.home 10.9.0.82 - работает, в hosts добавляется, но резолвинг не работает (dnsmasq)

**Comment by qzeleza** [comment]
Версия 1.1.9 еще не вышла, не вижу смысла ее здесь обсуждать, для того существует тема для тестирования в телеграмме канале [Квас Pro](https://t.me/kvas_pro/3310/3311).
> kvas help - не показывает что существует kvas hosts

Что выдает `kvas help | grep hosts`?
