### ISSUE TITLE
Перестали открываться "разблокированные" страницы

### ISSUE THREAD

**Issue by exfur** [qzeleza/kvas#126]
**Опишите проблему.**
На примере 2ip.io
Если он не в списке для разблокировки, то открывается с моим ip адресом
Если он в списке разблокировки, то получаю сообщение "Не удается получить доступ к сайту"

**Какие шаги, привели к ошибке/проблеме?**
Опишите подробно шаги, которые привели к ошибке:

1. Запустил следующую команду kvas setup
2. Затем kvas test

**Какие ожидания о поведении программы?**
Должен открыться 2ip.io с моим ip на shadowsocks сервере

**Приложите снимки экрана или сам текст с консоли.**
![image](https://github.com/qzeleza/kvas/assets/43076483/3fd1455c-bfc6-4545-9447-4b0adcd29e8e)
![image](https://github.com/qzeleza/kvas/assets/43076483/095159db-a8dc-42bf-896b-f55b0d396ec7)
![image](https://github.com/qzeleza/kvas/assets/43076483/5ac97753-318c-48bf-9dd1-d7678e9826e7)
![image](https://github.com/qzeleza/kvas/assets/43076483/212a7f13-b863-4439-955a-1432f0c0187b)

**Заполните информацию о системе на роутере:**
- Операционная система (ее кодовое название) и версия: Linux Keenetic-9579 4.9-ndm-5 #0 SMP  aarch64 GNU/Linux

- Браузер и его версия chrome 36
- SSH клиент и его версия Putty 0.81

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.1.3
- Тип устройства Peak (KN-2710) EAEU

_Сервер shadowsocks на Outline исправен_

**Comment by exfur** [comment]
как будто бы у меня прописаны какие то правила которые мешают работе кваса. Что это может быть? 
![image](https://github.com/qzeleza/kvas/assets/43076483/8c66ed7c-9a77-46be-8375-5a20a474ea30)

**Comment by qzeleza** [comment]
Доброго дня
Полагаю, что Вам в данном случае, лучше всего переустановить OPKG заново и затем Квас.
