### ISSUE TITLE
Не удается сохранить хосты - nonexistent directory

### ISSUE THREAD

**Issue by Teutonick** [qzeleza/kvas#127]
Модель: KN-1810
Продукт: Ultra
Страна_: EA
Тип архитектуры: mipsel
Версия пакета 1.1.8 release-2

Пытаюсь экспортировать хосты в файл, в любом варианте выдает ошибку

~ # kvas export > ./hosts.back
/opt/bin/kvas: line 2604: can't create : nonexistent directory
~ # kvas export
-----------------------------------------------------------------------------
Так как не задано имя файла для экспорта, то
Сохраняем архив в файл /opt/etc/.kvas/backup/hosts.list
Сохраняем записи в файл ...                                                  /opt/bin/kvas: line 2604: can't create : nonexistent directory
ОШИБКА

или 
 # kvas export > /opt/apps/kvas/
bin/   etc/   sbin/

или 
~ # kvas export > /opt/apps/hosts.back.txt
/opt/bin/kvas: line 2604: can't create : nonexistent directory

или 
~ # kvas export > /opt/apps/
-sh: can't create /opt/apps/: Is a directory

или 
~ # kvas export > /opt/apps/sdf
/opt/bin/kvas: line 2604: can't create : nonexistent directory

**Comment by qzeleza** [comment]
Квас тут не причем. У Вас скорее всего отсутствует папка в которую Вы хотите сохранить файл. 
Сначала создайте ее `mkdir /opt/apps` и только потом `kvas export > /opt/apps/hosts.back.txt`
