### ISSUE TITLE
Некорректно отрабатывает команда kvas rm

### ISSUE THREAD

**Issue by KirillShchetinnikov** [qzeleza/kvas#130]
**Опишите проблему.**
В документации указано, что команды kvas del / kvas rm	[*][хост] удаляют host из списка разблокировки. При попытке удалить хост командой kvas rm - программа хочет удалить весь пакет КВАС.

**Какие шаги, привели к ошибке/проблеме?**
~ # kvas rm Lego.com
------------------------------------------------------------------------------------------------------------------------------------
Удаление пакета КВАС™ версии 1.1.8-release-2...
------------------------------------------------------------------------------------------------------------------------------------
? Вы уверены в удалении пакета  [Y/N,Q]?  N
------------------------------------------------------------------------------------------------------------------------------------
~ #

**Какие ожидания о поведении программы?**
Должно быть поведение, как у команды kvas del

~ # kvas del Lego.com
------------------------------------------------------------------------------------------------------------------------------------
Удаляем Lego.com из списка разблокировки...                                                                                 УДАЛЕН
------------------------------------------------------------------------------------------------------------------------------------
~ #

**Заполните информацию о системе на роутере:**
- Windows 10
- Chrome 125
- Mobaxterm 24

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.1.6
- Тип устройства Ultra KN-1811

**Comment by qzeleza** [comment]
В следующем релизе для удаления пакета будет оставлена только команда **uninstall**
