### ISSUE TITLE
Отсутствие в выборе интерфейса подключения клиента Openconnect

### ISSUE THREAD

**Issue by dv0ll** [qzeleza/kvas#138]
После сканирования подключений, в списке выбора интерфейса VPN отсутствует интерфейс настроенного подключения openconnect. 
1. На прошивке 4.1.7 если установить в entware openconnect client и создать подключение, KVAS не "видит" его при первоначальной настройке,  с помощью kvas vpn set картина та же.
2. Клиент openconnect добавлен в прошивку 4.2 Beta 1 канала Preview, при настроенном подключении в UI, KVAS также его не "видит".
Собственно у меня больше вопрос, можно ли руками поменять дефолтный маршрут для адресов из списка разблокировки, и если можно, то где это сделать?

**Comment by qzeleza** [comment]
Не могу Вам ответить на данный вопрос - не использую данное соединение и нестабильные релизы прошивок.
Если есть желание предложить включить данное соединение в последующие выпуски Кваса - откройте голосование [здесь](https://t.me/kvas_pro/6/11).
