### ISSUE TITLE
Постоянные новые записи в логах о перезаполнении таблицы.

### ISSUE THREAD

**Issue by KirillShchetinnikov** [qzeleza/kvas#14]
Каждые несколько секунд в логах появляются сообщения о пересоздании правил для shadowsoks соединения.  Никакие ошибки (выделенные красным) при этом не появляются. Разблокировка при этом работает. Файл журнала забивается очень сильно, что вызывает проблему в роутере.
Скриншоты и дебаг в приложенных файлах. Это нормальное поведение или ошибка в пакете?
![Снимок экрана 2022-10-31 215758](https://user-images.githubusercontent.com/98528966/199088290-17ef8ea4-ef66-4bea-8d41-e21ddade6f94.png)
![Снимок экрана 2022-10-31 215731](https://user-images.githubusercontent.com/98528966/199088300-93b8f84d-7d35-473a-99ba-691d157a0b38.png)
[debug.txt](https://github.com/qzeleza/kvas/files/9904069/debug.txt)

**Comment by qzeleza** [comment]
> Это нормальное поведение или ошибка в пакете?

Пожалуйста будьте внимательны [при прочтении сообщений на форуме](https://forum.keenetic.com/topic/14415-%D0%BF%D1%80%D0%BE%D0%B1%D1%83%D0%B5%D0%BC-%D0%BA%D0%B2%D0%B0%D1%81-shadowsocks-%D0%B8-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-vpn-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/?do=findComment&comment=154477):
В данной бете добавлены дополнительные сообщения в лог роутера, которые позволяют более эффективно отслеживать ошибки при отладке. В дальнейшем большинство из них удалю. Также, сейчас, при установке пакета, Вы сможете видеть ошибки, которые сыпятся в лог роутера - это служебная информация, которая никак не влияет на последующую работу пакета. Обращать стоит внимание, на последующие сообщения/ошибки, выделенные красным цветом во время его работы.

**Comment by KirillShchetinnikov** [comment]
Судя по тексту в логах, данные действия не должны производиться каждые 5 секунд. К тому же частая перезапись как логов, так и таблиц маршрутизации приведёт к более быстрому выходу из строя внутренней памяти роутера. 
Так же наблюдается проблема с открытие мобильного приложения сбербанка. С запущенным КВАС он не открывается, а так же не работает телевидение от билайн на IPTV. После удаления пакета доступ восстанавливается. Переустановка не помогает. На 18 версии такой проблемы нет.

**Comment by Horizont32** [comment]
![D698CD50-1904-4B85-9FF4-FFB61C66C982](https://user-images.githubusercontent.com/42933596/199338024-65602f6c-8a94-4f1a-97cd-dfc702951f3d.jpeg)

судя по графику загрузки, все это приводит сначала к очистке таблицы в один момент, а потом полной загрузке роутера, отсутствию возможности зайти даже на вебморду. Лог, соответсвенно, добыть тоже не могу.

**Comment by qzeleza** [comment]
Как временная мера **kvas reset**

> Судя по тексту в логах, данные действия не должны производиться каждые 5 секунд.

На основании какого именно теста в логах Вы сделали подобный вывод? Каждые пять минут скорее всего срабатывает механизм ndm, квас в данном случае не имеет к этому отношения.  



> потом полной загрузке роутера, отсутствию возможности зайти даже на вебморду. Лог, соответсвенно, добыть тоже не могу.

Вы зачем хотите заходить в WUI и лог снимать именно в момент полной загрузки процессора? 
Просто нужно подождать 1-2 сек и войти как обычно или Вы не можете в принципе выполнить команду `kvas debug > log.txt` ?

**Comment by Horizont32** [comment]
> Как временная мера **kvas reset**
> 
> > Судя по тексту в логах, данные действия не должны производиться каждые 5 секунд.
> 
> На основании какого именно теста в логах Вы сделали подобный вывод? Каждые пять минут скорее всего срабатывает механизм ndm, квас в данном случае не имеет к этому отношения.
> 
> > потом полной загрузке роутера, отсутствию возможности зайти даже на вебморду. Лог, соответсвенно, добыть тоже не могу.
> 
> Вы зачем хотите заходить в WUI и лог снимать именно в момент полной загрузки процессора? Просто нужно подождать 1-2 сек и войти как обычно или Вы не можете в принципе выполнить команду `kvas debug > log.txt` ?

Не мог, да, роутер в ноль завис. 

Сегодня произошло то же самое при удалении facebook.com из списка командой kvas rm *facebook.com, но через 2 минуты отвисло. 

![46810735-B85D-4C5F-9F82-A24FA5BFFC69](https://user-images.githubusercontent.com/42933596/199563076-57a9725d-9f80-429c-aa06-a65ce11f4d91.jpeg)

**Comment by KirillShchetinnikov** [comment]
> На основании какого именно теста в логах Вы сделали подобный вывод? Каждые пять минут скорее всего срабатывает механизм ndm, квас в данном случае не имеет к этому отношения.

Посмотрите на мои скриншоты. На них одни и те же действия кваса срабатывают каждые 5 СЕКУНД. При этом через роутер не проходит трафик, т.е. не добавляются новые домены по wildcard маске в список разблокировки. Должны ли iptables обновляться каждые 5 секунд?

**Comment by qzeleza** [comment]
> Посмотрите на мои скриншоты. На них одни и те же действия кваса срабатывают каждые 5 СЕКУНД. 

Простите, но если действительно внимательно присмотреться к временным меткам на опубликованных Вами, то каждых 5 сек там ничего не происходит. Там происходит запуск файла **100-proxy-redirect** с частотой в 2 сек. и повторяется 2 раза подряд. 
Это, в свою очередь, мне говорит о том, что данный файл вызывается при срабатывании прерывания от **ndm** и при каком-то изменении правил в **iptables**.

**Comment by qzeleza** [comment]
> Сегодня произошло то же самое при удалении facebook.com из списка командой kvas rm *facebook.com, но через 2 минуты отвисло.

У меня на Giga удаление занимает не более 5 сек. Возможно тут проблема со сторонними пакетами, которые работают в фоне? 

> Да, кстати, не очень-то стабильно работает обход.

В чем именно выражается "не-очень-стабильность"?

**Comment by Horizont32** [comment]
> > Сегодня произошло то же самое при удалении facebook.com из списка командой kvas rm *facebook.com, но через 2 минуты отвисло.
> 
> У меня на Giga удаление занимает не более 5 сек. Возможно тут проблема со сторонними пакетами, которые работают в фоне?
> 
> > Да, кстати, не очень-то стабильно работает обход.
> 
> В чем именно выражается "не-очень-стабильность"?

Инстаграм к примеру открывается один раз из 10м при этом период update выставлен на час. Достаточно часто отваливается AGH, приходится заново его переподключать. 

По предыдущему вашему реплаю на мой пост:

Дело в том, что такое случилось в первый раз, никогда до этого никаких проблем не было. Пакетов кроме kvas и AGH, который ставится квасом, нет.

**Comment by qzeleza** [comment]
> Пакетов кроме kvas и AGH, который ставится квасом, нет.

Чем снимали графики загрузки памяти и CPU?

**Comment by Horizont32** [comment]
> > Пакетов кроме kvas и AGH, который ставится квасом, нет.
> 
> Чем снимали графики загрузки памяти и CPU?

Да это ж стандартная прила от кинетика на телефон)

**Comment by KirillShchetinnikov** [comment]
> Это, в свою очередь, мне говорит о том, что данный файл вызывается при срабатывании прерывания от **ndm** и при каком-то изменении правил в **iptables**.

А должны ли правила в Iptables так часто обновляться? Если такие логи появляются всегда, даже без сетевой активности через роутер, и открытии ресурсов из списка разблокировки?

**Comment by qzeleza** [comment]
> А должны ли правила в Iptables так часто обновляться? Если такие логи появляются всегда, даже без сетевой активности через роутер, и открытии ресурсов из списка разблокировки?

Это вопрос к разработчикам **ndm** в **opkg**. **Квас** к этому отношения не имеет, скрипты запускаются ровно тогда, когда происходит пребывание настроенное в **ndm**.

**Comment by qzeleza** [comment]
Выпущена 20 бета пакета. Проверяем.
Жду обратной связи.

**Comment by qzeleza** [comment]
Вопрос закрыт или остается на повестке?

**Comment by KirillShchetinnikov** [comment]
Вопрос закрыт
