### ISSUE TITLE
[FEATURE REQUEST] Support DPI changing like in ByeDPI/GoodbyeDPI

### ISSUE THREAD

**Issue by Maks-gaming** [qzeleza/kvas#140]
It would be extremely useful to work with DPI replacement, as it is likely to be sometimes faster than packet tunneling.
Reference: https://github.com/ValdikSS/GoodbyeDPI

**Comment by qzeleza** [comment]
Пакет Квас написал на русском языке для русско-язычных пользователей. 
Хотите что-то спросить - напишите на русском, чтобы Вас поняли все кто читает обращение.
