### ISSUE TITLE
[ОШИБКА] Проверьте свое интернет соединение!

### ISSUE THREAD

**Issue by wolfam0108** [qzeleza/kvas#141]
При первом запуске, на свеже установленом OPKG Entware:
При выполнении: opkg install curl && curl -sOfL http://kvas.zeleza.ru/install && sh install
Получаю ошибку: [ОШИБКА] Проверьте свое интернет соединение!

Что совершенно не соответсвует правде.
Любые пакеты ставятся и обновляются через ту же консоль.
Подключение PPPoE - ростелеком.
Из важного - железка XIAOMI R3P, прошивка 4.1.7 (ZM.16), Xiaomi R3P (KN-1011) RU.
В чем может быть проблемма, почему скрипт упорно считает что нет интернета?

**Comment by qzeleza** [comment]
Спасибо за Ваш вопрос. Насколько я помню Вам в канале телеграмм уже отвечали на данный вопрос - проблема в том, что API кинетика видимо корреткно работает только на своих роутера - оригинальных.

**Comment by pymen** [comment]
подтверждаю ошибку на последнем релизе
http://kvas.zeleza.ru/install --> https://raw.githubusercontent.com/qzeleza/kvas/main/opt/bin/main/upgrade

package_url=$(curl -sH "Accept: application/vnd.github.v3+json" ${release_url}/latest | sed -n 's/.*browser_download_url\": "\(.*\)\"/\1/p;'| tr -d ' ' |  sed '/^$/d')

отдает пустоту

пришлось вручную вписать
package_url="https://github.com/qzeleza/kvas/releases/download/v1.1.8/kvas_1.1.8-release_2_all.ipk"
