### ISSUE TITLE
Неизвестная ошибка при установке

### ISSUE THREAD

**Issue by Chimildic** [qzeleza/kvas#143]
**Опишите проблему.**
Квас не устанавливается

**Какие шаги, привели к ошибке/проблеме?**
Пишу команду
```
curl -sOfL http://kvas.zeleza.ru/install && sh install
```
Получаю такой ответ:

![image](https://github.com/user-attachments/assets/c5c20b50-f171-402f-b94b-d168dfdfd161)

После при обращении к `kvas` отвечает, что команды нет. То есть установка не прошла.

**Заполните информацию о самом роутере**
- Keenetic Extra KN-1710
- 3.8.7

**Comment by Chimildic** [comment]
Установщик хочет поставить редактор `nano`, но спотыкается. Потому что `nano` уже был установлен ранее для других нужд. После удаления `nano` командой `opkg remove nano`, установка кваса прошла успешно.

**Comment by qzeleza** [comment]
В следующей версии данная проблема будет устранена
