### ISSUE TITLE
не всегда автоматом стартует ssr-соединение

### ISSUE THREAD

**Issue by Monoboy4ik** [qzeleza/kvas#144]
**Опишите проблему.**
когда ты делаешь kvas ssr new и успешно добавляешь ssr подключение, я считал (и вроде так и работало раньше), что квас автоматом переключается и запускает это соединение, но этого не происходит

**Какие шаги, привели к ошибке/проблеме?**
kvas ssr new, далее указал ссылку вида ss:// , после чего настройка соединения завершилась, но сервис был остановлен, далее пришлось запускать kvas vpn set и принудительно выбирать ssr-соединение, после чего оно стало "подключено", то есть сервис запустился

**Какие ожидания о поведении программы?**
при успешном добавлении ssr-соединения, оно поднимается автоматически (запускается) и выбирается текущим

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.2 бета 2
- Тип устройства Ultra KN-1811

**Comment by qzeleza** [comment]
Спасибо, посмотрю.

**Comment by lexuspro** [comment]
> Спасибо, посмотрю. 

Поддерживанию автора, есть проблемы в работе ssr

**Comment by qzeleza** [comment]
Проверьте на новой версии.
