### ISSUE TITLE
Добавление своих адресов в kvas.dnsmasq

### ISSUE THREAD

**Issue by Driv3r92** [qzeleza/kvas#148]
Добрый день. Хочу добавить в файл kvas.dnsmasq адрес ipset=/:.*youtube\.com:/unblock 
после ручного добавления выполняю команду /opt/etc/init.d/S56dnsmasq restart   все работает, но при перезапуске роутера- все слетает на дефолт.
Ротуре keenetic extra версия kvas latest.

**Comment by qzeleza** [comment]
Доброго дня
Квас предназначен для удобной работы со списками доменных имен, которая не предполагает вмешательства пользователя в его настройки. Если Вам необходимо что-то либо настроить вручную выбирайте иной инструмент, отличный от Кваса.
