### ISSUE TITLE
kvas routing steam over vpn

### ISSUE THREAD

**Issue by lunsige** [qzeleza/kvas#149]
**Опишите проблему.**
kvas routing steam over vpn

**Какие шаги, привели к ошибке/проблеме?**
1. Запуск загрузки со стима
2. Смена сервера на любой
3. Тот же итог

**Какие ожидания о поведении программы?**
Загрузка со стима идет напрямую, без роутинга

**Приложите снимки экрана или сам текст с консоли.**
![image](https://github.com/user-attachments/assets/34a2cfbc-ce33-475f-82bc-4f398fd9f7ae)

*Software Specs*
Windows 11 23H2 22631.4112
Steam 1724878532

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Keenetic
- Giga
- KN-1011

**Comment by qzeleza** [comment]
О чем речь? 
На родном для Вас языке опишите подробно проблему.

**Comment by lunsige** [comment]
> О чем речь? На родном для Вас языке опишите подробно проблему.

Проблема с тем, что трафик из приложения Steam идет через Socks подключение.

**Comment by LexPanov** [comment]
Добрый день!
Помогла рекомендация из 
<https://forum.keenetic.ru/topic/14415-%D0%BF%D1%80%D0%BE%D0%B1%D1%83%D0%B5%D0%BC-%D0%BA%D0%B2%D0%B0%D1%81/page/24/#comment-168322>
Убрать из списка разблокировки `*t.co`
