### ISSUE TITLE
Бета 19 не могу запустить

### ISSUE THREAD

**Issue by goldfoxigor** [qzeleza/kvas#15]
Добрый день!
Ставлю квас бету 19 как обычно на свеженастроенный роутер. прошивка 3.8.5 после установки нет обхода и нет интернета вообще. Раньше при первой установке сразу нужно было вводить параметры для shadowsocks, а теперь после установки нужно вводить команду kvas ssr new и вводить данные. в общем что я только не делал но так он у меня и не заработал.   test и debug и update толку ноль.
[log.txt](https://github.com/qzeleza/kvas/files/9939516/log.txt)
может какие то новые подготовительные действия нужно проводить? а я пропустил?

**Comment by qzeleza** [comment]
Доброго вечера,
В Вашем случае, судя по логу, не прописались правила в iptables.
Попробуйте `kvas reset`

**Comment by goldfoxigor** [comment]
Добрый день! Что я только не пробовал, не работает и всё 19-я версия. На данный момент стоит adguardhome и КВАС 14 бета, всё работает вроде без проблем. Если удалить квас 14 `opkg remove kvas` и поставить 19-ю версию начинаются проблемы, то установка вообще не может до конца дойти, то `kvas test` `kvas reset` `kvas debug` `kvas update` не проходят до конца, просто зависает в каком-то месте и всё. Так же пробовал удалять квас с командой `--autoremove`.  Пробовал ставить всё начисто без adguardhome и с ним.

**Comment by qzeleza** [comment]
Выпущена 20 бета пакета. Проверяем.
Жду обратной связи.

**Comment by goldfoxigor** [comment]
вечер добрый! 

BusyBox v1.35.0 (2022-08-08 06:21:00 UTC) built-in shell (ash)

~ # opkg update
Downloading http://bin.entware.net/mipselsf-k3.4/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Downloading http://bin.entware.net/mipselsf-k3.4/keenetic/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/keendev
~ # opkg remove kvas
Removing package kvas from root...
---------------------------------------------------------------------------------
Удаление пакета КВАС™ версия 1.0. beta 14...
---------------------------------------------------------------------------------
Удаляем файлы конфигурации...                                     УСПЕШНО
Удаляем данные из cron...                                         УСПЕШНО
Очищаем все правила и таблицы...                                  УСПЕШНО
---------------------------------------------------------------------------------
При установке пакета КВАС™ были установлены следующие пакеты:
shadowsocks-libev-ss-redir knot-dig iptables curl cron libpcre
shadowsocks-libev-config dnsmasq-full nano-full bind-dig ipset jq
Если данные пакеты Вами больше не используются, Вы можете их удалить следующей
командой:  opkg remove kvas --autoremove все сразу, либо
командой opkg remove <package1 package2 package3...>.
---------------------------------------------------------------------------------
Удаление КВАСа завершено.
---------------------------------------------------------------------------------
~ # opkg install /opt/kvas_1.0-beta_20_all.ipk
Installing kvas (1.0-beta_20) to root...
Configuring kvas.
-----------------------------------------------------------------------------------
Установка пакета КВАС™ версия 1.0-beta-20
-----------------------------------------------------------------------------------
Обновить список интерфейсов [Y/N,Q]?                                y
-----------------------------------------------------------------------------------
Производим сканирование интерфейсов!
Сохраняйте терпение и спокойствие!
-----------------------------------------------------------------------------------
Выберите VPN интерфейс для работы пакета
-----------------------------------------------------------------------------------
1. Интерфейс shadowsocks [текущий]                                  В СЕТИ
-----------------------------------------------------------------------------------
Выберите номер варианта VPN соединения [1-1]:                       1
Останавливаем сервис shadowsocks...                                 ГОТОВО
Интерфейс shadowsocks подключен                                     УСПЕШНО
-----------------------------------------------------------------------------------
На роутере обнаружен AdGuard Home
Установить AdGuard Home, как основной DNS сервер [Y/N,Q]?           y
AdGuard Home установлен в качестве основного DNS сервера            УСПЕШНО
-----------------------------------------------------------------------------------
Настройка файлов конфигурации пакета                                ГОТОВО
Обнаружен список разблокировки от предыдущей установки
Список разблокировки восстановлен                                   УСПЕШНО
Ставим обновление ip адресов по умолчанию - каждые 12 часов...      ГОТОВО
Запускаем КВАС в работу                                             УСПЕШНО
-----------------------------------------------------------------------------------
Установка КВАСа завершена.
Для общей справки наберите kvas help
-----------------------------------------------------------------------------------
~ # kvas test
-----------------------------------------------------------------------------------
Состояние службы dnsmasq                                            /opt/bin/kvas: line 80: /opt/etc/init.d/S56dnsmasq: not found
ОСТАНОВЛЕНА
Перезапускаем еще раз dnsmasq                                       ОШИБКА
Запустите диагностику командой kvas debug
~ #

**Comment by qzeleza** [comment]
Вижу пока только один вариант решения - это доступ по ssh на ваше устройство.
Если готовы, то напишите в личку на форуме.

**Comment by goldfoxigor** [comment]
BusyBox v1.35.0 (2022-08-08 06:21:00 UTC) built-in shell (ash)

~ # kvas debug
-----------------------------------------------------------------------------------
Состояние службы dnsmasq по команде
/opt/etc/init.d/S56dnsmasq status                                   ОСТАНОВЛЕНА
-----------------------------------------------------------------------------------

dnsmasq: failed to create listening socket for port 53: Address already in use
[] Проблемы при выделении адресов для аренды DHCP
~ #

**Comment by xPROMSx** [comment]
> BusyBox v1.35.0 (2022-08-08 06:21:00 UTC) built-in shell (ash)
> 
> ## ~ # kvas debug
> ## Состояние службы dnsmasq по команде
> /opt/etc/init.d/S56dnsmasq status ОСТАНОВЛЕНА
> dnsmasq: failed to create listening socket for port 53: Address already in use [] Проблемы при выделении адресов для аренды DHCP ~ #

У вас такая же проблема, как я описал https://github.com/qzeleza/kvas/issues/17
Введите kvas adguard on, как временное решение проблемы и пользуйтесь.

**Comment by qzeleza** [comment]
> dnsmasq: failed to create listening socket for port 53: Address already in use
> [] Проблемы при выделении адресов для аренды DHCP

Прошу Вас, прислать карту действий по воспроизведению ошибки. Т.е. описать какие шаги, которые приводят к ошибке и в каком порядке делали, чтобы я смог воспроизвести ее на своем устройстве.

**Comment by goldfoxigor** [comment]
> > dnsmasq: failed to create listening socket for port 53: Address already in use
> > [] Проблемы при выделении адресов для аренды DHCP
> 
> Прошу Вас, прислать карту действий по воспроизведению ошибки. Т.е. описать какие шаги, которые приводят к ошибке и в каком порядке делали, чтобы я смог воспроизвести ее на своем устройстве.

настроить роутер с нуля, у меня подключение через сотового оператора модем fibocom l860GL, настроить entware на внешнем USB носителе, установить и настроить adguard **через все интерфейсы**, установить и настроить квас 14  через SS, потом удалить 14-ю версию и поставить 20-ю, вроде всё. квас  то свои задачи выполняет и обход работает и даже после перезагрузки роутера, но вот есть такая ошибка с dnsmasq.

**Comment by qzeleza** [comment]
Ошибку нашел, в 21 бете выйдет исправление.

**Comment by goldfoxigor** [comment]
спасибо вам за ваш труд!

**Comment by qzeleza** [comment]
Вышла бета 21, прошу проверить и сообщить о результатах тестов по данной ошибке.

**Comment by goldfoxigor** [comment]
хорошо

**Comment by goldfoxigor** [comment]
День добрый!  в процессе установки 21-ой версии зависло на этапе запуска квасА. перезапустил SSH соединение проверил командой kvas test, всё прошло успешно, на данный момент времени всё вроде работает, если будут проблемы обязательно отпишусь.
