### ISSUE TITLE
не получается установить КВАС вручную

### ISSUE THREAD

**Issue by qellyka** [qzeleza/kvas#152]
**Опишите проблему.**
Хотел установить версию КВАСА 1.1.8, т.к. с бета версией проблемы(не работает ss), но при вводе команды для установки постоянно выдавало ошибки.

**Какие шаги, привели к ошибке/проблеме?**
Опишите подробно шаги, которые привели к ошибке:

1. opkg install https://github.com/qzeleza/kvas/releases/download/v1.1.8/kvas_1.1.8-release_2_all.ipk
2. Выдало ошибку

**Какие ожидания о поведении программы?**
Установка КВАСА версии 1.1.8

![image](https://github.com/user-attachments/assets/1007e46c-84f4-44f3-994f-7921a9a03b00)

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.1.7
- Тип устройства Hopper KN-3810

**Comment by balkarov** [comment]
Тоже столкнулся с данной проблемой на 1.1.9 версии. Не работает ss. На 1.1.8 все работало. 
Отпишитесь, пожалуйста,  у кого получится установить 1.1.8

**Comment by qzeleza** [comment]
Вышла новая версия.
