### ISSUE TITLE
Ошибка в main

### ISSUE THREAD

**Issue by PsychodelEKS** [qzeleza/kvas#153]
Ошибка `/opt/bin/kvas: /opt/apps/kvas/bin/libs/main: line 268: syntax error: unexpected "||"`

https://github.com/qzeleza/kvas/blame/3de914701a38e72d554be73fd2ec90e277b197c9/opt/bin/libs/main#L268

![image](https://github.com/user-attachments/assets/e33e6ba3-4084-4560-b7a5-1bd6e5b83841)

**Comment by PsychodelEKS** [comment]
и еще такая ошибка вылезает

`/opt/bin/kvas: line 44: syntax error: unexpected "}"`

**Comment by PsychodelEKS** [comment]
как откатиться на 1.1.8:

- сохраняем список доменов через `kvas export /opt/etc/.kvas/kvas.list` (нужно проверить, что файл сгенерился) или копируем из `kvas list`
- `kvas uninstall full` - удаляем "битый", если ругается на синтаксические ошибки (из бага), нужно поправить их в файлах через nano/mcedit
- перезагрузка
- `cd /opt/tmp` переходим в tmp директорию
- `rm -i *` очищаем ее
- `curl -sOfL https://github.com/qzeleza/kvas/releases/download/v1.1.8/kvas_1.1.8-release_2_all.ipk` качаем рабочую версию
- `opkg install kvas_1.1.8-release_2_all.ipk` запускаем установку
- `kvas setup` после перезагрузки настраиваем заново

**Comment by qzeleza** [comment]
Доброго дня 
Данные ошибки исправлены. Обновитесь на новый выпуск пакета r3
