### ISSUE TITLE
Проблемы с последней версией

### ISSUE THREAD

**Issue by qellyka** [qzeleza/kvas#154]
**Опишите проблему.**
При установке КВАСА версии 1.1.9 beta-3 есть проблемки. Точнее не при установке, а в использование. Короче говоря ss работает не постоянно youtube вообще не грузит.(с впн всё норм и списком доменов тоже, на версии 1.1.8 все работало.)

**Какие шаги, привели к ошибке/проблеме?**

1. Настроил ss, с первого раза не заработал
2. Поставил другую ссылку чяерез kvas ssr new, потом kvas vpn set и выбрал ss? заработал
3. Добавил ip-ники ютуба, не работает, захожу на myip2.ru все норм
4. Kvas purge, kvas test, захожу на ifconfig.me не работает(myip2.ru тоже)
5. Опять отчищаю, kvas test, теперь работает

**Какие ожидания о поведении программы?**
Стабильная работа

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.1.7
- Тип устройства Hopper KN-3810

P.S.
Можно как то установить версию 1.1.8?

**Comment by qzeleza** [comment]
https://github.com/qzeleza/kvas/wiki/Описание-команд#откат-пакета-на-предыдущие-версии

**Comment by qellyka** [comment]
> [https://github.com/qzeleza/kvas/wiki/Описание-команд#откат-пакета-на-предыдущие-версии](https://github.com/qzeleza/kvas/wiki/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4#%D0%BE%D1%82%D0%BA%D0%B0%D1%82-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0-%D0%BD%D0%B0-%D0%BF%D1%80%D0%B5%D0%B4%D1%8B%D0%B4%D1%83%D1%89%D0%B8%D0%B5-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8)

А дальше, при вводе команды меня выкинуло из терминала, я зашёл и усе)
![image](https://github.com/user-attachments/assets/22c75742-ce6e-471d-99d8-ce459d5ea034)
