### ISSUE TITLE
Сайты из списка unblock не открываются

### ISSUE THREAD

**Issue by it800** [qzeleza/kvas#155]
**Опишите проблему.**
Судя по тому, что я вижу, некорректно отрабатывает отправка пакетов в wireguard туннель для сайтов, которые добавлены в список кваса:
Обмен пакетами с 195.201.201.32 по с 32 байтами данных:
Ответ от 195.201.201.32: число байт=32 время=87мс TTL=55
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.

Только один пакет уходит нормально для IP-адреса из списка unblock. Остальные сайты (которые напрямую идут в интернет) работают корректно. 

**Какие шаги, привели к ошибке/проблеме?**
Выполнил установку по инструкции, перенёс нужные девайсы в профиль по-умолчанию, выполнил все шаги включая Adguard Home. В итоге всё работает, кроме сайтов, которые должны ходить через ВПН

**Заполните информацию о системе на роутере:**
KeeneticOS 4.2beta3
Хром 128
SecureCRT

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.2beta3
- Тип устройства: Giga KN-1010]

[debug.log](https://github.com/user-attachments/files/16905689/debug.log)

**Comment by qzeleza** [comment]
Писал ранее, что с прошивками выше той, которая является стабильной (4.1.7), Квас не тестируется и гарантируется его работа.
