### ISSUE TITLE
Не добавляются новые списки для фильтрации рекламы

### ISSUE THREAD

**Issue by Mike6386** [qzeleza/kvas#157]
После добавления новых списков (по команде kvas adblock edit) для фильтрации рекламы или прямое редактирование файла /opt/etc/adblock/sources.list, а также если не добавлять новые, а просто убрать # у существующих, то все изменения не сохраняются после перезапуска kvas adblock off/on. 
Также нет команды на обновление списков без перезапуска adblock (например, по команде kvas adblock update).

**Comment by qzeleza** [comment]
> После добавления новых списков (по команде kvas adblock edit) для фильтрации рекламы или прямое редактирование файла /opt/etc/adblock/sources.list, а также если не добавлять новые, а просто убрать # у существующих, то все изменения не сохраняются после перезапуска kvas adblock off/on. Также нет команды на обновление списков без перезапуска adblock (например, по команде kvas adblock update).

Как Вы поняли, что этого не происходит?
Есть экранные снимки (скриншоты) Ваших действий?

**Comment by Mike6386** [comment]
> > После добавления новых списков (по команде kvas adblock edit) для фильтрации рекламы или прямое редактирование файла /opt/etc/adblock/sources.list, а также если не добавлять новые, а просто убрать # у существующих, то все изменения не сохраняются после перезапуска kvas adblock off/on. Также нет команды на обновление списков без перезапуска adblock (например, по команде kvas adblock update).
> 
> Как Вы поняли, что этого не происходит? Есть экранные снимки (скриншоты) Ваших действий?

После включения adblock, файл /opt/etc/adblock/sources.list откатывается со списком источников до внесения изменений и обновление списка доменов всегда происходит соответственно только по 7 источникам прописанным по-дефолту.

**Comment by qzeleza** [comment]
Прошу протестировать [версию Кваса 1.1.9b4](https://t.me/kvas_pro/3310/13219) - осталась ли проблема?

**Comment by qzeleza** [comment]
Исправлено в версии Кваса 1.1.9b6.
