### ISSUE TITLE
Обход замедления YouTube

### ISSUE THREAD

**Issue by FlamestoN** [qzeleza/kvas#160]
Добрый день

Хочу проксировать ютуб через vpn, добавил эти записи

Защищенный список содержит 8 записей:
------------------------------------------------------------------------------------------------------------------------------------------
*2ip.ru
*googlevideo.com
*instagram.com
*youtu.be
*youtube.com
*ytimg.com
ifconfig.me
myip2.ru
------------------------------------------------------------------------------------------------------------------------------------------

Но ютуб по прежнему плохо грузится
ifconfig.me показывает айпи vpn
скорость на сервере vpn 1gbit/s
Может нужно еще какие-то домены добавить?

1.1.9 beta-3

**Comment by FlamestoN** [comment]
Как понимаю из-за большего пула адресов *googlevideo.com не успевает все адреса заворачивать в впн
Нашел такую ссылку https://www.gstatic.com/ipranges/goog.json с ветки https://forummikrotik.ru/viewtopic.php?t=16909&start=10
Если бы можно было бы добавить автоматическое обновление с этой ссылки, было бы супер

**Comment by qzeleza** [comment]
Как данный вопрос относится непосредственно к работе Кваса?

**Comment by FlamestoN** [comment]
> Как данный вопрос относится непосредственно к работе Кваса?

Относится тем, что Квас не проксирует ютуб, и возможно все другие домены, которые используют пул адресов, вместо одного айпи адреса, и возможно, можно что-то придумать, например опрашивать айпи доменов чаще и навсегда сохранять прошлые айпи, замеченные за доменом для проксирования.
Это можно реализовать? Либо ваши предложения
