### ISSUE TITLE
Моменты по 1.1.9 r3 (beta3)

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#162]
**При чистой установке.**
1. Есть ошибка обновления opkg. Не понятно почему. Перед этим руками обновлял, все успешно.. 
```
~ # cd /opt/packages/
/opt/packages # curl -sOfL http://kvas.zeleza.ru/install && sh install
Проверка наличия интернета                                        ПРИСУТСТВУЕТ
--------------------------------------------------------------------------------
Установка пакета КВАС версии [1.1.9 beta-3]
--------------------------------------------------------------------------------
Обновляем библиотеку пакетов opkg...                                     ОШИБКА
Загружаем пакет...                                                       ГОТОВО
```

2.  Устанавливаем новую версию пакета [1.1.9 beta-3]  заняло примерно минуты 3. 
В качестве пожелания, было удобно иметь возможность запускать установку с выводом всех деталей в консоль (чтобы видеть что происходит). Знаю что в файл все пишется, но это не-интерактивно..

3. В мастере установки использовал кодированную ss строку.  Всё принялось без каких либо вопросов.

**Но по тестам при переходе на сайты = маршрут через ss почему то не заработал, хотя по kvas test все зеленое и вроде все хорошо**

[kvas_debug.txt](https://github.com/user-attachments/files/17002065/kvas_debug.txt)

4. в kvas debug обращает на себя внимание, что список хостов отображается дважды, один раз где все видно- из kvas.dnsmasq, а потом в защищенном режиме из hosts.list
```
Защищенный список в /opt/etc/dnsmasq.d/kvas.dnsmasq (все записи)
--------------------------------------------------------------------------------
*****=/myip2.ru/unblock
*****=/:.*2ip\.ru:/unblock
*****=/ifconfig.me/unblock

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Защищенный список /opt/etc/hosts.list (все записи)
--------------------------------------------------------------------------------
*****ru
*****fig.me
*****.ru

--------------------------------------------------------------------------------
```

5. В kvas debug как будто есть ошибка в описании.
Таблица ipset показана пустой, но в то же время есть запись
**Все записи в таблице unblock прошли проверку.** это противоречиво, или я чего то не понимаю.
```
--------------------------------------------------------------------------------
Таблица ipset (10 крайних записей)
команда: 'ipset list unblock'
--------------------------------------------------------------------------------

...
...
...

--------------------------------------------------------------------------------
Проверка наличия ip адресов хостов в таблице ipset
Таблица защиты unblock отсутствует в списке ipset
Проверьте работу скрипта /opt/apps/kvas/bin/main/ipset
Все записи в таблице unblock прошли проверку.
```

6. Нашел причину почему не заработал ss. 
При установке через кодированную строку, квас обрезал последний символ пароля и в \opt\etc\shadowsocks.json по итогу пароль неверный был)
Кодированная строка была вида ss://Y2hhY2hhRudFpLUlRCcA@my.serverru:53184?type=tcp#ss-2-chacha20-bighome-kvas

7. В качестве вопроса- предложения. Может ли квас при настройке делать тестовый запуск ss-redir и пускать через него какой нибудь запрос\пинг\что угодно, чтобы можно было точно знать что конфиг ss работает?
В целом не хватает какой то отладки статуса ssr соединения. 
Сейчас конфиг с неверным паролем показывается как успешный.

8. Есть баг - если выполнять kvas export не указав имя файла, то будет такой ответ
```
~ # kvas export
--------------------------------------------------------------------------------
Так как не задано имя файла для экспорта, то
Сохраняем архив в файл /opt/etc/.kvas/backup/hosts.list
Сохраняем записи в файл ...                                                     /opt/bin/kvas: line 2750: can't create : nonexistent directory
ОШИБКА
--------------------------------------------------------------------------------

```

**Заполните информацию о самом роутере:**
- Keenetic Viva KN-1910
- Прошивка на роутере: 4.1.7

9. При вводе kvas add tags есть техническая информация в терминале
```
~ # kvas add tags
--------------------------------------------------------------------------------
Список заквасок для добавления:
--------------------------------------------------------------------------------
1. kvas                                                                ЧАСТИЧНО
2. microsoft                                                        ОТСУТСТВУЕТ
3. youtube                                                          ОТСУТСТВУЕТ
4. docker                                                           ОТСУТСТВУЕТ
5. games                                                            ОТСУТСТВУЕТ
6. ai                                                               ОТСУТСТВУЕТ
--------------------------------------------------------------------------------
Выберите номер закваски из списка [1-6], A:Все, Q:Выход: 6
+ '[[' 6 '=~' '[aA]' ]]
+ sed -n+ tr -d ' '
 6p
+ sed 's/^[0-9]\{1,3\}. \(.*\) .* .*$/\"\1\"/; /^$/d'+ echo -e '1. kvas
               ЧАСТИЧНО\n2. microsoft                                                        ОТСУТСТВУЕТ\n3. youtube                                                          ОТСУТСТВУЕТ\n4. docker
               ОТСУТСТВУЕТ\n5. games                                                            ОТСУТСТВУЕТ\n6. ai
                                                         ОТСУТСТВУЕТ\n'

+ chosen_tag='"ai"'
+ eval 'tag_selected="ai"'
+ tag_selected=ai
+ set +xeu
--------------------------------------------------------------------------------
```

10. Было бы удобно, иметь возможность запускать дебаг, чтобы он И отображался в консоли И записывался в файл.
Сейчас запуск  команды kvas debug debug.txt  не будет показывать интерактивно результаты дебага

**Comment by qzeleza** [comment]
Спасибо за подробный отчет по проблемам. Постараюсь посмотреть и проверить по всем пунктам, как будет время.

Касательно проверки работы ssr соединения, то если сможете найти рабочий способ проверки соединения на самом роутере - буду Вам премного благодарен. Пока такого способа я не знаю. 
Авторы ssr предлагают проверять только есть ли pid самого процесса при запуске и это все.

**Comment by qzeleza** [comment]
Нашел время посмотреть более подробно Ваши комментарии:

1. Исправил
2. Такая необходимость лишь у очень малого числа пользователей - Квас предназначен для людей с минимальным порогом входа. Не вижу необходимости в этом
3. В строке зашит не только пароль, но и кодировка, у Вас строка без котировки потому происходит смещение. Кодировка пишется через двоеточие. Но сделал доп проверку на наличие двоеточия в пароле
4. Так и задумано, это разного типа проверки
5. Исправил
6. см пп.3
7. Не знаю пока корректной проверки ssr соединения
8. Исправил
9. Убрал
10. Добавил

**Comment by badigit** [comment]
Спасибо!
Насчет п.4 поправьте если ошибаюсь.
Я полагал что звездочки в именах хостов нужны для повышения конфиденциальности - например когда делишься своим debug. Выглядит логично.
Но поскольку имена хостов все равно видны чуть выше в kvas.dnsmasq, то не совсем понятно смысл скрывать их в hosts.
Если речь конфиденциальности, то надо скрывать везде. Иначе можно вообще не скрывать, если и так все видно
```
Защищенный список в /opt/etc/dnsmasq.d/kvas.dnsmasq (все записи)
--------------------------------------------------------------------------------
*****=/myip2.ru/unblock
*****=/:.*2ip\.ru:/unblock
*****=/ifconfig.me/unblock

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Защищенный список /opt/etc/hosts.list (все записи)
--------------------------------------------------------------------------------
*****ru
*****fig.me
*****.ru

--------------------------------------------------------------------------------
```

**Comment by qzeleza** [comment]
Прошу протестировать [версию Кваса 1.1.9b4](https://t.me/kvas_pro/3310/13219) - остались ли проблемы выше?
