### ISSUE TITLE
YouTube и пул адресов 

### ISSUE THREAD

**Issue by FlamestoN** [qzeleza/kvas#163]
Квас не проксирует ютуб, и возможно все другие домены, которые используют пул адресов, вместо одного айпи адреса, и возможно, можно что-то придумать, например опрашивать айпи доменов чаще и навсегда сохранять прошлые айпи, замеченные за доменом для проксирования.
Это можно реализовать? Либо ваши предложения

**Comment by borovikovme** [comment]
@FlamestoN Вы можете https://www.gstatic.com/ipranges/goog.json за маршрутизировать принудительно через свой vpn и тем самым решить свою задачу. к KVAS это не относится.
