### ISSUE TITLE
[Поддержка OpenConnect в качестве VPN]

### ISSUE THREAD

**Issue by n00bsteam** [qzeleza/kvas#165]
Прошу добавить поддержку клиента OpenConnect или подсказать в каком конфиге изменить интерфейс для туннелирования.

В процессе установки предлагаются только OVPN\WG\SS туннели:
Выберите VPN интерфейс для работы пакета
------------------------------------------------------------------
1. Интерфейс shadowsocks [78.47.125.180] текущий         ОТКЛЮЧЕН
2. Интерфейс DigitalOcean текущий                        ОТКЛЮЧЕН
3. Интерфейс Antizapret [192.168.106.144] текущий          В СЕТИ
4. Интерфейс  [10.0.0.1] текущий                         ОТКЛЮЧЕН

- Производитель: [Keenetic]
- Прошивка на роутере: [4.2 Beta 4]
- Тип устройства [Giga KN-1011]

КВАС™ версии 1.1.9 beta_3

**Comment by qzeleza** [comment]
Пакет работает только с текущей версией KeenOS

**Comment by AltGrF13** [comment]
После релиза 4.2 «Клиент и сервер OpenVPN» теперь идёт из коробки. Протокол очень лёгкий и не детектируемый; так что, полагаю, этот вопрос будет ещё не раз всплывать. 

С другой стороны, а много ли желающих? Как минимум, опрос на форуме устроить стоит.
