### ISSUE TITLE
Соединение есть, но не открываются сайты из списка

### ISSUE THREAD

**Issue by Corleone5** [qzeleza/kvas#167]
Добрый день.
Установка проходит успешно, при этом при попытке открыть тестовый сайт для определения ip - он не открывается вообще.
другой сайт из списка, показывает мой IP ( не впновский).
Если добавить новый адрес в разблокировку, тут вообще проихсодит мистика - сайт перестает открываться вообще.

При этом, само ВПН соединение рабочее, пробовал через клиента на ПК.
Использую shadowsocks. ОЧень прошу помочь!!!!!

**Comment by qzeleza** [comment]
Абсолютно неинформативно сообщение - нет никаких данных для анализа. К сожалению помочь не представляется возможным.
