### ISSUE TITLE
Несколько профилей shadowsocks

### ISSUE THREAD

**Issue by Corleone5** [qzeleza/kvas#168]
Добрый день! Подскажите пожалуйста, а можно использовать как-то несколько профилей shadowssocks.
Опишу ситуацию, у меня есть беплатно 100GB VPN трафика в месяц на одном профиле. Когда он закончится, т.е соединение не будет устанавливаться, можно ли сделать так, чтобы квас переключался на второй профиль? 

Как вариант реализации:
1. сделать проверку через пинг любого узла из адреса разблокировки, если пинг не идет, переключится на 2-ую конфигурацию shadowsocks. 
2. Вторую конфу хратить в том же файле что и первую, либо в другом файле.
Спасибо! Это будет актуально для тех кто использует бесплатные vpn с ограниченным трафиком ( каких собственно больше всего) 
Заранее большое спасибо!

**Comment by qzeleza** [comment]
Доброго дня
Нет, такой вариант реализации в планах не стоит.
