### ISSUE TITLE
Скрипт ipset.kvas вызывает тайм-ауты при обращении к локальному DNS-серверу

### ISSUE THREAD

**Issue by Horun1992** [qzeleza/kvas#169]
**Проблема:**
При запуске скрипта `ipset.kvas`, который обновляет таблицу ipset с доменными именами, иногда возникают тайм-ауты при обращении к локальному DNS-серверу (AdGuard Home). DNS-сервер не успевает обработать домены, так как они проходят по циклу слишком быстро, что приводит к возникновению проблем. В нашем случае причиной является **Rate limit** в AdGuard.

**Шаги для воспроизведения проблемы:**
1. Включил и настроил AdGuard Home версии 0.107.52.
2. Запустил скрипт `./ipset.kvas`.
3. Для диагностики добавил сообщения о старте и завершении обработки доменов в консоль.
4. Обнаружил, что некоторые домены обрабатываются, а некоторые приводят к тайм-аутам.

**Ожидаемое поведение:**
Скрипт должен успешно обрабатывать все доменные имена без тайм-аутов.

**Фактическое поведение:**
Скрипт вызывает тайм-ауты. Например, в консоли виден следующий вывод:
;; WARNING: response timeout for 127.0.0.1@53(UDP)

**Роутер:**
- Производитель: Keenetic
- Прошивка: 4.2
- Тип устройства: Peak KN-2710

**Дополнительные пояснения:**
Для исправления ошибки предлагаю следующие решения:
1. Установить **Rate limit** на 0 по умолчанию в конфигурации AdGuard в блоке dns (желательно).
'/opt/etc/AdGuardHome/AdGuardHome.yaml'
![Screenshot from 2024-09-28 18-20-55](https://github.com/user-attachments/assets/e2102cf5-3433-4976-a80e-57f7dc1887de)

2. Добавить в скрипт `ipset.kvas` таймаут с помощью `usleep 300000` между запросами, чтобы избежать тайм-аутов (это также поможет снизить нагрузку на процессор). Но тут наверное каждый роутер свой таймаут должен сам выбирать.
![Screenshot from 2024-09-28 17-42-16](https://github.com/user-attachments/assets/60973b7e-0dcf-4609-ad64-2c765825695e)

**Comment by qzeleza** [comment]
Полагаю решением данной проблемы будет замена строки 
`until ADDRS=$(kdig +short ya.ru @localhost ) && [ -n "${ADDRS}" ] > /dev/null 2>&1; do sleep 5; done`
на 
`until ADDRS=$(kdig +short ya.ru @127.0.0.1:9153) && [ -n "${ADDRS}" ] || /opt/etc/init.d/S09dnscrypt-proxy2 restart &>/dev/null ; do sleep 10; done`

в файле **/opt/apps/kvas/bin/main/ipset**
