### ISSUE TITLE
Автоматический перезапуск ss-redir

### ISSUE THREAD

**Issue by muaddiib** [qzeleza/kvas#171]
Периодически падает ss-redir. 
/opt/etc/cron.5mins/check_vpn должен по-идее его поднимать, но нет.
Приходится руками "/opt/etc/init.d/S22shadowsocks restart".
Что-то не так с check_vpn? Как проверить?
По логам роутера крон5мин запускается..

**Comment by qzeleza** [comment]
Как Вы определили, что это именно так?

**Comment by muaddiib** [comment]
Перестали открываться сайты из списка kvas. Зашел по SSH: kvas ssr - сервис SHADOWSOCKS не запущен. 
Подождал минут 10, служба не поднялась. Посмотрел журнал роутера - cron5min отработал 2 раза за это время.
Скудные логи в системе - не Debian с коробки. Жду след. падение, что бы руками запустить check_vpn и как-то отследить, что не так.

**Comment by muaddiib** [comment]
. /opt/apps/kvas/bin/libs/main

добавил в скрипт, ошибок нет, но и нет рестарта тоже.

**Comment by stdcion** [comment]
Тоже самое, ручой запуск kvas test показывает, что shadowsocks был остановлен, происходит перезапуск, и снова все работает.

**Comment by qzeleza** [comment]
> а что в этой конструкции будет обьектом пинга? вы передаете вывод в пинг. не работает так. лишняя |
> 
> ping -c1 -A | grep "${ssr_ip}"

Спасибо, поправил в коде и здесь выше

**Comment by muaddiib** [comment]
и обязательно добавить после #!/bin/sh
. /opt/apps/kvas/bin/libs/main

иначе не известна половина переменных

**Comment by DreamCustody** [comment]
@qzeleza У Вас минорная опечатка связанная с этой правкой в последнем коммите [247405b](https://github.com/qzeleza/kvas/commit/247405bef326c325a25cd6503a313a1ea29059b9) в файле [HISTORY.md](https://github.com/qzeleza/kvas/blob/247405bef326c325a25cd6503a313a1ea29059b9/HISTORY.md?plain=1)

Вы написали 172:
> Исправлена ошибка, связанная с проверкой ssr соединения (см. заявка #[172](https://github.com/qzeleza/kvas/issues/171))

Предполагается 171:
> Исправлена ошибка, связанная с проверкой ssr соединения (см. заявка #[171](https://github.com/qzeleza/kvas/issues/171))

**Comment by qzeleza** [comment]
Да, поздно увидел. Благодарю за внимательность. Попробую чуть позже поправить.
