### ISSUE TITLE
Wiki: Работа с "заквасками" - поправить команды добавления/удаления доменов из "заквасок"

### ISSUE THREAD

**Issue by Remmi** [qzeleza/kvas#172]
[Wiki, Раздел "Работа с "заквасками"](https://github.com/qzeleza/kvas/wiki/%D0%AD%D1%84%D1%84%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%B0%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B7%D0%B0%D0%BA%D0%B2%D0%B0%D1%81%D0%BA%D0%B0%D0%BC%D0%B8)

Сейчас:
> Создать свою закваску и добавить туда домен: kvas tags add домен метка,
> как пример, создаем закваску и добавляем домен в нее: kvas tags add tel.me telegram
> и затем добавляем второй домен в эту же закваску: kvas tags add telegram.me telegram

Правильно поменять домен и метку местами:
> Создать свою закваску и добавить туда домен: kvas tags add метка домен,
> как пример, создаем закваску и добавляем домен в нее: kvas tags add telegram tel.me
> и затем добавляем второй домен в эту же закваску: kvas tags add telegram telegram.me

---

Аналогично с удалением, сейчас:
> Удаляем домен из закваски: kvas tags del tel.me telegram

Правильно поменять домен и метку местами:
> Удаляем домен из закваски: kvas tags del telegram tel.me

**Comment by qzeleza** [comment]
Спасибо, обновил
