### ISSUE TITLE
Перезаполнение списка обхода

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#184]
1. Нужна какая-то команда типа `kvas rescan` для переобхода списка с преобразованием в IP (код, что сейчас в `opt/bin/main/ipset`). Сам же файл `opt/bin/main/ipset` просто будет вызывать этот метод, а не хранить всю логику.
2. Вышеназванный файл закидывается сейчас в директорию `cron.5mins`. А ведь там проход по всем записям из списка обхода и `kdig` их! Списки пухнут, это становится всё более затратной операцией (у некоторых новый крон начинается, хотя старый ещё не завершился). Можно при установке спрашивать человека желаемую частоту обхода, сохранять это в конфиг и просто закидывать файл в соответствующую директорию?
- 5mins (по-умолчанию)
- hourly
- daily
- weekly

Люди с маленькими списками останутся как и раньше, а большесписочные смогут выбрать иное значение. Или даже самим ручками сделать свой период благодаря команде из пункта 1.

**Comment by qzeleza** [comment]
От данной функции отказался во всех версиях, начиная с 1.1.9b2, вместо этого подхода создаются ipset таблицы с временной задержкой в одни сутки.

**Comment by AltGrF13** [comment]
Спасибо за пояснение! У меня 1.1.9 beta_3, но файл не был удалён пакетом при удалении и установке. Вот и ввёл в заблуждение.

В Телеграмме многие до сих пор рекомендуют его переносить, т.е. выжил он ни у одного меня. По коду вижу, да, что быть его и не должно.
