### ISSUE TITLE
Мелкие проблемы в 1.1.9

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#186]
Разное встреченное, не относящееся к узкоспециализированным задачам. Возможно, перекликается со #162 , но показалось правильнее отдельным вопросом.

**Comment by AltGrF13** [comment]
При старте гостевой в логе роутера
![image](https://github.com/user-attachments/assets/084165e9-6b68-4234-96e9-8d70c3b456ed)
И действительно, в `opt/etc/ndm/ifstatechanged.d/100-unblock-vpn`:
```
#!/bin/sh

. /opt/apps/kvas/bin/libs/ndm_d

if [ "${1}" = "hook" ] && [ "${change}" = "link" ] ; then

#	 Действия для подключений PPTP|L2TP, которое подключено к провайдеру
	 if [[ ${id} =~ 'PPTP|L2TP' ]] && is_cli_iface_global "${id}"; then
		#	В случае отключения PPTP|L2TP соединения через основной интерфейс
		#	проще говоря, в случае если подключение к интернету осуществляется
		#	через PPTP|L2TP соединение и оно прервалось	- ставим флаг, в виде создания файла
		case "${connected}-${link}-${up}" in
			"no-down-down" )
				touch "${tmp_file}"
			;;
			"yes-up-up" )
				[ -f "${tmp_file}" ] && {
					# После отключения PPTP|L2TP (которое используется для подключения к провайдеру)
					# и при наличии файла tmp_file - переустанавливаем ipset правила для восстановления
					cmd_vpn_iptable_reset &> /dev/null
					logger -t "КВАС"  "Соединение ${id} успешно подключено, правила восстановлены!"
					rm -f "${tmp_file}"
				}
			;;
		esac
	fi
```
`tmp_file` не определена. Я правильно понимаю, что пропущена строка:
```
		#	через PPTP|L2TP соединение и оно прервалось	- ставим флаг, в виде создания файла
		tmp_file=/opt/tmp/sub_connection
		case "${connected}-${link}-${up}" in
```

**Comment by AltGrF13** [comment]
![image](https://github.com/user-attachments/assets/700cebb0-d470-4e60-8f3c-f7ffa0fc4a3a)
Ума не приложу почему, но текст ВДОБАВЛЕНА. На функциональность не влияет, просто не понятное

**Comment by qzeleza** [comment]
Доброго дня

Благодарю Вас за внимательное отношение к деталям. 
В первом случае, этот тип "захвата" уже устарел, но все равно я его подправил.
Во втором случае - подправил, спасибо.

В следующей бете выйдет исправление.
