### ISSUE TITLE
adguard.com через vpn

### ISSUE THREAD

**Issue by egorlepa** [qzeleza/kvas#188]
adguard.com работает через vpn, хотя я не настраивал его обход, в ipset его адресов нет, в  ip route show table all его адресов нет, в маршрутах в UI роутера адресов нет. я схожу с ума? почему он идет через vpn?

**Comment by qzeleza** [comment]
Почему Вы игнорируете простые правила создания обращений?
Как из вашего сообщения можно понять о какой версии идет речь, о какой связке идет речь, какие домены у Вас прописаны!
На такие обращения - ответ только один, это закрытие без анализа.

**Comment by egorlepa** [comment]
Да ладно, я думал, что ответ Вам уже известен, скорее всего это из за возможности установки adguard home и обход сделан как то "мимо кассы" по умолчанию.
