### ISSUE TITLE
1.1.9-beta_6: wildcard у хостов при импорте или добавлении теряется

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#189]
В `bin/libs/vpn` (при правке на роутере `/opt/apps/kvas/bin/libs/vpn`) в `cmd_add_one_host`
вместо
```
	wild="${3:}"	 
```
надо
```
	wild="${3:-}"
```

**Comment by qzeleza** [comment]
Исправил, в следующей бете выйдет.
