### ISSUE TITLE
Бэта 20 строки с ошибками при запуске команд кваса

### ISSUE THREAD

**Issue by KirillShchetinnikov** [qzeleza/kvas#19]
После удаления 19 бэты и установки 20, в изначальной настройке изменил настройки shadowsocks подключения на другой сервер, и теперь при выполнении каждой команды кваса появляются строки:
ip: can't find device 'shadowsocks'
ip: can't find device 'shadowsocks'

Поkysq лог переустановки в приложенном файле. И так же прикладываю debug. 

Даже при запуске дебага они появляются:
/opt/packages # kvas debug > debug.txt
ip: can't find device 'shadowsocks'
ip: can't find device 'shadowsocks'
/opt/packages #
 

[remove-install.txt](https://github.com/qzeleza/kvas/files/9973278/remove-install.txt)

[debug.txt](https://github.com/qzeleza/kvas/files/9973303/debug.txt)

**Comment by qzeleza** [comment]
Какой вывод команды
`cat /opt/etc/sgadowsocks.json`

**Comment by KirillShchetinnikov** [comment]
~ # cat /opt/etc/shadowsocks.json
{
  "server": "ip",
  "server_port": 8388,
  "local_port": 1181,
  "password": "pass",
  "method": "chacha20-ietf-poly1305",
  "timeout": 86400,
  "local_address": "::",
  "dns_ipv6": false,
  "fast_open": false
}
~ #
 
 
 В выводе убрал значение ip сервера и пароль для него

**Comment by KirillShchetinnikov** [comment]
В логах роутера так же есть такие строчки
![IMG_20221110_080426](https://user-images.githubusercontent.com/98528966/201005333-e872fcb1-637a-43c6-8f09-8fcc99a71ec7.jpg)

**Comment by qzeleza** [comment]
Тогда `cat /opt/etc/ndm/netfilter.d/100-proxy-redirect` в студию)

**Comment by KirillShchetinnikov** [comment]
#!/bin/sh


#------------------------------------------------------------------------------
#
#	ПАКЕТ КВАС
#
#------------------------------------------------------------------------------
#
#	Данный файл служит для создания правил для пропуска Shadowsocks трафика (tcp)
#	при использовании любого shadowsocks подключения.
#	Они срабатывают при перезаписи правил в таблице netfilter
#	https://github.com/ndmsystems/packages/wiki/Opkg-Component
#
# ------------------------------------------------------------------------------
#	Разработчик: mail@zeleza.ru
#	Дата создания: 21/05/2022
#	Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------

# Shadowsocks+
if [ "${type}" = "iptables" ] ; then
	. /opt/apps/kvas/bin/libs/ndm
	case "${table}" in
		nat|mangle)
			if ! ip4save | grep "${table_name}" | grep -q 1181 ; then
				logger -t "КВАС"  "Запущен файл /opt/etc/ndm/netfilter.d/100-proxy-redirect"
			#	 создаем правила для shadowsocks подключения
				ip4_firewall_ssr_prune &> /dev/null
				ip4_firewall_set_ssr_rules br0 1181 &> /dev/null
			fi
			;;
		*)
			;;
	esac
fi

**Comment by KirillShchetinnikov** [comment]
[100-proxy-redirect.txt](https://github.com/qzeleza/kvas/files/9977543/100-proxy-redirect.txt)

**Comment by qzeleza** [comment]
Простите, у Вас будет возможность копию оформлять единым шрифтом или прилагать отдельным файлом?
Читать трудно и не ясна структура кода!

**Comment by KirillShchetinnikov** [comment]
> Простите, у Вас будет возможность копию оформлять единым шрифтом или прилагать отдельным файлом? Читать трудно и не ясна структура кода!

Простите с телефона отправляю, просто скопировал текст скрипта в комментарий, а уже гитхаб его сверстал таким. Приложил файл.

**Comment by qzeleza** [comment]
`cat /opt/apps/kvas/bin/libs/ndm | grep -E 'INFACE_[A-Z]{3}='`

**Comment by KirillShchetinnikov** [comment]
> `cat /opt/apps/kvas/bin/libs/ndm | grep -E 'INFACE_[A-Z]{3}='`

 ~ # cat /opt/apps/kvas/bin/libs/ndm | grep -E 'INFACE_[A-Z]{3}
'
INFACE_CLI=shadowsocks
INFACE_ENT=shadowsocks
~ #
~ #
~ #

**Comment by qzeleza** [comment]
> INFACE_CLI=shadowsocks
> INFACE_ENT=shadowsocks
Ясно, есть несколько вариантов развития событий. 

1. Вы самостоятельно изменили данный файл (в чем я сомневаюсь, но порой так бывает)
2. Данный файл каким то чудом остался после одной из бет, при проблеме с удалением предыдущей версии пакета. 
3. В процессе удалений и добавлений закралась ошибка в коде.

 В 1 и 2 случае, это проблема решается полным удалением пакет. Необходимо выполнить следующие команды, после его удаления:
`rm -rf /opt/apps/kvas /opt/etc/.kvas`

В третьем случае для того, чтобы я смог отловить ошибку в коде (если это действительно так), мне необходима Ваша карта действий (последовательность шагов), которая сможет привести меня к данной ошибке.

Для этого необходимо удалить полностью пакет и снова установить, записывая свои действия с начала установки пакете: в процессе установки выбрал это, затем это (в принципе можно просто скопировать текст с экрана установки пакета и поместить его в файл, чтобы разместить его здесь). 
Затем тоже самое сделать с процессом шагов, приводящим к этой ошибке.

**Comment by KirillShchetinnikov** [comment]
1 вариант неверный.
2 вариант возможен, но я форматировал флэшкарту перед установкой 19 бэты и после неё установил 20. Т.е. он мог остаться только после 19.
Последовательность действий по удалению 19 и установке 20 я прикреплял к своему первому сообщению при открытии тикета. Перед этим, на 19 бэте я менял настройки shadowsoks подключения и менял интерфейс через который работает квас на vpn и обратно на shadowsoks. Логов этих событий не сохранилось. Точную последовательность не помню, возможно попытаюсь повторить как будет возможность. 

Так как данная проблема появилась сразу после установки новой версии кваса(что видно в логе remove-install.txt), то предлагаю сразу в установщике проверять этот файл на наличие неверной записи, и если она неверная - исправлять ее, это будет легче, чем вылавливать проблему в коде, когда неясна точная последовательность.

**Comment by qzeleza** [comment]
> Так как данная проблема появилась сразу после установки новой версии кваса(что видно в логе remove-install.txt), то предлагаю сразу в установщике проверять этот файл на наличие неверной записи, и если она неверная - исправлять ее, это будет легче, чем вылавливать проблему в коде, когда неясна точная последовательность.

Так и происходит, данная переменная интерфейса **entware** устанавливается на стадии установки пакета и именно по этой причине я предположил, что были проблемы с удалением пакета. 

> Точную последовательность не помню, возможно попытаюсь повторить как будет возможность.

Да, было бы здорово, в противном случае, отловить данную проблему не представляется возможным на текущий момент.

**Comment by KirillShchetinnikov** [comment]
Не удалось повторить действия которые привели к ошибке. Решилось переустановкой пакета и удалением  каталога кваса. Думаю тикет можно закрыть, если проблема повторится, открою новый.

**Comment by qzeleza** [comment]
Добро
