### ISSUE TITLE
Обход блокировки discord

### ISSUE THREAD

**Issue by kovjogin** [qzeleza/kvas#191]
**Опишите проблему.**
При добавлении доменов в discord в список защищенных, не работают голосовые чаты.

**Какие шаги, привели к ошибке/проблеме?**
Опишите подробно шаги, которые привели к ошибке:

1. Нашел список доменов discord. 
2. Добавил их через команду kvas add
3. Приложение discord, чаты и т.п. грузится, но голосовые каналы не работают.

**Какие ожидания о поведении программы?**
Четкое и краткое описание того, что вы ожидали, что произойдет.
Ожидаю полноценную работу дискорд (можно без видео связи, но хотя бы голос)

**Приложите снимки экрана или сам текст с консоли.**
Если возможно и применимо, добавьте снимки экрана или сам текст с консоли (более предпочтительно), которые помогут объяснить вашу проблему.

![image](https://github.com/user-attachments/assets/866b1b61-07bd-4e1f-be8c-40a5a3a0f4c2)
![image](https://github.com/user-attachments/assets/d21ca3a8-97a6-4759-8bc4-bb99405aa002)
![image](https://github.com/user-attachments/assets/87b43989-eb37-4453-81b6-a67d4c954495)

**Заполните информацию о системе на роутере:**
Linux Keenetic_Giga 4.9-ndm-5 #0 SMP Wed Oct 2 17:01:16 2024 mips GNU/Linux
Google Chrome: Версия 130.0.6723.70 (Официальная сборка), (64 бит)
При подключении к роутеру просто вызвал exec sh

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.2.1
- Тип устройства: Giga (KN-1010) EAEU

**Внесите дополнительные пояснения.**
У меня есть клиент vpn, если его запускаю discord работает исправно, но мне не нравится идея гонять ВЕСЬ трафик через vpn. Поэтому хочу настроить, чтобы только нужные сайты работали через vpn. И до сегодняшнего дня все было прекрасно.

**Comment by kovjogin** [comment]
Информация о версии, если это поможет:
![image](https://github.com/user-attachments/assets/abfccaa7-c949-479d-a3c6-6bd44dbcc026)

**Comment by qellyka** [comment]
такая же проблема

**Comment by egorlepa** [comment]
да, приходится руками загружать в UI роутера актуальные маршруты отсюда:
https://github.com/RockBlack-VPN/ip-address/tree/main/Global/Discord
