### ISSUE TITLE
Не работает DNS/Маршрутизация

### ISSUE THREAD

**Issue by subbotaaa** [qzeleza/kvas#192]
**Опишите проблему.**
Опишите подробно обнаруженную ошибку/проблему без "воды", только суть.
Установил КВАС на свежий кинетик по инструкции, с отключением стнадратного DNS, после чего накатил КВАС. 

**Какие шаги, привели к ошибке/проблеме?**
Опишите подробно шаги, которые привели к ошибке:

1. Установил КВАС
2. Перехожу на https://ifconfig.me/ или https://2ip.ru/ - ошибка "Не удается получить доступ к сайту"
3. Ввожу команды:
kvas dns test yandex.ru
--------------------------------------------------------------------
Тестируем получение DNS сервер 127.0.0.1 **не доступен** на 9153 порту.

Включаю шифрование:
kvas crypt on
--------------------------------------------------------------------
Шифрование DNS                                           ПОДКЛЮЧЕНО
--------------------------------------------------------------------
/opt/tmp # kvas dns test yandex.ru
--------------------------------------------------------------------
Тестируем получение DNS сервер 127.0.0.1 **не доступен** на 9153 порту.

5. В работе Shadowsocks уверен. Прямое подключение через клиент работает. Пробовал ручной ввод и "через ссылку". 

**Какие ожидания о поведении программы?**
КВАС будет направлять трафик для доменов через Shadowsocks 

**Заполните информацию о системе на роутере:**
- Операционная система Windows 10
- Браузер и его версия Chrome Shadowsocks 
- SSH клиент Pytty

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic 
- Прошивка на роутере: 4.2.1
- Тип устройства Viva

**Внесите дополнительные пояснения.**
kvas test
--------------------------------------------------------------------
Состояние службы dnsmasq                                   ЗАПУЩЕНА
Отслеживание порта #53 сервисом dnsmasq                      СЛЕДИМ
--------------------------------------------------------------------
Состояние службы dnscrypt-proxy2                           ЗАПУЩЕНА
Отслеживание порта #9153 dnscrypt-proxy2                     СЛЕДИМ
--------------------------------------------------------------------
Состояние службы shadowsocks                               ЗАПУЩЕНА
Отслеживание порта #1181 shadowsocks                         СЛЕДИМ
--------------------------------------------------------------------
Наличие правил защиты в iptable                                ЕСТЬ
Заполнение ipset таблицы скриптами КВАСа                  ЗАПОЛНЕНА
--------------------------------------------------------------------
Проверка наличия ip адресов хостов в таблице ipset
Все записи в таблице unblock прошли проверку.

**Comment by qzeleza** [comment]
О какой версии Кваса идет речь?

**Comment by subbotaaa** [comment]
> О какой версии Кваса идет речь?

Версия пакета 1.1.9 beta_3
Но заметил что при выключенном crypt маршрутизация кваса всеравно работает, но при этом dns test выводит ошибки и в консоли самого кинетика все сайты добавляются как бы с локальным IP. 
Получается в моем случае на работоспособность это не влияет, но в идеале хотелось бы понять как это поправить или убедиться что так и должно быть

**Comment by AltGrF13** [comment]
кто испытывает трудности с версиями пакета 1.1.9, до тех пор пока не выйдет стабильная версия - использовать версию пакета 1.1.8r2
Установить пакет можно командами ниже:

mkdir /opt/packages/ && cd /opt/packages  
curl -sOfL https://github.com/qzeleza/kvas/releases/download/v1.1.8/kvas_1.1.8-release_2_all.ipk 
opkg install /opt/packages/kvas_1.1.8-release_2_all.ipk

**Comment by qzeleza** [comment]
Старые бета версии не поддерживаю.
