### ISSUE TITLE
Не работает дискорд

### ISSUE THREAD

**Issue by qellyka** [qzeleza/kvas#196]
Недавно человек создал тикет, где спрашивал как починить дискорд, ему ответили что нужно в UI роутера добавлять маршруты из данного списка (https://github.com/RockBlack-VPN/ip-address/tree/main/Global/Discord), у меня вопрос если я в KVAS использую shadowsocks, то что делать?(AWG и WG почему то отваливаются именно в роутере).

**Comment by AltGrF13** [comment]
У ss-redir проблема с поддержанием WebRTC, голоса не будет. Проблема именно в пакете Кинетика, а не КВАСе.

Все остальные функции работать будут.

**Comment by qellyka** [comment]
Понял, спасибо

**Comment by qellyka** [comment]
А если через AWG, то будет работать да?
