### ISSUE TITLE
Вопрос по бинарникам dnsmasq входящим в поствку

### ISSUE THREAD

**Issue by pavelk-bluesnap** [qzeleza/kvas#197]
**Опишите проблему.**
Проблемы нет. Интересует подробности, как были получены бинарники лежащие в opt/apps/kvas/sbin/dnsmasq. Есть ли инструкция по их сборке? Есть ли возможность сделать reproduceable build для проведения аудита?

Заранее спасибо!

**Comment by AltGrF13** [comment]
Это Dnsmasq с [этим патчем](https://github.com/lixingcong/dnsmasq-regex)
Сборка его обсуждалась много где, в том числе на [форуме](https://forum.keenetic.com/topic/13435-dnsmasq-%D1%81-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%BE%D0%B9-regexp/)
