### ISSUE TITLE
1.1.9 beta_3 Защищенный список самопроизвольно очищается

### ISSUE THREAD

**Issue by notabene00** [qzeleza/kvas#198]
**Опишите проблему.**
Опишите подробно обнаруженную ошибку/проблему без "воды", только суть.
В чем именно она проявляется?

"Защищенный список" становится пуст при неясных обстоятельствах.

**Какие шаги, привели к ошибке/проблеме?**
Опишите подробно шаги, которые привели к ошибке:

**kvas 1.1.9 beta_3**

Добавляю youtube `kvas add youtube.com`, соглашаюсь на добавление с поддоменами.
Использую `kvas show` для просмотра списка, `*youtube.com` там есть.
Добавляю так же `pornhub.com`, соглашаюсь на поддомены - вижу `*pornhub.com` в выводе `kvas show`.
Точно так же добавляю `kvas add youtu.be`, точно так же соглашаюсь на добавление с поддоменами... и вот уже `kvas show` показывает "список содержит 1 записей: *youtu.be".

**Какие ожидания о поведении программы?**
Список будет пополняться и пополняться, а не самопроизвольно очищаться при добавлении очередного хоста.

**Приложите снимки экрана или сам текст с консоли.**
<img width="958" alt="Screenshot 2024-11-01 at 08 42 55" src="https://github.com/user-attachments/assets/29686600-e75a-47d9-bfe2-8b6d250c542d">

**Заполните информацию о системе на роутере (компьютере?):**
- Операционная система (ее кодовое название) и версия: [например, Ubuntu 22.01]
macOS 15.1
- Браузер и его версия [например, chrome 36, safari 16.1]
n/a
- SSH клиент и его версия [например, iTerm, 1.0]
OpenSSH_9.8p1, LibreSSL 3.3.6

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: [например, Keenetic]
KeeneticOS 
- Прошивка на роутере: [например, 3.8.4]
4.2.1
- Тип устройства [например, Ultra KN-1810]
Giga (KN-1010) EAEU

**Внесите дополнительные пояснения.**
Добавьте сюда любые пояснения, которые по Вашему мнению касаются обнаруженной ошибки/проблемы.
Примерно тоже самое после `kvas import somefile.lst`, только список вообще пустым может стать.
Хотя, вроде бы, рапортует что всё успешно
<img width="962" alt="Screenshot 2024-11-01 at 08 57 57" src="https://github.com/user-attachments/assets/c09f48e6-8cbf-48a2-9e2e-2c377f73d9d8">

**Comment by notabene00** [comment]
Это не связано напрямую с командой 'add'. 
Какая-то фоновая периодическая задача чистит список, что ли. Спустя некоторое время ввел снова 'kvas show', теперь список пуст.

**Comment by qzeleza** [comment]
не обсуждаю и НЕ поддерживаю старые беты. Текущая бета №6
