### ISSUE TITLE
Мелочь, но все-таки)

### ISSUE THREAD

**Issue by drfischer2** [qzeleza/kvas#20]
В 20 бете при вызове справки пункт:

kvas rm google      - удаляем все хосты из списочного файла.

а, должно быть, думаю:

kvas rm google      - удаляем все хосты с упоминанием "google" из списочного файла.

**Comment by qzeleza** [comment]
Да, спасибо, подправлю.

**Comment by qzeleza** [comment]
В 21 бете - исправлено.
