### ISSUE TITLE
Для старых роутеров/прошивок не хватает информации в инструкции

### ISSUE THREAD

**Issue by slavkostrov** [qzeleza/kvas#202]
<img width="901" alt="image" src="https://github.com/user-attachments/assets/ae091ff1-bdcb-4ecf-9ac0-abb6a5124c78">

Предлагается дополнить этот пункт тем, что если указаных компонент нет, то сначала нужно установить "Протокол IPv6", после этого появятся netfilter компоненты.

Собственно столкнулся с такой проблемой на keenetic ii и 2.16.D.12.0-11

**Comment by qzeleza** [comment]
Добавил, благодарю Вас.
