### ISSUE TITLE
1.1.9-beta_6: триггерные файлы

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#206]
Т.к. идут частые сработки, решил посмотреть основные.

Первое, в `/opt/etc/cron.5mins/check_vpn` вызов `reset_vpn_connection`, а функция `restart_vpn_connection`

**Comment by AltGrF13** [comment]
Второе, в `netfilter.d`/`100-vpn-mark` разделил `ip4_mark_vpn_network` обратно на 2 подфункции, сработку второй сделал и на таблицу nat. Ибо роутинг DNS-запросов в ней, надо реагировать и на её изменение (но только второй подфункцией).
```
# IPv4
if [ "${type}" = 'iptables' ] ; then
	. /opt/apps/kvas/bin/libs/ndm

	# использует только команды ipset
	ip4set_create_table &> /dev/null

	# обе функции используют только mangle
	# кроме маркировки включают обход br0
	if [ "${table}" = 'mangle' ] ; then
		if fastnet_enabled ; then
			ip4_firewall_vpn_mark &>/dev/null
		else
			ip4_firewall_mark_rules_tcp_udp_on &>/dev/null
		fi
	fi

	# роутинг DNS гостевых и обход без ускорения используют nat
	# обход с ускорением использует mangle
	if [ "${table}" = 'mangle' ] || [ "${table}" = 'nat' ] ; then
		set_guest_nets_rules &>/dev/null
	fi
fi
```

**Comment by AltGrF13** [comment]
Четвёртое, проблема логики в триггерах `fs.d`

Вот рассмотрим `netfilter.d`.
1. `100-dns-local`: правила редиректа DNS в br0 (ничего не требуют и ни от чего не зависят)
2. `100-vpn-mark`: создаём kvas_ipset (этого тут быть не должно, но может уменьшить количество ошибок на старте), маркируем VPN и включаем обход br0 с использованием этой таблицы, включаем обход с использованием kvas_ipset и маркировки.

Всё логично, зависимые друг от друга команды последовательно друг за другом в одном файле.

А что в `fs.d`?
1. `100-ipset`: создаём kvas_ipset (то, где он и должен быть)
2. `100-vpn`: создаём таблицу маршрутизации, меняем приоритет; маркируем VPN и включаем обход br0 с использованием kvas_ipset, включаем обход с использованием kvas_ipset и редиректы DNS гостевых.

Странно создавать kvas_ipset в одном файле, а использовать в другом (хотя в `100-vpn-mark` делаем в одном).
Странно, что VPN правила создаём в автозагрузке `fs.d`, а не дожидаемся сработки триггеров в `netfilter.d`. Если причина в том, что триггерное создание не надёжно, то почему не добавлены и правила редиректа DNS из `100-dns-local`? Почему не добавлен SS, он нормально работает? В общем, зачистил в `fs.d`/`100-vpn` попытку применения сетевых правил VPN, они и очень часто предпринимают попытки и без этого, и сеть может быть банально не готова ещё на этом этапе.
```
if [ "$1" = 'start' ] ; then
	. /opt/apps/kvas/bin/libs/ndm

	# Создаем талицу IP адресов для  VPN подключения отличного от shadowsocks
	ip4_add_route_table &> /dev/null
	# Устанавливаем приоритет таблицы
	ip4_rule_set_priority &> /dev/null
fi
```

**Comment by qzeleza** [comment]
Исправления внес в 7 бету, благодарю.
