### ISSUE TITLE
1.1.9-beta_6: Межсетевой экран

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#207]
Сейчас в установке присутствуют
```
	# Закрываем снаружи DNS порты для всех вншних сетей
	deny_wirewall_port "53" "tcp" "Квас: закрываем снаружи 53/TCP DNS порт"
	deny_wirewall_port "53" "udp" "Квас: закрываем снаружи 53/UDP DNS порт"
	allow_wirewall_local_net_to_port "53" "tcp" "Квас: разрешаем локальной сети обращения в 53/TCP DNS порт"
	allow_wirewall_local_net_to_port "53" "udp" "Квас: разрешаем локальной сети обращения в 53/UDP DNS порт"
	# Устанавливаем вышесозданные правила на первое место в списке правил
	set_wirewall_order_for_rule "53" "tcp" "deny" "0"
	set_wirewall_order_for_rule "53" "udp" "deny" "0"
	set_wirewall_order_for_rule "53" "udp" "permit" "0"
	set_wirewall_order_for_rule "53" "udp" "permit" "0"
```

Почему было необходимо защищаться фаерволом на условной beta3?
1. Оба DNS-сервера отвечали всем IP. Это исправлено в beta6, не актуально.
2. Была прокидка 53 порта со внешних сетевых интерфейсов в роутер. Фикс уже вошёл в beta7, не актуально.
3. К тому же, на 53 порту был требовательный к внимательной настройке Dnsmasq. Сейчас на нём встроенный DNS-прокси KeenOS. Мы действительно думаем, что у Кинетика не получилось его обезопасить, что им надо прям помогать?
4. Если мы закрываем 53 для внешних подключений, то мы должны для каждой сети при добавлении `kvas vpn net add` обратно разрешать 53 диапазону этой сети. Сдвигая все правила ниже. Вот, например, как выглядит ручное разрешение IKEv2 (они ведь приходят извне):
![image](https://github.com/user-attachments/assets/8aca9a2e-39b7-4aa8-bfdf-9e5935afb723)
  Текущая добавка 4 правил при установке просто не дала бы этому подключению работать (пока бы я руками не добавил 2 правила со скрина). А если я не хочу на IKEv2 включать обход, то КВАС же всё равно должен починить, что сломал?
5. А как определить, не стоят ли у человека правила защиты уже? Да, проверяющий код там сейчас есть; но он проверяет конкретный порт. А если я поставил правило (как при настройке серверов) запретить весь диапазон 0–65535 с обратным разрешением только нужных мне портов? А если другой диапазон, который этот 53й уже включает?

В общем, вопросов больше, чем ответов. Текущая не большая реализация ломает подключения к гостевым VPN-серверам на роутере, а нормальная поддержка всех вариантов случаев в межсетевом экране выльется в огромные такие куски кода. И, главное, смысл он уже утратил. Это был временный костыль до закрытия/фиксов.

Что и предлагаю проверить в рамках beta7. Временно это закомментировать, попросить желающих опустить ручные щиты и последить за нагрузкой (на 80% уверен, что проблема ушла). Заодно натравлю на роутер сканеры безопасности.

**Comment by qzeleza** [comment]
В бете 7 закомментировал.
 Спасибо.
