### ISSUE TITLE
Оптимизация старта списка

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#208]
Попробуем добавить в список "защиты" любую запись. После этого в логе множественные
![image](https://github.com/user-attachments/assets/b6bb8edc-fb26-4898-9535-5e05e92a155b)
И по `ipset list kvas_ipset | wc -l` видим, что ipset "прогрет" на 145 записей (при 39 доменах в списке). С IP основных доменов из списка "защиты" (без поддоменов). Но зачем это делать, если вся "защита" уже умеет собираться на лету? Раз сабдомены работают в таком режиме, почему и с основными не поступить также? Со старта ipset должен содержать лишь записи с IP, которые есть у меня в "защите" (только они не могут загрузиться на лету). Аналогичная картина и если перезапускаем роутер, куча kdig'ов и для без того загруженного процессора.

В файле `bin/main/ipset` комментируем строчку `add_host_by_iplist_to_ipset "${host}" || true`. После перезапуска в `ipset list kvas_ipset | wc -l` почти нет записей. Заходим на myip2.ru, "защита" работает, в `ipset list kvas_ipset | wc -l` стало на 1 больше. Заходим в Страву или куда ещё — записи множатся на десятки. Всё работает, при этом при каждом перезапуске не нужно молотить огромные списки.

**Comment by AltGrF13** [comment]
Имеется ещё проблема. IP в указанном выше файле добавляются `ipset -exist add "${IPSET_TABLE_NAME}" "${host}" &>/dev/null || true`. Но в этом случае они истекут по таймауту, и больше отрабатывать не будут. В отличии от попадающих по домену, они себя автоматически восстановить не могут. Их надо изначально добавлять с timeout 0. Итого указанный блок кода будет
```
	# если строка IP, диапазон или маска; то добавляем напрямую и без ttl
	if echo "${host}" | grep -qoE "${IP_FILTER}|${IP_FILTER}-${IP_FILTER}|${IP_FILTER}/[0-9]{1,2}"; then
		ipset -exist add "${IPSET_TABLE_NAME}" "${host}" timeout 0 &>/dev/null || true
	fi
```

**Comment by qzeleza** [comment]
Благодарю Вас, только, в очередной раз, напомню Вам, что Квас не обходит, а защищает необходимое Вам доменные имена внутри Ваших соединений.

**Comment by AltGrF13** [comment]
Везде в задаче изменил формулировки на корректные

**Comment by AltGrF13** [comment]
Захожу в файл `bin/main/ipset` и там
![image](https://github.com/user-attachments/assets/82c97542-14e7-4f89-8be2-4692f47712de)
Должно быть как-то так
```
while read -r line || [ -n "${line}" ]; do

	#  пропускаем строки c минусами - это рекламные сайты
	#  пропускаем пустые строки и строки с комментариями
	#  пропускаем строки с комментариями
	[ "${line::1}" = "-" ] || [ -z "${line}" ] || [ "${line:0:1}" = "#" ] && continue

	# удаляем из строки комментарии - все что встречается после символа # и сам символ
	# удаляем *
	host=$(echo "${line}" | sed 's/#.*$//g' | tr -s ' ' | sed 's/\*//')

	# если строка начинается с IP, то проводим обработку по IP
	if echo "${host}" | grep -qoE "${IP_FILTER}|${IP_FILTER}-${IP_FILTER}|${IP_FILTER}/[0-9]{1,2}"; then
		ipset -exist add "${IPSET_TABLE_NAME}" "${host}" timeout 0 &>/dev/null || true
	fi

done < "${HOST_LIST}"
```
