### ISSUE TITLE
Некоторые хосты, отсутствующие в списке разблокировки, открываются через VPN

### ISSUE THREAD

**Issue by impaxel** [qzeleza/kvas#21]
**Мой девайс:** Keenetic Hopper (KN-3810)
**Версия КВАСа:** КВАС 1.0 beta 20

После обновления с 18 беты на 20 заметил, что контент и видео на Reddit (reddit.com) стали грузиться не так шустро как раньше, но особо не придал этому значение. Однако еще позднее заметил, что реклама на сайте и посты в блоке near you отсылают меня в Амстердам (где и находится мой VPN узел). А сегодня, войдя в свою учетную запись на Faceit (faceit.com), я вдруг получил письмо, что я залогинился с нового IP адреса и в новой локации - Netherlands.

Очевидно, что ни Reddit, ни Faceit, я не добавлял в список разблокировки, ведь они и так прекрасно работают.
Ниже прикладываю свой лист:

<pre>
~ # kvas ls
-----------------------------------------------------------------------------------
Список разблокировки содержит 28 записей:
-----------------------------------------------------------------------------------
*ads-twitter.com
*cdnfacebook.com
*cdninstagram.com
*f.vision
*facebook.com
*fb.com
*fbcdn.com
*fbcdn.net
*fburl.com
*ig.me
*instagram.com
*licdn.com
*linkedin.com
*lnkd.in
*meduza.io
*meta.com
*quora.com
*rutracker.org
*spotify.com
*t.co
*twimg.com
*twitter.co
*twitter.com
*twitteroauth.com
*twttr.com
*whatsapp.net
2ip.ru
yt3.ggpht.com
-----------------------------------------------------------------------------------
</pre>

**Comment by impaxel** [comment]
Не заметил, что уже 21 бета есть. Сейчас обновился на 21, проблема сохраняется.

**Comment by impaxel** [comment]
Кажется, я понял вероятную причину такого поведения. Скорее всего все дело в домене **\*t.co**, который содержится в листе, из-за чего все сайты, в адресе которых встречается **t.co** начинают открываться через VPN (reddi**t.co**m, facei**t.co**m). Попробовал его убрать и заменить на t.co без звездочки - проблема решилась.

**Comment by qzeleza** [comment]
Хорошо, внесу в релиз **t.co** без *****
