### ISSUE TITLE
Dnsmasq настройки

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#211]
Соберу в вопросе несколько нюансов отдельными комментариями. 

### А. Прослушивание правильных адресов

1. Без `bind-interfaces` он действительно слушает всё, никакие дополнительные `listen-address` и `interface` не помогают
![image](https://github.com/user-attachments/assets/b9277849-f370-428f-832b-1099615188f4)

2. Если вместе с включением `bind-interfaces` не указать ни `listen-address`, ни `interface`; то Dnsmasq обойдёт все сетевые интерфейсы и добавит все IP шлюзов с них.
_скриншот2 надо чистить_

3. Если добавить `interface=br0`, то увидим 4 адреса
![image](https://github.com/user-attachments/assets/3c01ee00-02b1-458c-a093-945815e5db1b)
Два из них от br0, два от lo (в документации указано, что он добавляет его автоматически).
![image](https://github.com/user-attachments/assets/6673a694-b9f5-492e-86ef-0b464b1abbb1)

4. Вот картина для
```
bind-interfaces
interface=br0
except-interface=lo
```
![image](https://github.com/user-attachments/assets/f8ab29ee-e9e6-4a33-8272-994dd2ccb43e)

5. Указание `listen-address` просто добавляют в прослушку дополнительные адреса.
_скриншота тут, думаю, не требуется_

**Выводы**. Я ожидал, что указание обоих параметров (`listen-address` и `interface`) будет работать как AND условие. Оно же работает как OR. Это важно для сбора правильного конфига.

Идеальным вариантом видится указание только `listen-address`
![image](https://github.com/user-attachments/assets/b6438f1d-37a4-4075-aea5-2a4ea8dcdae1)
Т.е. удалить `interface=br0` в текущем конфиге, это уберёт прослушку IPv6 у br0 и loopback (а IPv4 для них мы добавили уже руками через `listen-address`). Т.к. DNS трафик для IPv6 мы всё равно не прероутим, в IPv6 в Dnsmasq у br0 и loopback всё равно ничего не придёт.

**Мысль на будущее**. Как уже писал, IPv6 уже сейчас выглядит полностью не отключаемым (если у меня отключены пакет в роутере и настройка в сетевом подключении Винды, я всё равно получу и IPv6 адрес). Если добавить правила прероутинга IPv6 для DNS в `ip4_firewall_dns_rules_set`, `ip4_add_to_dns_routing` и `ip4_delete_from_dns_routing`; и настроить в DNSMasq отдачу только IPv4 адресов, то это решит вопрос хотя бы частично (до полной поддержки, в которой потребуются отдельные ipset и правила роутинга). Ибо на многих устройствах (типа планшетов) использование IPv6 из DNS отключить проблематично (нет галочки, как в Винде). Дык вот, в этом случае (после реализации таких правил) проще будет отказаться от использования `listen-address=` в `/opt/etc/dnsmasq.conf` и перейти только на `interface=`. Потому что добавление одного интерфейса идентично добавлению двух listen-address (IPv4 и IPv6), это проще. Плюс, напоминаю, lo (127.0.0.1 и его IPv6 ипостась) будет добавляться автоматически.

**Comment by AltGrF13** [comment]
### Б. DNSSec
Сейчас в конфиге добавился `proxy-dnssec`. Т.е. мы доверяем вышестоящим серверам проверку DNSSEC, и передаём её пользователям. Но в мане Dnsmasq сказано
> Note that caching the Authenticated Data bit correctly in all cases is not technically possible. If the AD bit is to be relied upon when using this option, then the cache should be disabled using --cache-size=0.

Для нашего случая `cache-size=0` делать нельзя, а без него `proxy-dnssec` не надёжен.

У Dnsmasq есть возможность, чтобы он сам тестировал DNS ответы; и тогда он кеширует DNSSEC data корректно. По умолчанию её мануал и рекомендует, но с ней завести Dnsmasq из Entware у меня не получилось.
> Dnsmasq must be compiled with HAVE_DNSSEC enabled, and DNSSEC trust anchors provided, see --trust-anchor. Because the DNSSEC validation process uses the cache, it is not permitted to reduce the cache size below the default when DNSSEC is enabled. The nameservers upstream of dnsmasq must be DNSSEC-capable, ie capable of returning DNSSEC records with data. If they are not, then dnsmasq will not be able to determine the trusted status of answers and this means that DNS service will be entirely broken.

**Итого**. Предлагаю убрать, пусть пользовательские устройства проверяют DNSSEC сами.

**Comment by AltGrF13** [comment]
### В. IPv6 в DNS
Предлагаю добавить в конфиг
```
filter-AAAA # убирает IPv6 в ответе от DNS
```
Если ничего не путаю, это освободит пользователя от необходимости выключать IPv6 в подключениях Винды (но не на роутере)

**Comment by AltGrF13** [comment]
### Г. ECH в DNS
Предлагаю добавить в конфиг (да, закомментированным)
```
#filter-rr=HTTPS # уберёт HTTPS RR, из-за этого отключится ECH
```
Владельцы сайтов, которым важны пользователи из РФ, сейчас [отключают ECH](https://habr.com/en/news/856344/).

Пользователи Firefox, например, могут отключить поддержку со своей стороны.

Некоторые отключают на своих DNS (на роутере). Но это очень спорный вопрос. С одной стороны, соблюдёшь требования и перестанешь блокироваться. С другой стороны, начнёшь отправлять первый пакет не шифрованно (в том числе и для списка защиты). Каждый решает сам; но подсказать пользователям о такой настройке можно такой опцией. Она не является каким-то нарушением; скорее, наоборот, соблюдением закона (и уменьшением приватности).

**Comment by qzeleza** [comment]
Итоги какие?
