### ISSUE TITLE
Перехват DNS не работает в отдельных случаях

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#213]
Пока нет решения. Оставлю подумать себе.
_По сути варианты стали всплывать от тех, у кого обход работал лишь частично. Поддомены динамически не добавлялись, но т.к. основные домены прогревались при рестарте, то выглядело рабочим. Жили в режиме «работает, если периодически дёргать kvas test»._

В обоих случаях правила перехвата висели верно (у одного роутер только был 192.168.2.1)
```
iptables -A PREROUTING -w -t nat -i br0 -p tcp --dport 53 -j DNAT --to-destination 192.168.1.1:9753
iptables -A PREROUTING -w -t nat -i br0 -p udp --dport 53 -j DNAT --to-destination 192.168.1.1:9753
```

DNS и браузеры были настроены верно (добавление в ipset руками чинило ситуацию). Dnsmasq на правильном порту, с рабочими выходом и kvas.dnsmasq. У обоих в итоге можно было завести через шаманство настроек (в одном случае случай идентичен моему, когда с правильными не войти в интернет, но после входа их можно изменить, и всё работает). Но это всё не важно, ведь основной вопрос — почему правила перехвата выше не работали. Они бы избавили от необходимости колдовать с настройками.

Вроде как общее правило у одного начинало работать
```
iptables -A OUTPUT -w -t nat -p tcp --dport 53 -j DNAT --to 192.168.2.1:9753
iptables -A OUTPUT -w -t nat -p udp --dport 53 -j DNAT --to 192.168.2.1:9753
```
Но это опять даст дыру в безопасности (доступ извне).

Также можно попробовать словить на другом интерфейсе или исходящий.

**Comment by AltGrF13** [comment]
Случай 1
![image](https://github.com/user-attachments/assets/80102ebc-448d-4f67-a474-3bc21b7cc35e)
![image](https://github.com/user-attachments/assets/927bd23a-af52-410c-a07f-443e46411c89)

**Comment by AltGrF13** [comment]
Случай 2
![image_2024-11-12_23-39-12](https://github.com/user-attachments/assets/cc14d100-92c2-4dbc-badb-fcbae701ad66)
![image_2024-11-12_23-17-53](https://github.com/user-attachments/assets/130e310e-5715-468a-8dae-f6d3f8dd7a4e)

**Comment by qzeleza** [comment]
самый гибкий (если он рабочий вариант) , с моей точки зрения это:
```
iptables -A PREROUTING -w -t nat -s 192.168.1.0/24 -p tcp --dport 53 -j DNAT --to-destination 192.168.1.1:9753
iptables -A PREROUTING -w -t nat -s 192.168.1.0/24 -p udp --dport 53 -j DNAT --to-destination 192.168.1.1:9753
```

Нет нужды в отлавливании новация интерфейса.

**Comment by AltGrF13** [comment]
Надо просто добраться до хоть одного устройства, у которого воспроизводится проблема. Когда поставленная из коробки бета не перехватывает DNS. Ну и проверить всю пачку вариантов. Возможно, это на какой-то из архитектур так аппаратный сетевой ускоритель отрабатывает, прокидывая мимо софтовой обработки iptables эти запросы. И с какой-то из видов записей будет работать хорошо. У нескольких человек я спросил, на днях попробую.

Пункт В я вечером проверю у себя, но это чисто ради #41. Хотя он может тоже помочь на тех случаях, что у меня не воспроизводятся.

Если не поможет в итоге ничего из этого, то останется лишь вариант возврата на 53 порт. Но это пока забегание вперёд, сначала нужно проверить.

**Comment by AltGrF13** [comment]
Сегодня удалось поковырять один из девайсов с нерабочим перехватом DNS. Он из [нового поколения с изменённым процом](https://blog.keenetic.ru/special-editions-kn-3x1x/), так что нюансы аппаратного ускорения явно изменились.

Никакой реакции на сочетание `PREROUTING -t nat --dport 53 -j DNAT`.
Оутпуты дают странный эффект: они начинают ловить примерно 1 пакет из 3ёх. При этом на домашнем, опять же, работают стабильно. Пробовалось что-то типа
```
ipset create localprivate hash:net -exist
ipset add localprivate 127.0.0.0/8
ipset add localprivate 10.0.0.0/8
ipset add localprivate 100.64.0.0/10
ipset add localprivate 172.16.0.0/12
ipset add localprivate 192.168.0.0/16

iptables -A OUTPUT -w -t nat -p tcp -m set ! --match-set localprivate dst --dport 53 -j DNAT --to-destination 127.0.0.1:9753
iptables -A OUTPUT -w -t nat -p udp -m set ! --match-set localprivate dst --dport 53 -j DNAT --to-destination 127.0.0.1:9753
```

Только позже дошло, что при простом редиректе можно переписать и на SNATы наоборот (смысл не поменяется)
```
iptables -A PREROUTING -w -t nat -s 192.168.1.0/24 -p tcp --dport 53 -j SNAT --to-source 127.0.0.1:9753
iptables -A PREROUTING -w -t nat -s 192.168.1.0/24 -p udp --dport 53 -j SNAT --to-source 127.0.0.1:9753
```

У некоторых видел домаркировку для Кинетика, возможно это как раз позволит пройти аппаратку
```
iptables -A PREROUTING -w -t nat -s 192.168.1.0/24 -p tcp --dport 53 -m ndmmark --ndmmark 0x4/0x0 -j SNAT --to-source 127.0.0.1:9753
iptables -A PREROUTING -w -t nat -s 192.168.1.0/24 -p udp --dport 53 -m ndmmark --ndmmark 0x4/0x0 -j SNAT --to-source 127.0.0.1:9753
```

Также вместо `PREROUTING` можно попытаться закосить под системные цепочки `_NDM_STATIC_SNAT`. Как проверить их формат/создание тоже разобрался. В общем, жду ещё одной проверки.

**Comment by AltGrF13** [comment]
Немного на тему #195 ещё. Вот в этом вопросе я рассказывал, что какие бы настройки не указывал в админке в разделе `/internet-filter/dns-configuration`, у меня ndnproxy никогда не отправлял запросы в `192.168.1.1:9753`. У некоторых же проставление настроек там и немного шаманства — и Keenetic в Dnsmasq запросы начинал передавать даже без iptables перехватов. Поэтому и пошёл в сторону перехватов iptables, потому что путём настроек стабильности добиться не удавалось (здесь с новыми роутерами тоже оказалась засада, но сообщение не об этом).

Сейчас подёргал в API `show dns-proxy`. Там в большом строковом параметре есть кусок с dns_server. Дык вот, для такого
![image](https://github.com/user-attachments/assets/3a283d15-1704-451e-98aa-e4568a336edc)
там
```
dns_server = 192.168.112.1 .
dns_server = 8.8.8.8 .
dns_server = 8.8.4.4 .
dns_server = 77.88.8.1 .
dns_server = 1.0.0.1 .
```

Если добавим
![image](https://github.com/user-attachments/assets/a01a3810-352a-4494-bc13-eb7cc9e3637d)
становится
```
dns_server = 192.168.112.1 .
dns_server = 8.8.8.8 .
dns_server = 8.8.4.4 .
dns_server = 192.168.1.1:9753 .
dns_server = 77.88.8.1 .
dns_server = 1.0.0.1 .
```

У меня нигде в настройках нет этого самого 8.8.4.4. Opkg чистый. Если я сохраняю файл конфигурации роутера, то там тоже 8.8.4.4 нигде не упоминается. Нет ни на одной странице настроек! По `find / -name ndnproxy` находим `/tmp/ndnproxymain.conf`, в котором эта истинная очерёдность видна. Как только этим рулить — не понятно. Если зайти с этой стороны, то перехваты на iptables могут оказаться и не нужны. Если научиться подсовывать `192.168.1.1:9753` повыше.

Вызвал `no ip name-server 8.8.8.8`
```
			"status": "message",
			"code": "22544585",
			"ident": "Dns::Manager",
			"message": "name server 8.8.8.8, domain (default) deleted."
```
Аналогично с 8.8.4.4. Записи пропадают. И даже 192.168.112.1, который нельзя. Получаем:
```
dns_server = 192.168.1.1:9753 .
dns_server = 77.88.8.1 .
dns_server = 1.0.0.1 .
```

После этого на странице с интернет-провайдером пробую указать ещё раз порядок
![image](https://github.com/user-attachments/assets/51ef74ca-1322-4fb8-8074-4f5e5dc606c9)
И в конфиге опять
```
dns_server = 192.168.112.1 .
dns_server = 8.8.8.8 .
dns_server = 8.8.4.4 .
dns_server = 192.168.1.1:9753 .
dns_server = 77.88.8.1 .
dns_server = 1.0.0.1 .
```
Он обратно восстанавливает всё это. Т.е. я могу за счёт `no ip name-server` загнать `192.168.1.1:9753` в верх списка. Но малейшее изменение настроек или перезагрузка роутера — и он в приоритете опускается на 4 место. Так, собственно, он у меня и не отрабатывает. И люди произвольно настройки натыкивают, у них она начинает работать. А у кого-то никак (если мы говорим о перехвате через настройки, а не через iptables). Как минимум, становится понятно, у кого через настройки будет работать, а у кого — нет.

**Comment by qzeleza** [comment]
Полагаю, что это проблема и недочет в самой прошивке. 
У меня периодически перестает работать ip:5793, подмечал уже не раз. 

Для окончательной проверки надо бы попробовать в старой версии - до 4.1

**Comment by qzeleza** [comment]
На время, можно в крон поставить обновление dns_server = 192.168.1.1:9753, только вот период надо понять какой поставить.

Но это "костыль", конечно.

**Comment by AltGrF13** [comment]
>Но это "костыль", конечно

Кроме этого, боюсь, какие-то из тоннелей перестанут работать после `no ip name-server`. Ща походил, повырубал всё на роутере. Если выключить WireGuard, то он перестаёт докидывать Гугловые. 192.168.112.1 после отказа от рабочих L2TP/IPsec. 

ndnproxy глубоко зашит в прошивку, обслуживает все из видов туннелей. И, видимо, на лету собирает свой приоритет: сначала для туннелей; потом, что указано в настройках. И в дальнейшей работе, встретив общественный туннельный, DNS-трафик уходит туда. Забивая на истинные настройки в разделе «Профили DNS».

**Comment by AltGrF13** [comment]
Четвёртый способ с маркировкой одолеть не смог. Шестое из предположений завелось, но как и с аутпутом, работа была не стабильна.
> залетает живенько. Но не все. Тот же myip2.ru вообще ни в какую. Но многие открываются сразу.
> Опять таже история - тишина, тишина, минут через несколько все залетели и открылись
> Но именно все разом и через некоторое время
> В общем это работает намного лучше. Да, вроде как есть пропуски. Но в целом со временем все попадают в таблицу.

В любом случае, до этого у человека вообще не работало. Нужно будет собрать очередную версию, и проверить с такими правилами.

Рубрика странности Кинетика: вот мы свои правила помещаем под системными. Если посмотреть в системный NAT `iptables -L -t nat > /opt/tmp/iptables_nat.txt`, то там пусто выше нас (в цепочках _NDM_DNAT и иже с ними). Что на моём роутере, что на проблемном. Но на моём роутере правила отрабатывают, а на новых одна из цепочек заполнена невидимыми нам правилами. Как пишет техподдержка на форуме в схожих темах, а зачем вам это видеть? В общем, iptables очень закостыленный под себя. И сейчас будем залазить выше системного _NDM_DNS_REDIRECT.

**Comment by AltGrF13** [comment]
Текущая доработка меняет приоритет так
![image](https://github.com/user-attachments/assets/fa5c3a7e-5c62-47aa-9ddb-3118ccc2cc6c)

**Comment by AltGrF13** [comment]
Из интересного на будущее ещё по поводу настроек DNS из админки. Вот у человека указаны куча DNS и добавлен один DoT. Согласно доке, тогда нешифрованные DNS игнорируются. И это реально так. Но интересно другое: у него обращение к внешнему DNS идёт через редирект на порт 40500 в роутере. Вот как выглядит ndnproxymain.conf
![image_2024-11-18_18-43-30](https://github.com/user-attachments/assets/20e92c33-3170-4979-8fd8-45824620838c)
