### ISSUE TITLE
Доводка debug

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#215]
1. Каких-то моментов не хватает для гостевых (дольше описывать буду, чем кодить).
2. ipset
  2.1. При полностью динамическом ipset предыдущий тест на домены не подскажет ничего, к тому же путает людей. Когда у них не  работало, они просто делали тест, получали ручной прогрев kdig'ами и полуработу.
  2.2. Обучать людей командам утомительно, сделал вывод разной статы.
  
После того, как Вы создали тот удобный метод; понял, что мне не хватало)

**Comment by AltGrF13** [comment]
### kvas debug iptables
![image](https://github.com/user-attachments/assets/cab0d5be-c3a8-46e0-8ddd-0c833b03ff55)
![image](https://github.com/user-attachments/assets/828fcd3f-5824-4204-94d6-24c1fcc49e6a)

**Comment by AltGrF13** [comment]
### kvas debug ipset
![image](https://github.com/user-attachments/assets/f592c795-8534-41bb-a17d-df667cc1dba2)
Доменные IP упорядочиваются по ttl (ведь самый большой — самый последний влетевший). Из-за отсутствия -k у sort на роутере, вытаскиваются 7 последних ttl и все IP с ними. Число последних получается динамическим)
![image](https://github.com/user-attachments/assets/5b6faf0e-d022-4ddc-9c1c-47d1f0c43d17)
Блок с IP из списка не выводится, если IP там нет.

`kvas debug ipset clear|flush` кроме `ipset flush kvas_ipset` обратно заполняет IPSet IPшниками, если они были в списке.
`kvas debug ipset 34.160.111.145` или `kvas debug ipset myip2` добавит его в IPSet для теста всей схемы, если динамического заполнения не происходит.

**Comment by qzeleza** [comment]
Спасибо за проделанную работу. 
Добавлено в **Квас 1.1.9-beta-9**
