### ISSUE TITLE
КВАС не предлагает заполнить данные Shadowsocks

### ISSUE THREAD

**Issue by impaxel** [qzeleza/kvas#22]
**Мой девайс:** Keenetic Hopper (KN-3810)
**Версия КВАСа:** КВАС 1.0 beta 21

При установке пакета с нуля, КВАС не предлагает ввести данные сервера Shadowsocks. Вместо этого после выбора VPN интерфейса сразу запускает сервис с неизвестными данными. Установка пакета производилась на чистую, только что установленную и обновленную Entware.

Если открыть файл `shadowsocks.json`, то он будет следующего содержания:
<pre>
{
    "server":["::1", "127.0.0.1"],
    "mode":"tcp_and_udp",
    "server_port":8388,
    "local_port":1080,
    "password":"barfoo!",
    "timeout":86400,
    "method":"chacha20-ietf-poly1305"
}
</pre>
Выполнение команд `kvas vpn set/scan/rescan/reset` никак не решают проблему. Если удалить `shadowsocks.json`, то после повторного выбора интерфейса таки предлагает ввести данные сервера и все работает. 
Однако при выполнении команды любой команды `kvas` начинают появляться следующие сообщения:
<pre>
~ # kvas vpn
ip: can't find device 'shadowsocks'
ip: can't find device 'shadowsocks'
-----------------------------------------------------------------------------------
Текущее VPN соединение: SHADOWSOCKS                                 ПОДКЛЮЧЕНО
-----------------------------------------------------------------------------------
</pre>
Так же прикладываю лог из консоли во время установки: [install.log](https://github.com/qzeleza/kvas/files/10032728/install.log)

**Comment by qzeleza** [comment]
Взял в работу.

**Comment by qzeleza** [comment]
Обновил 21 бету - попробуйте скачать и переустановить. 
Жду обратной связи.

**Comment by impaxel** [comment]
Только что проверил - без изменений. Ставил так же с нуля, предложения заполнить данные сервера не было.

**Comment by qzeleza** [comment]
Тогда прошу прислать лог установки - необходимо скопировать данные с экрана установки или сделать скриншот от начала установки до полного завершения.

**Comment by impaxel** [comment]
[kvas.log](https://github.com/qzeleza/kvas/files/10047095/kvas.log)

**Comment by impaxel** [comment]
Не разбирался, если честно, но эти записи присутствуют в логах и до установки КВАСа.

**Comment by cinglok** [comment]
Добрый день.

 Тоже столкнулся с ошибкой при установке на чистую Entware.  Роутер - Вива1910.
`-----------------------------------------------------------------------------------
Установка пакета КВАС™ версия 1.0-beta-21
-----------------------------------------------------------------------------------
ash: {
}: bad number
Для корректной работы DNS сервера необходимо отключить использование DNS провайдера!
С этой целью зайдите в админ панель роутера по адресу: http://192.168.127.1:{
}/a
и выполните последовательно три следующих команды:
-----------------------------------------------------------------------------------
1. opkg dns-override  - отключаем использование DNS провайдера,
2. system configuration save   - сохраняем изменения,
3. system reboot  - перегружаем роутер.
-----------------------------------------------------------------------------------
Collected errors:
 * pkg_run_script: package "kvas" postinst script returned status 1.
 * opkg_configure: kvas.postinst returned 1.
/opt/packages # kvas test
ip: can't find device ''
ip: can't find device ''
/opt/bin/kvas: line 291: can't open /opt/etc/hosts.list: no such file
-----------------------------------------------------------------------------------
sh: {
}: bad number
Для корректной работы dnsmasq необходимо исключить влияние провайдера на Ваши DNS запросы!
С этой целью зайдите в админ панель роутера по адресу: http://192.168.127.1:{
}/a
и введите в поле Command следующую команду opkg dns-override , затем нажмите ENTER.
далее в том же поле введите команду system configuration save , затем нажмите ENTER.
И третьим шагом необходимо перегрузить роутер, для этого в том же поле
введите команду system reboot , затем нажмите ENTER.
/opt/packages # opkg install /opt/packages/kvas_1.0-beta_21_all.ipk
Package kvas (1.0-beta_21) installed in root is up to date.
Configuring kvas.
-----------------------------------------------------------------------------------
Установка пакета КВАС™ версия 1.0-beta-21
-----------------------------------------------------------------------------------
ash: {
}: bad number
Для корректной работы DNS сервера необходимо отключить использование DNS провайдера!
С этой целью зайдите в админ панель роутера по адресу: http://192.168.127.1:{
}/a
и выполните последовательно три следующих команды:
-----------------------------------------------------------------------------------
1. opkg dns-override  - отключаем использование DNS провайдера,
2. system configuration save   - сохраняем изменения,
3. system reboot  - перегружаем роутер.
-----------------------------------------------------------------------------------
Collected errors:
 * pkg_run_script: package "kvas" postinst script returned status 1.
 * opkg_configure: kvas.postinst returned 1.
`

**Comment by qzeleza** [comment]
> Тоже столкнулся с ошибкой при установке на чистую Entware. Роутер - Вива1910.


Доброго дня, 
Пока по описанным Вами действиям не вижу проблемы.
Из приведенного Вами лога вижу, что Вы не следовали [инструкциям установки пакета.](https://github.com/qzeleza/kvas/blob/main/README.md#установка) и только.

**Comment by cinglok** [comment]
> Доброго дня, Пока по описанным Вами действиям не вижу проблемы. Из приведенного Вами лога вижу, что Вы не 
> следовали [инструкциям установки пакета](https://github.com/qzeleza/kvas/blob/main/README.md#%D1%83%D1%81 
> %D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0) и только.

Прошу прощения, почему-то был уверен, что днс можно переопределить и после. Я так понимаю, что проблема именно в этом. Спасибо!

**Comment by qzeleza** [comment]
Вышла [бета 22](https://github.com/qzeleza/kvas/blob/main/ipk/), пробуем. 
Жду обратной связи по данному этикету.

**Comment by cinglok** [comment]
В первом приближении всё заработало с первого раза. Прошивка 3.9.1 Есть косметическая ошибка в отображении таблицы узлов
![изображение](https://user-images.githubusercontent.com/41973459/206732767-372aa758-7a88-4bdf-98f0-4bedea31e5b0.png)

**Comment by qzeleza** [comment]
Не вполне ясно а какой косметической  ошибке идет речь. Можете прокомментировать более подробно?

**Comment by qzeleza** [comment]
Принял, благодарю
Тикет закрываю.
