### ISSUE TITLE
kvas crypt: доводки

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#222]
1. Включил, вызвал отключение `kvas crypt off`. Команда выполнялась "бесконечно", хотя и все замены в конфигах сделала.

2. При `kvas crypt on` в `dnsmasq.conf` установлено `server=127.0.0.1#9153`. Т.е. все запросы пойдут туда. Это верно. Но в файле `kvas.dnsmasq` для каждого сервера указано
```
ipset=/artifacts.elastic.co/kvas_ipset
server=/artifacts.elastic.co/127.0.0.1#9153
```
Обычно server для домена указывается, когда нужно изменить от общего на частное. Но тут они равны. Не нужно повторяться. Для каждого домена при `kvas crypt on` должен быть указан лишь `ipset=/artifacts.elastic.co/kvas_ipset`.

3. При `kvas crypt off` в `dnsmasq.conf` установлено `server=9.9.9.9`. Т.е. все запросы пойдут туда. Это верно. Но в файле `kvas.dnsmasq` для каждого сервера указан лишь `ipset=/artifacts.elastic.co/kvas_ipset`. Т.е. запросы для списка пойдут открытым протоколом на 9.9.9.9; где их можно как банить, так и отслеживать. Запросы для списка всегда должны ходить шифрованно, в независимости от установки флага `kvas crypt`. Т.е. в этом режиме я как раз ожидал бы в файле
```
ipset=/artifacts.elastic.co/kvas_ipset
server=/artifacts.elastic.co/127.0.0.1#9153
```
Именно в таком виде, в DNSCrypt; у них свой отдельный DNS, не совпадающий с общим, тут это уместно. Т.е. DNSCrypt должен всегда работать. В режиме on на все запросы, в режиме off обслуживать лишь защищённый список (на то он и защищённый).

4. `filter-rr=HTTPS` тоже не плохо ложится на `kvas crypt`. Когда off, то смело можем фильтровать защиту DNS `filter-rr=HTTPS`. Когда on, то насильное откидывание ECH — плохая идея, лучше закомментировать `#filter-rr=HTTPS`.

**Comment by qzeleza** [comment]
Не совсем понятно, что Вы предлагаете сделать по пп. 1-4?

**Comment by AltGrF13** [comment]
Начнём последовательно. Пункт 1 у Вас не воспроизводится? Если поделать команды kvas crypt off, kvas crypt on, kvas crypt off последовательно; то команда off выходит, бесконечно не висит?

**Comment by qzeleza** [comment]
1. В крайней бете - все штатно - зависаний нет
2-3. Совсем не понял суть изменений - поясните пожалуйста, что на что необходимо изменить? 
4. Пожалуйста, поясните конкретно, что на что заменить и при каких условиях?

**Comment by AltGrF13** [comment]
> В крайней бете - все штатно - зависаний нет

У меня off не отрабатывает и периодически (если вызвать несколько раз по циклу включение-отключение) полностью очищает файл `/opt/etc/dnsmasq.d/kvas.dnsmasq`

**Comment by AltGrF13** [comment]
### filter-rr=HTTPS в /opt/etc/dnsmasq.conf

При `kvas crypt off` включать
```
filter-rr=HTTPS
```

При `kvas crypt on` отключать
```
#filter-rr=HTTPS
```

**Comment by qzeleza** [comment]
включил все выше и пересобрал 1.1.9b9

**Comment by AltGrF13** [comment]
### kvas crypt off

Делаю
```
kvas crypt off
kvas clear
kvas import /opt/tmp/unblock.txt
```
В файле `/opt/etc/dnsmasq.d/kvas.dnsmasq`
```
ipset=/artifacts.elastic.co/kvas_ipset
ipset=/jetbrains.com/kvas_ipset
ipset=/www.soapui.org/kvas_ipset
```
Хотя ожидается
```
ipset=/artifacts.elastic.co/kvas_ipset
server=/artifacts.elastic.co/127.0.0.1#9153
ipset=/jetbrains.com/kvas_ipset
server=/jetbrains.com/127.0.0.1#9153
ipset=/www.soapui.org/kvas_ipset
server=/www.soapui.org/127.0.0.1#9153
```
_Ведь DNS доменов из защищённого списка всегда должны ходить через DNSCrypt._

### kvas crypt on
Делаю
```
kvas crypt on
kvas clear
kvas import /opt/tmp/unblock.txt
```
В файле `/opt/etc/dnsmasq.d/kvas.dnsmasq`
```
ipset=/artifacts.elastic.co/kvas_ipset
server=/artifacts.elastic.co/127.0.0.1#9153
ipset=/jetbrains.com/kvas_ipset
server=/jetbrains.com/127.0.0.1#9153
ipset=/www.soapui.org/kvas_ipset
server=/www.soapui.org/127.0.0.1#9153
```
Хотя ожидается
```
ipset=/artifacts.elastic.co/kvas_ipset
ipset=/jetbrains.com/kvas_ipset
ipset=/www.soapui.org/kvas_ipset
```
_Ведь весь DNS трафик уже идёт через DNSCrypt._

**Comment by qzeleza** [comment]
Попробуйте проверить состояние `/opt/etc/dnsmasq.d/kvas.dnsmasq` сразу после `kvas crypt on` и `kvas crypt off`.
Все ли правильно добавляется, если нет, то поправлю, если да, то тогда нужно уже смотреть что не так с`import`.
Но это уже другая подзадача.

**Comment by AltGrF13** [comment]
Да, давайте разделим, пока речь только о переключениях. Пункты 1 и 4 сделаны. Устанавливаю с нуля. Судя по `kvas crypt` шифрование включено. Файл `/opt/etc/dnsmasq.d/kvas.dnsmasq` правильный.

Делаю `kvas crypt off`. В файле
```
ipset=/2ip.ru/kvas_ipset
ipset=/ifconfig.me/kvas_ipset
ipset=/myip2.ru/kvas_ipset
```
секции `server=/*/127.0.0.1#9153` по-прежнему нет.

**Comment by AltGrF13** [comment]
Да, давайте разделим, пока речь только о переключениях. Пункты 1 и 4 сделаны. Устанавливаю с нуля. Судя по `kvas crypt` шифрование включено. Файл `/opt/etc/dnsmasq.d/kvas.dnsmasq` правильный.

Делаю `kvas crypt off`. В файле
```
ipset=/2ip.ru/kvas_ipset
ipset=/ifconfig.me/kvas_ipset
ipset=/myip2.ru/kvas_ipset
```
секции `server=/*/127.0.0.1#9153` по-прежнему нет.

Делаю ещё цикл включения-отключения. `server=/*/127.0.0.1#9153` появляется, но теперь в шифрованном режиме перестаёт удаляться.

**Comment by qzeleza** [comment]
Нашел в коде ошибку - забыл указать в sed параметр -i чтобы в файле происходили изменения
Сейчас поправлю

**Comment by AltGrF13** [comment]
Установил с нуля. Судя по `kvas crypt` шифрование включено. Файл /opt/etc/dnsmasq.d/kvas.dnsmasq правильный.
Делаю `kvas crypt off`, появляются секции `server=/myip2.ru/127.0.0.1#9153`, всё верно.
Делаю `kvas crypt on`, секции `server=/myip2.ru/127.0.0.1#9153` остались.
Делаю ещё раз `kvas crypt off`, пошло задвоение секции сервер. Видимо, off отрабатывает верно, c on проблемы.

**Comment by qzeleza** [comment]
Обновил и перезалил 9 бету в канале, так как изменений почти нет - не стал писать об этом там.

**Comment by AltGrF13** [comment]
Установил. По умолчанию со старта `kvas crypt` подключен, но секция `server=` в `/opt/etc/dnsmasq.d/kvas.dnsmasq` есть.
Отключаю `kvas crypt off` — задвоение.
Включаю `kvas crypt on` — задвоение остаётся.

Если после этого почистить руками до
```
ipset=/2ip.ru/kvas_ipset
ipset=/ifconfig.me/kvas_ipset
ipset=/myip2.ru/kvas_ipset
```
и отключить, то сразу задвоенные строчки.

**Comment by AltGrF13** [comment]
Установил. По умолчанию со старта `kvas crypt `подключен, cекции `server=` в `/opt/etc/dnsmasq.d/kvas.dnsmasq` нет. Всё хорошо.

Отключаю вызовом `kvas crypt off` — секция `server=` появилась, основные настройки переключились, снова всё хорошо.

Включаю `kvas crypt on` — секция `server=` осталась, не удалилась.
При этом в этом режиме сделал импорт, и залилось всё верно, без `server=`.
Импорт с отключенным крипт тоже работает верно, с секцией сервер.

**Итого**: есть проблема лишь при переходе из состояния `kvas crypt off` в `kvas crypt on`, секция `server=` не удаляется.

**Comment by qzeleza** [comment]
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/24b0841b-e18b-4c59-bff1-887617c238c5">
Не увидел проблем - на рисунке ситуация не подтверждается

**Comment by AltGrF13** [comment]
Я как раз описал, что импорт работает верно (что проверяете Вы). Не верным остаётся сам список после включения.

### Как воспроизвести
Перескачиваю последнюю версию (106519 байт)
```
kvas uninstall full
reboot
opkg install /opt/tmp/kvas_1.1.9-beta_9_all.ipk | tee /opt/tmp/kvas_install.log
kvas setup | tee -a /opt/tmp/kvas_setup.log
cat /opt/etc/dnsmasq.d/kvas.dnsmasq
# верный вывод без server=
kvas crypt off
cat /opt/etc/dnsmasq.d/kvas.dnsmasq
# верный вывод с server=
kvas crypt on
cat /opt/etc/dnsmasq.d/kvas.dnsmasq
# не верный вывод
ipset=/2ip.ru/kvas_ipset
server=/2ip.ru/127.0.0.1#9153
ipset=/ifconfig.me/kvas_ipset
server=/ifconfig.me/127.0.0.1#9153
ipset=/myip2.ru/kvas_ipset
server=/myip2.ru/127.0.0.1#9153

kvas add abc.com
cat /opt/etc/dnsmasq.d/kvas.dnsmasq
# верный вывод
```

Может после включения (а может и отключения, для упрощения кода) просто вызывать пересборку `/opt/etc/dnsmasq.d/kvas.dnsmasq`? Не адаптировать файл руками, а вызывать единый метод перегенерации (раз он работает верно)? Ну или в быстрой ручной адаптации подправить удаление этой секции.
