### ISSUE TITLE
Не запускается AdGuard Home после перезапуска KVAS

### ISSUE THREAD

**Issue by sp1ne** [qzeleza/kvas#238]
**Опишите проблему.**
_После перезагрузки роутера не запускается AdGuard Home автоматически и, соответственно, нету доступа в интернет, приходится лезть по SSH и вручную запускать kvas adguard on , тогда всё заводится._

**Какие шаги, привели к ошибке/проблеме?**
_Перезагрузка роутера._

**Какие ожидания о поведении программы?**
_AdGuard Home запустится вместе с KVAS после перезагрузки роутера._

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: _Keenetic_
- Прошивка на роутере: _2.16.D.12.0-11_
- Тип устройства: _Ultra (чёрный, 1-ое поколение)_

**Дополнительно:**
_Установка «чистая», после сброса роутера до заводских настроек через панель управления. Далее установка KVAS по шагам [из инструкции](https://github.com/qzeleza/kvas/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0), во время установки ошибок небыло.
В поле «Сценарий initrc» в разделе «OPKG» webui интерфейса роутера прописано /opt/etc/init.d/rc.unslung
В каталоге /opt/etc/init.d/ файл S99adguardhome, запускающий AdGuard Home вместе с запуском KVAS — имеется._

Почистил файл AdGuardHome.log перез перезагрузкой роутера, перезагрузил роутер, прикрепил свежий 
[AdGuardHome.log](https://github.com/user-attachments/files/18061053/AdGuardHome.log)
Далее вручную запустил kvas adguard on и получил сбой при установке AdGuard Home в качестве основного DNS сервера: 
![2024-12-09_14-56-29](https://github.com/user-attachments/assets/41198e0b-3d9d-405e-937f-62eab7d47ee0)
Но AdGuardHome запустился, интернет появился, разблокированные сайты из списка открываются нормально.

**Comment by sp1ne** [comment]
Дополнительно: установка «чистая», после сброса роутера до заводских настроек через панель управления. Далее установка KVAS по шагам [из инструкции](https://github.com/qzeleza/kvas/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0), во время установки ошибок небыло.

**Comment by sp1ne** [comment]
После перезагрузки роутера выполнил **kvas test**:
```
Состояние службы dnsmasq
/opt/bin/kvas: line 101: /opt/etc/init.d/S56dnsmasq: not found ОСТАНОВЛЕНА
Перезапускаем еще раз dnsmasq ОШИБКА
Запустите диагностику командой kvas debug
```
Далее **kvas debug**:
```
Версия пакета 1.1.8 release-2
Состояние службы dnsmasq по команде
/opt/etc/init.d/S56dnsmasq status ОСТАНОВЛЕНА
--------------------------------------------------------------------------------------------------------------------
[] Проблемы при выделении адресов для аренды DHCP
```
Далее **kvas adguard on** :
```
AdGuard Home установлен в качестве основного DNS сервера СБОЙ
Возникла ошибка при установке AdGuard Home в качестве основного DNS сервера.
--------------------------------------------------------------------------------------------------------------------
2024/12/11 11:25:18.798035 [info] dnsproxy: cache enabled size=4096
2024/12/11 11:25:18.799542 [info] dnsproxy: max goroutines is set count=300
2024/12/11 11:25:18.801088 [info] dnsproxy: ratelimit is enabled rps=20 ipv4_subnet_mask_len=24 ipv6_subnet_mask_len=56
2024/12/11 11:25:18.806265 [info] dnsproxy: server will refuse requests of type any
2024/12/11 11:25:18.807592 [info] dnsproxy: upstream mode is set mode=load_balance
2024/12/11 11:25:18.808875 [info] dnsproxy: cache enabled size=4194304
2024/12/11 11:25:18.818687 [info] dnsproxy: max goroutines is set count=300
2024/12/11 11:25:18.822238 [info] addrproc: processing addresses
2024/12/11 11:25:18.830928 [info] AdGuard Home is available at the following addresses:
2024/12/11 11:25:18.831605 [info] go to http://192.168.1.1:8080
```
После последней команды интернет появляется.
В каталоге **/opt/etc/init.d** лежат только эти файлы:

1. rc.func
2. rc.unslung
3. S10cron
4. S22shadowsocks
5. S51dropbear
6. S99adguardhome

Как я понимаю, проблема с отсутствием запрашиваемого S56dnsmasq в этом же каталоге. Или должен запускаться S99adguardhome вместо него (так как я устанавливал по инструкции KVAS + AdGuardHome)?

Как это дело поправить, подскажите, пожалуйста?

**Comment by sp1ne** [comment]
Лог AdGuard Home после перезагрузки роутера:
```
2024/12/11 12:50:51.470992 [info] Received signal "terminated"
2024/12/11 12:50:51.471527 [info] stopping AdGuard Home
2024/12/11 12:50:51.471842 [info] stopping http server...
2024/12/11 12:50:51.484317 [info] stopped http server
2024/12/11 12:50:51.501750 [info] dnsproxy: stopping server
2024/12/11 12:50:51.510751 [info] dnsproxy: stopped dns proxy server
2024/12/11 12:50:51.885595 [info] stopped
```

**Comment by qzeleza** [comment]
> warning: SO_REUSEPORT not supported err="protocol not available"
 
 Просмотрите Ваш файл конфигурации ADGH, видимо где то указана не поддерживаемая SO_REUSEPORT

**Comment by sp1ne** [comment]
> > warning: SO_REUSEPORT not supported err="protocol not available"
> 
> Просмотрите Ваш файл конфигурации ADGH, видимо где то указана не поддерживаемая SO_REUSEPORT

В конфигурации ADGH (смотрел и .yaml и .conf) вообще упоминаний про параметр "SO_REUSEPORT" нету.

Команда **grep -lr "SO_REUSEPORT" /** выводит только файлы логов и 1 исполняемый /opt/bin/AdGuardHome с самой программой.

**Comment by sp1ne** [comment]
Пока что отказался от AdGuardHome и перешёл на KVAS + dnsmasq + dnscrypt, все работает замечательно, в том числе и после перезагрузки роутера. Стоит сменить связку на KVAS + AdGuardHome - всё ломается после перезагрузки.
Если дадите пищу для размышлений - буду признателен, пока не очень понимаю в какую сторону копать.

**Comment by NSGrid** [comment]
Скажите, пожалуйста, есть ли какие-то варианты исправления проблемы. Столкнулся с тем же самым и логи очень похожие. После перезапуска роутера - автоматом не стартует ADGH. Причем, если запустить затем руками (скрипт S99adguardhome), то стартует все нормально. Может, надо просто какую-то задержку сделать в выполнении этого скрипта?
