### ISSUE TITLE
Выполнение команды kvas vpn reset завершается ошибкой

### ISSUE THREAD

**Issue by impaxel** [qzeleza/kvas#24]
**Мой девайс:** Keenetic Hopper (KN-3810)
**Версия КВАСа:** КВАС 1.0 beta 21
**VPN соединение:** Shadowsocks

При выполнении команды `kvas vpn reset` отображается следующее сообщение:
<pre>
~ # kvas vpn reset
-----------------------------------------------------------------------------------
Переустановка iptables для vpn завершена                            C ОШИБКАМИ
-----------------------------------------------------------------------------------
</pre>
На работоспособность вроде не влияет, с другими VPN интерфейсами не проверял.
В логах роутера:
<pre>
[I] Nov 17 20:47:10 КВАС: Производим удаление правил match-set в таблице mangle, цепочке PREROUTING для VPNREDIR
[I] Nov 17 20:47:10 КВАС: Производим удаление правил match-set в таблице mangle, цепочке OUTPUT для VPNREDIR
[I] Nov 17 20:47:10 КВАС: Производим удаление правил в таблице mangle и цепочке OUTPUT и удаляем цепочку.
[E] Nov 17 20:47:11 КВАС: ОШИБКА::iptables: No chain/target/match by that name.
[E] Nov 17 20:47:11 КВАС: ОШИБКА::iptables: No chain/target/match by that name.
</pre>
`kvas debug`: [kvas.log](https://github.com/qzeleza/kvas/files/10034333/kvas.log)

**Comment by impaxel** [comment]
Готово, получил следующий результат:
<pre>
~ # iptables-save | grep SHADOW
:SHADOWSOCKS - [0:0]
-A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
-A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
-A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
-A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
-A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
-A SHADOWSOCKS -d 195.123.216.26/32 -j RETURN
</pre>

**Comment by qzeleza** [comment]
Вышла [бета 22](https://github.com/qzeleza/kvas/blob/main/ipk/), пробуем. 
Жду обратной связи по данному этикету.

**Comment by qzeleza** [comment]
Прошу дать обратную связь поданному этикету, в противном случае, тикет будет закрыт через 3 дня.
