### ISSUE TITLE
IPSet: заполнение, истечение

### ISSUE THREAD

**Issue by AltGrF13** [qzeleza/kvas#241]
Давно обещал дополнительно проверить истечение таймаутов и работу в целом. После #225 появились новые механизмы доработки (часть из которых заводил под проблему ttl), поэтому начнём.

**Comment by AltGrF13** [comment]
А. Сделаем
```
/opt/etc/init.d/S56dnsmasq restart
kvas ipset flush
ipset list KVAS_LIST | grep 81.90.181.105
```
Записи myip2.ru нет. <ins>Всё хорошо</ins>.

Б. Кинем с пользовательского устройства `nslookup myip2.ru`, запись в IPSet появляется. <ins>Всё хорошо</ins>.

В. Удалим
```
ipset del KVAS_LIST 81.90.181.105
```
На пользовательском устройстве `ipconfig /flushdns`, новый NSLookup — и ничего. Записи нет, она должен заполняться, но этого не происходит.

Г. Перезапустим
```
/opt/etc/init.d/S56dnsmasq restart
kvas ipset
```
Увидим, что ipset при перезапуске не сбрасывается. Но в этот раз после `nslookup myip2.ru`, запись в IPSet появляется. <ins>Всё хорошо</ins>.

При перезапуске происходит сброс кэша. Проверим эту теорию, отключим `cache-size=0` и снова прогоним А–В. В начинает заполняться стабильно!

Вывод: если DNSMasq берёт запись из кэша, то он не производит заполнение ipset. В нём надо будет отключить, в DNSCrypt включить. К сожалению, на режиме crypt off это скажется отрицательно (большая часть DNS вне кэша). А жаль, потому что именно он сейчас позволяет жить с IPv6 интернетом.

**Comment by AltGrF13** [comment]
### Заполнение при истечении ttl

```
ipset -exist add KVAS_LIST 81.90.181.105 timeout 10000
ipset list KVAS_LIST | grep 81.90.181.105
81.90.181.105 timeout 9997
```

С пользовательского устройства делаем
```
ipconfig /flushdns
nslookup myip2.ru
```

Снова на роутере
```
ipset list KVAS_LIST | grep 81.90.181.105
81.90.181.105 timeout 86397
```

**Вывод:** проблема не подтверждена! Даже если запись в ipset близка к истечению, новый DNS-запрос запускает отсчёт заново, продляет ttl.

**Comment by qzeleza** [comment]
Благодарю Вас.
PR внес в основной код, выпущена версия **1.1.9 beta10-3**

**Comment by AltGrF13** [comment]
Снова прогнал все тесты, всё отлично
