### ISSUE TITLE
KVAS не видит актуальное прокси-соединение

### ISSUE THREAD

**Issue by Leviann** [qzeleza/kvas#246]
**Опишите проблему.**
Ранее настраивался SOCKS5 прокси к одному ip адресу, потом я поменял его на другой ip адрес. Соединение работает.
После этого я установил KVAS, однако при настройке (kvas vpn set) отображается старый ip адрес прокси-соединения, как отключенный. Новый - не видит в упор.
Пробовал передобавлять соединение - не помогло.

**Какие шаги, привели к ошибке/проблеме?**
1. Создал socks5 proxy с ip 1
2. Поменял ip адрес socks5 proxy на 2
3. Установил kvas, изначально выбрав wg соединение
4. Выполнил команду kvas vpn set чтобы поменять ресурсоемкое wg на socks5
5. Обнаружил socks5 proxy с ip 1 как отключенное и недоступное
6. socks5 proxy с ip 2 отсутствует в списке впринципе

**Какие ожидания о поведении программы?**
Отображается актуальное socks5 соединение

**Приложите снимки экрана или сам текст с консоли.**
![2024-12-15-14-28-17-135](https://github.com/user-attachments/assets/c7be4586-7787-4c42-977e-0bca1a453e13)
![2024-12-15-14-29-35-006](https://github.com/user-attachments/assets/b303476e-0450-43b0-9366-e0df973cf764)

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
**Заполните информацию о системе на роутере:**
- Keenetic Peak (KN-2710) on KeeneticOS 4.2.3
- BusyBox v1.36.1 (2024-07-23 11:34:57 UTC) built-in shell (ash)

**Comment by qzeleza** [comment]
Удалите свое соединение и просканируйте снова. Остается только Wireguard.
Затем снова создайте соединение и просканируйте его. Должно получиться.

**Comment by Leviann** [comment]
К сожалению это не помогло.

**Comment by qzeleza** [comment]
Тогда более полно опишите проблему. 

Не ясно, какой адрес именно Вы меняете и с какой целью? Почему на вновь создаваемом соединении Вы не устанавливаете "правильный адрес"? 
Что значит "Обнаружил socks5 proxy с ip 1 как отключенное и недоступное"? Как Вы его обнаружили?
О каком втором подключении идет речь, если Вы его удалили?

**Comment by Leviann** [comment]
У меня до установки kvas'а было два соединения: wireguard и socks5 прокси с адресом 1.2.3.4.
Позже я удалил socks5 прокси с адресом 1.2.3.4 и добавил новое socks5 прокси с адресом 5.6.7.8.
Установил kvas с использованием wireguard, но хочу использовать socks5.
При поиске показывается удаленное socks5 прокси с адресом 1.2.3.4, хотя его уже давно нет. Отображается оно как отключенное.
Нового socks5 прокси с адресом 5.6.7.8 в списке нет.

**Comment by qzeleza** [comment]
Вы точно сканировали соединения при запуске команды vpn set?

**Comment by Leviann** [comment]
Конечно, и уже неоднократно. Собственно только так и пытался изменить соединение.

**Comment by AltGrF13** [comment]
В бете это есть. А в финалке, скорее всего, не хватает в `/opt/apps/kvas/bin/libs/vpn` в функции `update_interface_name_list` более широкой строчки
```
types_inface_included='"OpenVPN","Wireguard","IKE","SSTP","PPPOE","L2TP","PPTP","Proxy", "OpenConnect" '
```
