### ISSUE TITLE
Полностью кладется роутер (возможная причина - AGH, КВАС) 

### ISSUE THREAD

**Issue by Horizont32** [qzeleza/kvas#25]
Мониторил поведение роутера примерно неделю на следующем конфиге, на 18 бетке и раньше, чем 18, такого не было:
AGH + KVAS_beta_21
Роутер - Viva KN-1910 (Возможно, проблема в 128 Мб оперативки)

В какой-то момент (происходит рандомно, может через 5 часов после загрузки роутера, может через сутки) роутер ловит ошибки по ядру и начинает убивать все процессы, логи РОУТЕРА прикладываю, скрин с показаниями загрузки CPU и MEM тоже.

Помогает только ручная перезагрузка роутера через дерганье автомата.

![199338024-65602f6c-8a94-4f1a-97cd-dfc702951f3d](https://user-images.githubusercontent.com/42933596/203378413-2e3d02c8-694a-4fef-ad3f-b400340eb898.jpeg)
[logs_router.txt](https://github.com/qzeleza/kvas/files/10069577/logs_router.txt)

**Comment by qzeleza** [comment]
Насколько я помню данный вопрос был закрыт на форуме - дело было в очень малом объеме памяти самой модели роутера. Жаль, что не комментируете закрытие этикета здесь.
