### ISSUE TITLE
При первоначальной настройке отсутствует вомзожность выбора подключения Openconnect. 

### ISSUE THREAD

**Issue by vinte97** [qzeleza/kvas#258]
Имеем keenetic Vivo KN-1913
VPS с OpenConnect сервером. Подключение работает и стабильно.
При первоначальной настройке:
opkg install curl && curl -sOfL http://kvas.zeleza.ru/install && sh install
на моменте выбора впн подключения, подключение OpenConnect не отображается.

<img width="651" alt="Снимок экрана 2024-12-22 в 12 03 38" src="https://github.com/user-attachments/assets/d65d7575-b139-440d-adfa-ed61463d6f46" />
При этом существует интерфейс nocli1  через который осуществляется подключение.

**Comment by qzeleza** [comment]
Данный вопрос уже давно решен в крайних бетах. Проблема не актуальна.
