### ISSUE TITLE
Сайт вне списка разблокировки (google.com) идет через туннель

### ISSUE THREAD

**Issue by DenisDudnik** [qzeleza/kvas#259]
**Опишите проблему.**
В списке разблокировки отсутствует адрес `google.com`.
Спустя какое-то время этот адрес начинает ходить через туннель.
При этом в списке разблокировки он не появляется.

**Какие шаги, привели к ошибке/проблеме?**
Опишите подробно шаги, которые привели к ошибке:

1. Запустил на ПК команду 'traceroute google.com'
2. В ответе на втором шаге вижу туннель '2  10.8.0.1 (10.8.0.1)  208.343 ms  208.363 ms  208.348 ms'
3. Для проверки ввел команду 'kvas find google.com'
4. В ответе нет адреса `google.com` (только его поддомены)
5. Запустил команду 'kvas reset'
6. Запустил на ПК команду 'traceroute google.com'
7. В ответе на втором шаге вижу своего провайдера '2  172.17.191.1 (172.17.191.1)  3.347 ms  3.354 ms  3.387 ms'
8. Ошибка: `google.com` самопроизвольно начинает ходить через туннель.

**Какие ожидания о поведении программы?**
`google.com` не начинает ходить через туннель, если он отсутствует в списке разблокировки.

**Приложите снимки экрана или сам текст с консоли.**
```
~ # kvas find google
----------------------------------------------------------------------------------------------------------------------------------------
*googleapis.com
*googletagmanager.com
*googlevideo.com
bard.google.com
discord-attachments-uploads-prd.storage.googleapis.com
gemini.google.com
lookerstudio.google.com
news.google.com
play.google.com
suggestqueries.google.com
tokenized.play.google.com
wide-youtube.l.google.com
youtube-ui.l.google.com
youtubeembeddedplayer.googleapis.com
youtubei.googleapis.com
yt-video-upload.l.google.com
ytimg.l.google.com

```
```
traceroute google.com
traceroute to google.com (74.125.131.101), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.258 ms  1.732 ms  1.726 ms
 2  10.8.0.1 (10.8.0.1)  208.343 ms  208.363 ms  208.348 ms
```
```
traceroute google.com
traceroute to google.com (64.233.161.113), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.281 ms  0.257 ms  1.724 ms
 2  172.17.191.1 (172.17.191.1)  3.347 ms  3.354 ms  3.387 ms
```

**Заполните информацию о системе на роутере:**
- Операционная система (ее кодовое название) и версия: Ubuntu 22.04
- Браузер и его версия - не важно
- SSH клиент и его версия - не важно

**Заполните информацию о самом роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.1.7
- Тип устройства Ultra KN-1811

**Внесите дополнительные пояснения.**
Добавьте сюда любые пояснения, которые по Вашему мнению касаются обнаруженной ошибки/проблемы.
Команда 'kvas reset' лечит последствия проблемы, но не саму проблему.
Были мысли, что какой-то из внесенных адресов имеет тот же ip адрес, что и сам `google.com`

**Comment by AltGrF13** [comment]
> Были мысли, что какой-то из внесенных адресов имеет тот же ip адрес, что и сам google.com

Вы правы, так и есть. У Google очень большая интеграция своих сервисов друг в друга, общие сервера. Иногда даже добавление нескольких доменов YouTube может показывать аналогичную картину.

**Comment by DenisDudnik** [comment]
Я не могу найти с кем пересекается этот адрес по IP.
Как это вычислить?
Я делал так:
1. Сделал с ноутбука, подключенного к роутеру, команду `ping google.com`
2. Получил его IP.
3. На роутере выполнил команду `ipset list unblock`
4. Получил соответствие адресов разблокировки их IP.
5. В этом списке не нашел IP из п.1.

**Comment by AltGrF13** [comment]
Заходим на сайт Гугла.
Открываем консоль по F12, выполняем
```
window.domains = [...new Set(performance.getEntriesByType('resource').map(r => (new URL(r.name)).hostname))];
console.log(domains);
```
Это (при том не все) домены, которые он использовал, чтобы отобразить страницу.

Теперь каждый из этих доменов прогоняем через командную строку (не на роутере) `nslookup google.com`
Все полученные IP по каждому из доменов выписываем.

После этого на роутере проверяем каждый `ipset list unblock | grep -F '216.58.204.78'`
Пересечений нет? Не поверю)

> Получил соответствие адресов разблокировки их IP
По основным доменам лишь. При обращении к их поддоменам они тоже попадают в обход, но соотнести их (к какой родительской записи они принадлежали) возможности нет. Смотрите всю картину. Она в unblock.

**Comment by AltGrF13** [comment]
Посоветовать могу лишь использовать списки поуже. Только те сервисы Google, которыми действительно пользуетесь. Для минимальной работы YouTube, например, нужны лишь 4–7 доменов.
