### ISSUE TITLE
Не работает при нечисловом IP

### ISSUE THREAD

**Issue by ramazankzn** [qzeleza/kvas#26]
Доброго дня!
Если указывать адрес сервера в виде: "fi0.tier0.access.undef.network"
перестают открываться сайты из списка разблокировки.
Если вычислить ip-адрес этого ресурса, то все нормально работает.

Используемые данные для подключения:
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpoSmpiRlBUTlpTVXk@fi0.tier0.access.undef.network:443/?outline=1

Ниже скрин, когда прописан Ip. В имени компьютера отображается нужный URL.
Прикладываю файлы логов с IP и с URL.
![image](https://user-images.githubusercontent.com/86193880/204029286-0a95015d-e213-41a5-98f5-6bb7c8ae3d2e.png)

[logWithIp.log](https://github.com/qzeleza/kvas/files/10094348/logWithIp.log)
[logWithURL.log](https://github.com/qzeleza/kvas/files/10094349/logWithURL.log)

**Comment by qzeleza** [comment]
Доброго дня. 
О каком адресе сервера идет речь?Об адресе, Вашего VPN или SSR провайдера?
Если так, то выполните команду '**kvas dns test fi0.tier0.access.undef.network**' - если получите на выходе IP, то Квас тут не причем - обращайтесь к своему провайдеры SSR.

**Comment by ramazankzn** [comment]
Спасибо за ответ!
При выполнении команды вышел IP фэйсбука.
Если это нормально, то вопросов больше нет. Спасибо!

**Comment by qzeleza** [comment]
> При выполнении команды вышел IP фэйсбука.

Это нормально для Вашей версии Кваса. В Вашей версии (1.0-beta-15) данная функция не поддерживается. 
А вот на текущей версии пакета есть возможность тестировать DNS не только доменом  лицокнига, а командой описанной выше.

**Comment by ramazankzn** [comment]
Вышел Ip-адрес ресурса.
Спасибо.

**Comment by qzeleza** [comment]
В таком случае, данный случай не проблема пакета - ищите проблему у Вашего провайдера SSR.
