### ISSUE TITLE
Подсети

### ISSUE THREAD

**Issue by qellyka** [qzeleza/kvas#264]
Есть ли возможность добавлять подсети в ipset, оч нужно для дискорда да и вообще полезная вещь.

**Comment by AltGrF13** [comment]
Подсети поддерживаются и при импорте файла, и командой kvas add.
Более того, для быстрого обновления набора IP в бета-версии есть команда `kvas clear ip` и ускоренный/упрощенный импорт (если файл содержит только IP или диапазоны).
