### ISSUE TITLE
Kvas после рестарта ADH затирает настройки rewrite

### ISSUE THREAD

**Issue by Floppik** [qzeleza/kvas#28]
После перезагрузки или перезапуска ADH пропадают вот эти настройки:
![image](https://user-images.githubusercontent.com/38560023/204134985-586b9e79-ce03-4561-bae4-72032281dbc3.png)

Версия - kvas_1.0-beta_21_all. Проверял на 2х разных устройствах

**Comment by qzeleza** [comment]
Тикет закрываю из-за отсутствия информации необходимой для диагностики проблемы. 
Как правильно составлять тикет пожалуйста почитайте [здесь](https://github.com/qzeleza/kvas/tree/main/issues).
