### ISSUE TITLE
Неправильное\неактуальное название интерфейса WG

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#3]
beta17, после переустановки kvas  - показываются неправильные имена интерфейсов (в кинетике были переименованы).
Кажется тянется из файла /opt/etc/inface_equals  , там устаревшие данные

**Comment by qzeleza** [comment]
Придите пожалуйста пример и вывод 
`cat /opt/etc/inface_equals`

**Comment by qzeleza** [comment]
Добро, в следующей версии поставлю принудительное удаление старого inface_equals.
Благодарю.

**Comment by badigit** [comment]
Спасибо! Так то - инструмент для "гиков", и конечно разобраться можно и без этого)

Но если это возможно,  то по-красивому будет, то обновлять inface_equals  перед показом диалогов выбора интерфейса, чтобы всегда корректный был перечень

**Comment by qzeleza** [comment]
При наличии более 3 интерфейсов опрос занимает значительное время (до минуты-двух), потому перед показом диалогов выбора интерфейса проверяется на наличие самого файла, если его нет, то тогда происходит сканирование и запись в файл.
