### ISSUE TITLE
Правки в wiki

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#30]
Привествую! 
Предлагаю немного исправить вики

1. 

Подготовительные действия
>4.
> -Модули ядра подсистемы Netfilter
> -Пакет расширения Xtables-addons для Netfilter

Добавить что не требуются на новых прошивках (их нет в списке, входит в состав компонента "Поддержка открытых пакетов")

2. Если четко следовать инструкциям - не возможно будет установить КВАС, поскольку  в подготовительных действиях
п.5. требует включить opkg dns-override, после которого у вас пропадет DNS и "интернет", и пользователь не сможет выполнить другие пункты, связанные с загрузкой пакета. 

Нужно поменять порядок - сначала скачать и подготовить пакет, а затем выполнять opkg dns-override и настраивать квас.

**Comment by badigit** [comment]
И еще желательно уточнить, в случае если есть желание установить kavas + Adguard средствами kvas , то выполнять
команду "kvas adguard on" нужно до первичной пакета "kvas setup" или после?

**Comment by qzeleza** [comment]
Доброго дня

> Добавить что не требуются на новых прошивках

О каких конкретно прошивках идет речь?

**Comment by qzeleza** [comment]
> И еще желательно уточнить, в случае если есть желание установить kavas + Adguard средствами kvas , то выполнять
> команду "kvas adguard on" нужно до первичной настройки пакета "kvas setup" или после?

Без разницы, так как, если не была проведена установка пакета, то сначала выполнится команда **setup** и только затем любая другая команда, в том числе и `kvas adguard on`.

**Comment by badigit** [comment]
> О каких конкретно прошивках идет речь?
3.8.4 + видимо.

https://forum.keenetic.com/topic/14415-%D0%BF%D1%80%D0%BE%D0%B1%D1%83%D0%B5%D0%BC-%D0%BA%D0%B2%D0%B0%D1%81-shadowsocks-%D0%B8-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-vpn-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B/?do=findComment&comment=151148

**Comment by qzeleza** [comment]
Спасибо за помощь, правки сделал. 
Тикет закрываю.
