### ISSUE TITLE
После установки kvas отсутствует интернет

### ISSUE THREAD

**Issue by rurikrok** [qzeleza/kvas#31]
После установки kvas отсутствует интернет

После выполнения kvas setup на версиях 1.0-beta_22 и 1.1 пропадает подключение к интернету.
На версии 1.0-beta_21 проблема отсутствует.

Для чистоты эксперимента ставил всё с нуля.
1. Отформатировал флешку, воткнул в роутер, поставил Entware, зашёл по ssh, сменил пароль
2. opkg dns-override, system configuration save, system reboot
2. Зашёл по ssh, Установил КВАС opkg install /opt/packages/kvas_1.1_all.ipk
3. Запустил kvas setup (некритично, но kvas setup отобразил только 2 из 3 настроенных на роутере VPN, на 1.0-beta_21 проблема отсутсвует)
4. Интернет-соединение падает и не поднимается после перезагрузок роутера.
Попытки ткнуть пальцем в небо - поставить/снять в настройках соединения галку "Игнорировать DNS", удалить все DNS-серверы, указанные в настройках роутера - ситуацию не меняют.
kvas debug не выдаёт ничего кроме рекомендации перезагрузить роутер.

Скриншоты:
![kvas_setup](https://user-images.githubusercontent.com/1208974/208255831-cb3ce5f9-9fc9-45c5-871b-2fc063afcc51.png)
![no_internet](https://user-images.githubusercontent.com/1208974/208255835-1ff50224-c21a-47d3-a11e-2eeb7ae0916e.png)
![kvas_debug](https://user-images.githubusercontent.com/1208974/208255837-faaba760-b147-4f96-a86b-586302f90f76.png)

Win 11 22H2
Chrome 108
Putty 0.78

Keenetic
KeeneticOS 3.8.5.4
Ultra KN-1810

**Comment by ergashev** [comment]
Была аналогичная проблема, которая воспроизводилась на 22 бете и на стабильной 1.1.
Откат на 21 бету возвращал интернет.
Хотел в выходные поразбираться с ситуацией но, внезапно, обновление прошивки роутера с 3.8.5.4 до 3.9.1 решило проблему.

**Comment by qzeleza** [comment]
Доброго дня

> После установки kvas отсутствует интернет

Решение - чуть выше.

> 4\. некритично, но kvas setup отобразил только 2 из 3 настроенных на роутере VPN, на 1.0-beta_21 проблема отсутсвует

А вот это интересно. 
Если все установили на прошивке **3.9.1** и все заработало, кроме этого пункта, то прошу прислать` kvas debug`. Если прошивка на **3.9.1** не решила проблему, то жду сообщения в ["личку" на форуме](https://forum.keenetic.com/profile/20603-zeleza/).

**Comment by rurikrok** [comment]
Смогу проверить решение только на выходных, 24-25 декабря

**Comment by rurikrok** [comment]
Установка прошивки 3.9.1 решила проблему. спасибо за помощь.
