### ISSUE TITLE
Ошибка при удалении записи

### ISSUE THREAD

**Issue by drfischer2** [qzeleza/kvas#32]
Добавил в список разблокировки диапазон командой:

kvas add 176.58.48.48-176.58.48.0/23
в списке разблокировки запись появилась.

Потом при попытке удалить эту запись командой:
kvas del 176.58.48.48-176.58.48.0/23

получаю: 
Удаляем 176.58.48.48-176.58.48.0/23 из списка разблокировки...      sed: unsupported command 2
УДАЛЕН

И, не смотря на "УДАЛЕН", - по факту запись в списке остается.
Повторная попытка удаления записи - приводит к аналогичному результату.

**Comment by qzeleza** [comment]
К сожалению данный вид записи диапазона не поддерживается **ipset** 
```
# ipset -exist add unblock 176.58.48.48-176.58.48.0/23
ipset v7.15: Syntax error: cannot parse 176.58.48.48-176.58.48.0: resolving to IPv4 address failed
```
Поддерживаемый вариант: **176.58.48.48-176.58.48.59** или **176.58.48.0/24**

> Потом при попытке удалить эту запись командой: kvas del 176.58.48.48-176.58.48.0/23
> 
> получаю: Удаляем 176.58.48.48-176.58.48.0/23 из списка разблокировки... sed: unsupported command 2 УДАЛЕН

За ошибку спасибо - подправил, выйдет в следующем релизе.

**Comment by qzeleza** [comment]
Справку по команде add в [WIKI](https://github.com/qzeleza/kvas/wiki) обновил.

**Comment by qzeleza** [comment]
Вышла версия 1.1.1 в которой данные проблемы решены (с удалением и с информированием о недопустимости добавления подобных диапазонов адресов)
