### ISSUE TITLE
Не грузится контент приложения Youtube на IOS

### ISSUE THREAD

**Issue by XEGARE** [qzeleza/kvas#33]
**Описание проблемы.**
При использовании kvas приложение Youtube не грузит ничего. Даже нет текста. И спустя время выбивает ошибку типа нет соединения.

**Мои шаги, приведшие к ошибке/проблеме.**
Опишите подробно шаги, которые привели к ошибке:

1. Установил kvas_1.1_all.ipk
2. kvas setup
3. kvas dns 8.8.8.8
4. kvas add yt3.ggpht.com
5. Открываю приложение и не грузит ничего
6. На ПК, в сафари, в приложении ютуб на андроиде весь контент ютуба грузится(картинки с yt3.ggpht.com тоже)

**Ожидания о поведении программы.**
Ожидаю загрузку названий видео. Иконок. Самих видео.

**Снимки экрана или сам текст с консоли.**
![image](https://i.imgur.com/vXwvmLs.jpeg)

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
- Операционная система и версия: IOS 16.2
- Safari
- Приложение YouTube

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере:  3.9.1
- Giga KN-1010

**Дополнительные пояснения.**
Думаю как то связано с ДНС. Когда я ещё не использовал квас, то при использовании например 1.1.1.1 получал такое же поведение. А на гугловских 8.8.8.8 или DoH\DoT всё отлично грузилось.
Отключал шифрование. Не помогает. 
DNS менял.
Полностью удалял квас и переустанавливал.
Даже роутер сбросил. 
Ничего не помогает.

**Comment by qzeleza** [comment]
Прошу пояснить следующие моменты:

1. С какой целью исполняете команду `kvas dns 8.8.8.8`?
2. Не пользуюсь подобным сервисом **yt3.ggpht.com**, потому прошу пояснить, как связано доменное имя **yt3.ggpht.com** с видеохостингом **youtube.com**?
3. И пожалуй самый главный вопрос - как клиент подключается к роутеру на котором стоит **kvas**?

Также прошу приложить `kvas debug`

**Comment by XEGARE** [comment]
1. Сменить DNS. Хотя видимо при включенном шифровании это не работает.
2. Напрямую. Это хостинг картинок ютуба.  Аватарки, шапки каналов, а так же другие изображения(например в сообществе канала). Есть блокировка этого домена в РФ
3. По WIFI. Но это не меняет того что именно приложение не хочет работать. Сайт с IOS через Safari открывается. И все картинки я вижу - kvas работает, но что-то ломает.



<details>
<summary>kvas debug</summary>

-----------------------------------------------------------------------------------
Версия пакета КВАС 1.1-
-----------------------------------------------------------------------------------
Текущая дата и время Wed Dec 21 16:09:26 +05 2022

-----------------------------------------------------------------------------------
Информация о роутере
-----------------------------------------------------------------------------------
Страна: RU
Модель: KN-1010
Тип архитектуры: mipsel

Текущее VPN соединение: frankfurt (Wireguard0)                      ПОДКЛЮЧЕНО
УСТАНОВЛЕН список разблокировки ПО УМОЛЧАНИЮ.
Шифрование DNS трафика (dnscrypt-proxy2) ВКЛЮЧЕНО.
Блокировка рекламы НЕ УСТАНОВЛЕНА..
-----------------------------------------------------------------------------------
Установка завершена: 21/12/2022 12:44:10
-----------------------------------------------------------------------------------
Список ошибок из системного журнала
-----------------------------------------------------------------------------------
 failed to load names from /opt/etc/hosts: No such file or directory
 Dec 21 12:49:43
 Сброс пакета КВАС в исходное состояние ЗАВЕРШЕНА!
 Dec 21 12:49:47
 failed to load names from /opt/etc/hosts: No such file or directory
 Dec 21 12:51:55

Состояние службы dnsmasq по команде
/opt/etc/init.d/S56dnsmasq status                                   ЗАПУЩЕНА
-----------------------------------------------------------------------------------
Выборка из файла конфигурации dnsmasq: /opt/etc/dnsmasq.conf
-----------------------------------------------------------------------------------
user=nobody
pid-file=/var/run/opt-dnsmasq.pid
interface=br0
listen-address=192.168.1.1
listen-address=127.0.0.1
port=53
conf-file=/opt/etc/kvas.dnsmasq
proxy-dnssec

Состояние службы dnscrypt-proxy2                                    ЗАПУЩЕНА
-----------------------------------------------------------------------------------
Отчет по прослушиванию порта dnscrypt-proxy [9153]
команда: netstat -ltunp | grep "dnscrypt"
-----------------------------------------------------------------------------------
tcp 0 0 :::9153 :::* LISTEN 21868/dnscrypt-prox
udp 0 0 :::9153 :::* 21868/dnscrypt-prox

-----------------------------------------------------------------------------------
Выборка из файла конфигурации dnscrypt-proxy2 /opt/etc/dnscrypt-proxy.toml
-----------------------------------------------------------------------------------
listen_addresses = ['[::]:9153']
cache = true

-----------------------------------------------------------------------------------
Список разблокировки в /opt/etc/kvas.dnsmasq (20 записей)
-----------------------------------------------------------------------------------
ipset=/:.*instagram\.com:/unblock
ipset=/:.*kinozal\.tv:/unblock
ipset=/:.*licdn\.com:/unblock
ipset=/:.*linkedin\.com:/unblock
ipset=/:.*lnkd\.in:/unblock
ipset=/:.*meta\.com:/unblock
ipset=/:.*netflix\.com:/unblock
ipset=/:.*quora\.com:/unblock
ipset=/:.*rutracker\.org:/unblock
ipset=/:.*t\.co:/unblock
ipset=/:.*twimg\.com:/unblock
ipset=/:.*twitter\.co:/unblock
ipset=/:.*twitter\.com:/unblock
ipset=/:.*twitteroauth\.com:/unblock
ipset=/:.*twttr\.com:/unblock
ipset=/:.*whatsapp\.net:/unblock
ipset=/browserleaks.com/unblock
ipset=/openwrt.org/unblock
ipset=/whoer.net/unblock
ipset=/ggpht.com/unblock

-----------------------------------------------------------------------------------
Состояние vpn соединения frankfurt                                  ПОДКЛЮЧЕНО
-----------------------------------------------------------------------------------
Таблица заполнения маршрутов VPN списка id=1001
команда: 'ip route show table 1001'
-----------------------------------------------------------------------------------
default via 10.200.95.158 dev nwg0
192.168.1.0/24 dev br0 scope link  src 192.168.1.1

-----------------------------------------------------------------------------------
Таблица правил маршрутизации VPN списка id=1001
команда: 'ip rule show'
-----------------------------------------------------------------------------------
0:      from all lookup local
10:     from all fwmark 0xffffcff lookup main
196:    from 10.200.95.158 lookup 58
198:    from 10.27.220.223 lookup 60
1778:   from all fwmark 0xd1000/0xd1000 lookup 1001
32766:  from all lookup main
32767:  from all lookup default

-----------------------------------------------------------------------------------
Переустановка iptables для vpn завершена                            УСПЕШНО
-----------------------------------------------------------------------------------
Правила перенаправления трафика unblock в iptables
команда: iptables-save | grep -E 'SHADOWSOCKS|VPNREDIR|unblock'
-----------------------------------------------------------------------------------
:VPNREDIR - [0:0]
:VPNREDIR - [0:0]
-A PREROUTING -p tcp -m set --match-set unblock dst -j VPNREDIR
-A PREROUTING -p udp -m set --match-set unblock dst -j VPNREDIR
-A OUTPUT -p tcp -m set --match-set unblock dst -j VPNREDIR
-A OUTPUT -p udp -m set --match-set unblock dst -j VPNREDIR
-A VPNREDIR -m set ! --match-set unblock dst -j RETURN
-A VPNREDIR -d 0.0.0.0/8 -j RETURN
-A VPNREDIR -d 127.0.0.0/8 -j RETURN
-A VPNREDIR -d 10.0.0.0/8 -j RETURN
-A VPNREDIR -d 169.254.0.0/16 -j RETURN
-A VPNREDIR -d 172.16.0.0/12 -j RETURN
-A VPNREDIR -d 192.168.0.0/16 -j RETURN
-A VPNREDIR -d 224.0.0.0/4 -j RETURN
-A VPNREDIR -d 240.0.0.0/4 -j RETURN
-A VPNREDIR -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A VPNREDIR -m mark --mark 0xd1000 -j RETURN
-A VPNREDIR -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j MARK --set-xmark 0xd1000/0xffffffff
-A VPNREDIR -p udp -m conntrack --ctstate NEW -j MARK --set-xmark 0xd1000/0xffffffff
-A VPNREDIR -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff

-----------------------------------------------------------------------------------
Список разблокировки /opt/etc/hosts.list (20 записей)
-----------------------------------------------------------------------------------
*instagram.com
*kinozal.tv
*licdn.com
*linkedin.com
*lnkd.in
*meta.com
*netflix.com
*quora.com
*rutracker.org
*t.co
*twimg.com
*twitter.co
*twitter.com
*twitteroauth.com
*twttr.com
*whatsapp.net
browserleaks.com
openwrt.org
whoer.net
yt3.ggpht.com

-----------------------------------------------------------------------------------
DNS сервер, используемый в /opt/apps/kvas/bin/main/ipset
-----------------------------------------------------------------------------------
@127.0.0.1:9153

-----------------------------------------------------------------------------------
Таблица ipset (20 записей)
команда: 'ipset list unblock'
-----------------------------------------------------------------------------------
52.183.220.149
52.184.216.226
52.185.211.133
52.204.48.70
52.206.92.184
52.21.227.162
52.22.151.125
54.155.246.232
54.157.77.20
54.163.58.78
54.172.34.192
54.225.122.99
54.236.184.144
54.237.159.171
54.243.147.148
54.73.148.110
64.233.165.132
72.21.91.29
92.122.36.149
93.184.220.29

-----------------------------------------------------------------------------------
Проверка наличия ip адресов хостов в таблице ipset
команда 'ipset list unblock'
-----------------------------------------------------------------------------------
4pda.ru (172.67.183.145|104.21.68.2)                                В ТАБЛИЦЕ
ads-twitter.com                                                     АДРЕСА НЕТ
cdnfacebook.com                                                     АДРЕСА НЕТ
cdninstagram.com                                                    АДРЕСА НЕТ
f.vision (213.133.123.188)                                          В ТАБЛИЦЕ
facebook.com (157.240.247.35)                                       В ТАБЛИЦЕ
fbcdn.net (157.240.247.35)                                          В ТАБЛИЦЕ
fburl.com (157.240.3.11)                                            В ТАБЛИЦЕ
ig.me (157.240.247.174)                                             В ТАБЛИЦЕ
instagram.com (157.240.247.174)                                     В ТАБЛИЦЕ
kinozal.tv (188.114.97.2|188.114.96.2)                              В ТАБЛИЦЕ
licdn.com                                                           АДРЕСА НЕТ
linkedin.com (13.107.42.14)                                         В ТАБЛИЦЕ
lnkd.in (13.107.42.14)                                              В ТАБЛИЦЕ
meta.com (157.240.247.13)                                           В ТАБЛИЦЕ
netflix.com (54.74.73.31|3.251.50.149|54.155.178.5)                 В ТАБЛИЦЕ
quora.com (54.82.148.155|54.81.207.255|34.239.11.60|52.206.92.184|52.200.140.216|18.213.162.15|52.3.28.168|54.80.202.192)                                                     В ТАБЛИЦЕ
rutracker.org (172.67.212.135|104.21.83.43)                         В ТАБЛИЦЕ
t.co (104.244.42.69)                                                В ТАБЛИЦЕ
twimg.com                                                           АДРЕСА НЕТ
twitter.co (165.160.13.20|165.160.15.20)                            В ТАБЛИЦЕ
twitter.com (104.244.42.193|104.244.42.1)                           В ТАБЛИЦЕ
twitteroauth.com (54.237.159.171|3.226.182.14|23.22.5.68|52.21.227.162)   В ТАБЛИЦЕ
twttr.com (199.59.148.10)                                           В ТАБЛИЦЕ
whatsapp.net (157.240.201.60)                                       В ТАБЛИЦЕ
browserleaks.com (104.236.69.55)                                    В ТАБЛИЦЕ
openwrt.org (139.59.209.225)                                        В ТАБЛИЦЕ
whoer.net (104.26.4.133|104.26.5.133|172.67.74.128)                 В ТАБЛИЦЕ
yt3.ggpht.com (photos-ugc.l.googleusercontent.com.|172.217.13.161)  В ТАБЛИЦЕ
-----------------------------------------------------------------------------------

</details>

**Comment by qzeleza** [comment]
С обычного компьютера работает?

**Comment by XEGARE** [comment]
Да, работает.

**Comment by XEGARE** [comment]
Всё. Нашёл. Как и говорил ранее дело в DNS. Но днём я просто отключил шифрование:
```
kvas crypt off
kvas update
```

сейчас сделал так и заработало:
```
kvas crypt off
kvas dns 8.8.8.8
kvas update
```

Результат:
![image](https://user-images.githubusercontent.com/28856609/208920669-9c2fd872-8a34-43a4-97c3-48381556e4c9.png)

**Comment by qzeleza** [comment]
Тики закрываю

**Comment by XEGARE** [comment]
Так почему шифрованный DNS не меняет на тот что я хочу? Шифровать гугловский нельзя?

**Comment by qzeleza** [comment]
Потому что в Вашей ситуации необходимо использовать, либо AGH, либо dnsmaqs+dnscrypt, а не все сразу.

**Comment by geekorn** [comment]
приветствую! у меня та же проблема, что и у автора issue, не загружается youtube исключительно в приложении на iOS, что на iPhone, что на iPad. 
То, что помогло @XEGARE, мне не помогло) да и меня устраивало как работает связка dnsmaqs+dnscrypt, и отдельный dns прописывать нет необходимости.

не знаю стоит ли заводить новый issue, или этот можно открыть снова?

Версия kvas 1.1.8 release-2

**Информация о роутере (пожалуйста, заполните следующую информацию):**
Производитель: Keenetic
Прошивка на роутере: 4.3.3
Giga KN-1012

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
iPhone 14pro
Операционная система и версия: IOS 18.5
Safari
Приложение YouTube

iPad 7-го поколения
Операционная система и версия: iPadOS 18.4.1
Приложение YouTube

Так было с самого начала установки kvas на роутер, но до этого момента особо не было времени с этим разбираться, да и ни к чему было. а сейчас вот, появились и потребность и время)

<details>
  <summary>Kvas debug</summary>
Версия пакета 1.1.8 release-2                                     
------------------------------------------------------------------
Текущая дата и время Wed Jun 11 13:29:25 MSK 2025

------------------------------------------------------------------
Информация о роутере
------------------------------------------------------------------
Страна: EA
Модель: KN-1012
Продукт: Giga
Тип архитектуры: aarch64

Журнал установки пакета:
------------------------------------------------------------------
Файл списка разблокировки ВОССТАНОВЛЕН из архива.
Файл конфигурации пакета Квас ВОССТАНОВЛЕН из архива.
Файл конфигурации Shadowsocks ВОССТАНОВЛЕН из архива.
Файл конфигурации dnsmasq ВОССТАНОВЛЕН из архива.
Файл списка ipset для dnsmasq ВОССТАНОВЛЕН из архива.
Файл конфигурации dnscrypt_proxy2 ВОССТАНОВЛЕН из архива.
Файл списка источников хостов для блокировки рекламы ВОССТАНОВЛЕН из архива.
Текущее VPN соединение: SHADOWSOCKS                                
Шифрование DNS трафика (dnscrypt-proxy2) ВКЛЮЧЕНО.
Блокировка рекламы НЕ УСТАНОВЛЕНА..
--------------------------------------------------------------------
Установка завершена: 13/01/2025 18:46:30

------------------------------------------------------------------
Список ошибок из системного журнала
------------------------------------------------------------------
 Core::Authenticator: access to \cli\ denied for user \root\. 
 Jun 11 13:15:47
 Core::Authenticator: access to \sftp\ denied for user \root\. 
 Jun 11 13:15:47
 Core::Authenticator: access to \cli\ denied for user \root\. 
 Jun 11 13:15:52
 Core::Authenticator: access to \sftp\ denied for user \root\. 
 Jun 11 13:15:52
 Core::Authenticator: access to \cli\ denied for user \root\. 
 Jun 11 13:20:03
 Core::Authenticator: access to \sftp\ denied for user \root\. 
 Jun 11 13:20:03
 Core::Authenticator: access to \cli\ denied for user \root\. 
 Jun 11 13:20:18
 Core::Authenticator: access to \sftp\ denied for user \root\. 
 Jun 11 13:20:18
 Core::Authenticator: access to \cli\ denied for user \root\. 
 Jun 11 13:20:18
 Core::Authenticator: access to \sftp\ denied for user \root\. 
 Jun 11 13:20:18
 Core::Authenticator: access to \cli\ denied for user \root\. 
 Jun 11 13:20:18
 Core::Authenticator: access to \sftp\ denied for user \root\. 
 Jun 11 13:20:18

Доступные VPN интерфейсы в системе 
------------------------------------------------------------------
shadowsocks = [shadowsocks | shadowsocks]
geekpicnic-server = [Wireguard0 | geekpicnic-server]
 = [GigabitEthernet0/Vlan3 | ]
 = [GigabitEthernet0/0 | ]
 = [GigabitEthernet0/1 | ]
 = [GigabitEthernet0/2 | ]
 = [GigabitEthernet0/3 | ]
 = [GigabitEthernet1/0 | ]
 = [WifiMaster0 | ]
 = [WifiMaster1 | ]
 = [WifiMaster1/AccessPoint1 | ]
 = [WifiMaster1/AccessPoint6 | ]
 = [WifiMaster0/AccessPoint5 | ]
 = [WifiMaster0/AccessPoint4 | ]
 = [WifiMaster0/AccessPoint1 | ]
 = [WifiMaster0/AccessPoint6 | ]
 = [WifiMaster0/AccessPoint2 | ]
 = [WifiMaster1/AccessPoint4 | ]
 = [WifiMaster1/AccessPoint2 | ]
 = [WifiMaster0/AccessPoint0 | ]
 = [WifiMaster1/AccessPoint5 | ]
 = [WifiMaster1/AccessPoint3 | ]
 = [WifiMaster1/AccessPoint0 | ]
 = [WifiMaster0/AccessPoint3 | ]
 = [WifiMaster0/WifiStation0 | ]
 = [WifiMaster1/WifiStation0 | ]
 = [GigabitEthernet0/Vlan1 | ]
 = [Bridge0 | ]
 = [Bridge1 | ]

------------------------------------------------------------------
Состояние службы dnsmasq по команде                               
/opt/etc/init.d/S56dnsmasq status                       ЗАПУЩЕНА  
------------------------------------------------------------------
Выборка из файла конфигурации dnsmasq: /opt/etc/dnsmasq.conf
------------------------------------------------------------------
user=nobody
pid-file=/var/run/opt-dnsmasq.pid
interface=br0
listen-address=192.168.2.1
listen-address=127.0.0.1
listen-address=172.16.82.1
port=53
addn-hosts=/opt/etc/hosts
conf-dir=/opt/etc/dnsmasq.d/,*.dnsmasq
proxy-dnssec

Состояние службы dnscrypt-proxy2                        ЗАПУЩЕНА  
------------------------------------------------------------------
Отчет по прослушиванию порта dnscrypt-proxy [9153]
команда: netstat -ltunp | grep "dnscrypt"
------------------------------------------------------------------
tcp 0 0 :::9153 :::* LISTEN 11990/dnscrypt-prox
udp 0 0 :::9153 :::* 11990/dnscrypt-prox

------------------------------------------------------------------
Выборка из файла конфигурации dnscrypt-proxy2 /opt/etc/dnscrypt-proxy.toml
------------------------------------------------------------------
listen_addresses = ['[::]:9153']
cache = false

------------------------------------------------------------------
Список разблокировки в /opt/etc/dnsmasq.d/kvas.dnsmasq (все записи)
------------------------------------------------------------------
ipset=/:.*2ip\.ru:/unblock
ipset=/:.*4pda\.to:/unblock
ipset=/:.*addr\.tools:/unblock
ipset=/:.*amnezia\.org:/unblock
ipset=/:.*bing\.com:/unblock
ipset=/:.*browserleaks\.com:/unblock
ipset=/:.*canva\.com:/unblock
ipset=/:.*cdntogo\.net:/unblock
ipset=/:.*chatgpt\.com:/unblock
ipset=/:.*digital-cdn\.net:/unblock
ipset=/:.*dnsleaktest\.com:/unblock
ipset=/:.*facebook\.com:/unblock
ipset=/:.*fbcdn\.net:/unblock
ipset=/:.*google\.dev:/unblock
ipset=/:.*googlevideo\.com:/unblock
ipset=/:.*help\.keenetic\.com:/unblock
ipset=/:.*i\.ytimg\.com:/unblock
ipset=/:.*instagram\.com:/unblock
ipset=/:.*keenetic\.com:/unblock
ipset=/:.*kino\.pub:/unblock
ipset=/:.*kinopub\.online:/unblock
ipset=/:.*live\.com:/unblock
ipset=/:.*lordserial\.pub:/unblock
ipset=/:.*medium\.com:/unblock
ipset=/:.*microsoft\.com:/unblock
ipset=/:.*microsoft365\.com:/unblock
ipset=/:.*myip\.addr\.tools:/unblock
ipset=/:.*myyad\.com:/unblock
ipset=/:.*netflix\.com:/unblock
ipset=/:.*notion\.com:/unblock
ipset=/:.*notion\.so:/unblock
ipset=/:.*oaistatic\.com:/unblock
ipset=/:.*openai\.com:/unblock
ipset=/:.*openwrt\.org:/unblock
ipset=/:.*proton\.me:/unblock
ipset=/:.*spotify\.com:/unblock
ipset=/:.*teamviewer\.com:/unblock
ipset=/:.*whatsapp\.net:/unblock
ipset=/:.*www\.youtube\.com:/unblock
ipset=/:.*x\.com:/unblock
ipset=/:.*xerox\.com:/unblock
ipset=/:.*yalenkino\.org:/unblock
ipset=/:.*yalenkino\.pro:/unblock
ipset=/:.*youtu\.be:/unblock
ipset=/:.*youtube\.com:/unblock
ipset=/:.*zencdn\.net:/unblock
ipset=/myip2.ru/unblock
ipset=/:.*yt3\.ggpht\.com:/unblock

------------------------------------------------------------------
Состояние службы shadowsocks                            ЗАПУЩЕНА  
------------------------------------------------------------------
Отчет по прослушиванию порта shadowsocks [1181]
команда: netstat -ltunp | grep "ss-redir"
------------------------------------------------------------------
tcp 0 0 :::1181 :::* LISTEN 11919/ss-redir

------------------------------------------------------------------
Выборка из файла конфигурации shadowsocks /opt/etc/shadowsocks.json
------------------------------------------------------------------
{
  "local_port": 1181,
  "method": "chacha20-ietf-poly1305",
  "timeout": 86400,
  "local_address": "::",
  "dns_ipv6": false,
  "fast_open": false
}

------------------------------------------------------------------
Переустановка iptables для shadowsocks завершена         УСПЕШНО  
------------------------------------------------------------------
Правила перенаправления трафика unblock в iptables
команда: iptables-save | grep -E 'SHADOWSOCKS|VPNREDIR|unblock'
------------------------------------------------------------------
:SHADOWSOCKS - [0:0]
-A PREROUTING -i nwg0 -p tcp -m set --match-set unblock dst -j REDIRECT --to-ports 1181
-A PREROUTING -i nwg0 -p udp -m set --match-set unblock dst -j REDIRECT --to-ports 1181
-A PREROUTING -i br0 -p tcp -m set --match-set unblock dst -j REDIRECT --to-ports 1181
-A PREROUTING -i br0 -p udp -m set --match-set unblock dst -j REDIRECT --to-ports 1181
-A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
-A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
-A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
-A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
-A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
-A SHADOWSOCKS -d 217.145.79.63/32 -j RETURN

------------------------------------------------------------------
Список разблокировки /opt/etc/hosts.list (все записи)
------------------------------------------------------------------
*2ip.ru
*4pda.to
*addr.tools
*amnezia.org
*bing.com
*browserleaks.com
*canva.com
*cdntogo.net
*chatgpt.com
*digital-cdn.net
*dnsleaktest.com
*facebook.com
*fbcdn.net
*google.dev
*googlevideo.com
*help.keenetic.com
*i.ytimg.com
*instagram.com
*keenetic.com
*kino.pub
*kinopub.online
*live.com
*lordserial.pub
*medium.com
*microsoft.com
*microsoft365.com
*myip.addr.tools
*myyad.com
*netflix.com
*notion.com
*notion.so
*oaistatic.com
*openai.com
*openwrt.org
*proton.me
*spotify.com
*teamviewer.com
*whatsapp.net
*www.youtube.com
*x.com
*xerox.com
*youtu.be
*youtube.com
*yt3.ggpht.com
*zencdn.net
myip2.ru

------------------------------------------------------------------
DNS сервер, используемый в /opt/apps/kvas/bin/main/ipset
------------------------------------------------------------------
@127.0.0.1:9153

------------------------------------------------------------------
Проверка наличия ip адресов хостов в таблице ipset 
команда 'ipset list unblock'
------------------------------------------------------------------
2ip.ru --> 188.40.167.82                               В ТАБЛИЦЕ  
4pda.to --> 104.22.34.226|104.22.35.226|172.67.6.182   В ТАБЛИЦЕ  
addr.tools --> 104.21.112.1|104.21.16.1|104.21.96.1|104В ТАБЛИЦЕ. 
amnezia.org --> 104.26.9.117|172.67.70.192|104.26.8.117В ТАБЛИЦЕ  
bing.com --> 150.171.27.10|150.171.28.10               В ТАБЛИЦЕ  
browserleaks.com --> 104.236.69.55                     В ТАБЛИЦЕ  
canva.com --> 104.16.102.112|104.16.103.112            В ТАБЛИЦЕ  
cdntogo.net --> 213.183.48.21                          В ТАБЛИЦЕ  
chatgpt.com --> 104.18.32.47|172.64.155.209            В ТАБЛИЦЕ  
digital-cdn.net --> 172.67.137.210|104.21.81.34        В ТАБЛИЦЕ  
dnsleaktest.com --> 23.239.16.110                      В ТАБЛИЦЕ  
facebook.com --> 31.13.71.36                          ОТСУТСТВУЕТ 
fbcdn.net --> 157.240.201.35                          ОТСУТСТВУЕТ 
google.dev --> 216.239.32.27                           В ТАБЛИЦЕ  
googlevideo.com --> 142.250.74.36                     ОТСУТСТВУЕТ 
help.keenetic.com --> keenetic.zendesk.com.|216.198.54.В ТАБЛИЦЕ. 
i.ytimg.com --> 216.58.207.246|142.250.74.150|216.58.2ОТСУТСТВУЕТ 
instagram.com --> 31.13.71.174                        ОТСУТСТВУЕТ 
;; WARNING: response timeout for 127.0.0.1@9153(UDP)
keenetic.com --> 49.12.59.2|167.233.7.36               В ТАБЛИЦЕ  
kino.pub --> 172.66.43.27|172.66.40.229               ОТСУТСТВУЕТ 
kinopub.online --> 216.150.16.193|216.150.1.129       ОТСУТСТВУЕТ 
live.com --> 204.79.197.212                            В ТАБЛИЦЕ  
lordserial.pub --> 104.21.17.232|172.67.178.167        В ТАБЛИЦЕ  
medium.com --> 162.159.153.4|162.159.152.4             В ТАБЛИЦЕ  
microsoft.com --> 40.90.65.53                         ОТСУТСТВУЕТ 
microsoft365.com --> 13.107.6.156                      В ТАБЛИЦЕ  
myip.addr.tools --> www2.addr.tools.|116.203.95.251    В ТАБЛИЦЕ  
myyad.com --> 35.212.27.210                            В ТАБЛИЦЕ  
netflix.com --> 54.170.196.176|54.246.79.9|52.214.181.ОТСУТСТВУЕТ 
notion.com --> 208.103.161.1|208.103.161.2             В ТАБЛИЦЕ  
notion.so --> 208.103.161.1|208.103.161.2              В ТАБЛИЦЕ  
oaistatic.com --> 172.64.146.98|104.18.41.158          В ТАБЛИЦЕ  
openai.com --> 104.18.33.45|172.64.154.211             В ТАБЛИЦЕ  
openwrt.org --> 64.226.122.113                         В ТАБЛИЦЕ  
proton.me --> 185.70.42.45                             В ТАБЛИЦЕ  
spotify.com --> 35.186.224.24                          В ТАБЛИЦЕ  
teamviewer.com --> 52.223.21.92                        В ТАБЛИЦЕ  
whatsapp.net --> 31.13.71.49                           В ТАБЛИЦЕ  
www.youtube.com --> youtube-ui.l.google.com.|142.250.6ОТСУТСТВУЕТ 
x.com --> 172.66.0.227                                 В ТАБЛИЦЕ  
xerox.com --> 13.13.40.11|13.8.148.11                  В ТАБЛИЦЕ  
youtu.be --> 142.250.74.110                            В ТАБЛИЦЕ  
youtube.com --> 142.250.74.46                          В ТАБЛИЦЕ  
yt3.ggpht.com --> photos-ugc.l.googleusercontent.com.|142.ОТСУТСТВУЕТ 
zencdn.net                                             АДРЕСА НЕТ 
myip2.ru --> 81.90.180.86                              В ТАБЛИЦЕ  
</details>
