### ISSUE TITLE
Не работают разблокированные домены через KVAS

### ISSUE THREAD

**Issue by wildrun0** [qzeleza/kvas#39]
**Описание проблемы.**
За всю историю существования КВАСа, так я и не смог приручить его на своем домашнем роутере. Через все версии, через множество повторений переустановок, он у меня ни разу не заработал. Этим тикетом я хочу попробовать разобраться с этим раз и навсегда

**Мои шаги, приведшие к ошибке/проблеме.**
Опишите подробно шаги, которые привели к ошибке:

1. Установил КВАС следуя инструкции
2. ???
3. Не работает!! Разблокированные сайты так и остаются заблокированными, выдавая ERR_CONNECTION_RESET

**Ожидания о поведении программы.**
Она должна работать....

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
- Операционная система Windows 10
- Google Chrome 110.0.5481.77
- SSH клиент PuTTY 0.78

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 3.9.3 (не работало и на предыдущих)
- Тип устройства Giga KN-1011

**Дополнительные пояснения.**
Прикладываю дебаг

**Comment by wildrun0** [comment]
Используемый тип VPN соединения: **L2TP/IPSec**

**Comment by qzeleza** [comment]
Судя по тому, что видно из лога самого роутера, то проблема была при установке пакета (не создались необходимые таблицы). Потому в данном случае, рекомендую Вам - переустановить все с нуля. Стереть флешку с opkg и записать ее по новой. После чего установить kvas.

**Comment by wildrun0** [comment]
> рекомендую Вам - переустановить все с нуля. Стереть флешку с opkg и записать ее по новой. После чего установить kvas.

Вы бы знали сколько раз данная процедура проделывалась без результата

**Comment by qzeleza** [comment]
> Вы бы знали сколько раз данная процедура проделывалась без результата

Могу предложить свою помощь в обнаружении проблемы, но только если сможете предоставить удаленный ssh доступ к устройству.

**Comment by wildrun0** [comment]
UPD
**Заработал** КВАС после обновления до самой последней версии. Даже не верится :)
Теперь другая проблема - после kvas add отваливается снова. Работает только после kvas test (причем на этапе проверки 2ip.ru, где просят проверить появился ли ip, айпи все так же мой, а не впн. После пропуска этого этапа все восстанавливается), в дебаге дельных ошибок нет
[debug2.txt](https://github.com/qzeleza/kvas/files/10712834/debug2.txt)

**Comment by ivan-cc** [comment]
Была похожая проблема. Проблема оказалась на VPN сервере.

**Comment by qzeleza** [comment]
Полагаю тикет можно закрыть из-за отсутствия самой проблемы с пакетом!

**Comment by yamobilkodev** [comment]
> UPD **Заработал** КВАС после обновления до самой последней версии. Даже не верится :) Теперь другая проблема - после kvas add отваливается снова. Работает только после kvas test (причем на этапе проверки 2ip.ru, где просят проверить появился ли ip, айпи все так же мой, а не впн. После пропуска этого этапа все восстанавливается), в дебаге дельных ошибок нет

У меня такая же проблема. Уточните пожалуйста, что значит "пропуск этого этапа" - Ctrl +_C?

**Comment by wildrun0** [comment]
> Уточните пожалуйста, что значит "пропуск этого этапа" - Ctrl +_C?

Нет, просто нажимаю на энтер, и не задерживаюсь на проверку ip адреса (который почему то не меняется, как говорит скрипт)
