### ISSUE TITLE
beta 17, kvas help не показывает help, а выдает список хостов для разблокировки

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#4]

**Comment by qzeleza** [comment]
Внимательно читаем комментарии изменений:
**Изменилось поведение при исполнени команды kvas без аргументов - вместо вывода справки, сейчас выводит БС (исполняет свое предназначение)**

**Comment by badigit** [comment]
> Внимательно читаем [историю изменений](https://github.com/qzeleza/kvas/blob/main/HISTORY.md): **Изменилось поведение при исполнени команды kvas без аргументов - вместо вывода справки, сейчас выводит БС (исполняет свое предназначение)**

Не понятно как это относится к ситуации когда вызывается команда с аргументом help. kvas help тоже показывает список

**Comment by qzeleza** [comment]
По существу, согласен.
Исправил и переизбрал - [проверяем](https://github.com/qzeleza/kvas/tree/main/ipk).
