### ISSUE TITLE
Удаляются параметры в конфиге Adguard Home при заполнении блока ipset

### ISSUE THREAD

**Issue by denisys16** [qzeleza/kvas#40]
**Описание проблемы.**
Скрипт _bin/main/adguard_ при очистке блока ipset удаляет часть параметров Adguard Home в файле _/opt/etc/AdGuardHome/AdGuardHome.yaml_ начиная от блока ipset до блока tls.

**Мои шаги, приведшие к ошибке/проблеме.**
1. В WEB-интерфейсе Adguard Home заполняю фильтр DNS Rewrites
2. Выполняю _/opt/etc/init.d/S99adguardhome restart_
3. После перезапуска в WEB-интерфейсе Adguard Home фильтр DNS Rewrites пуст

**Ожидания от поведения программы.**
Хотелось бы, чтобы настройки Adguard Home не влияющие на функционал KVAS сохранялись при перезапуске или обновлении списка ipset.

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 3.9.3
- Тип устройства Giga KN-1011
- KVAS v1.1.3
- Adguard Home v0.107.24 (Установлен и обновлен в соответствии с инструкцией KVAS)

**Дополнительные пояснения.**
Предлагаю в скрипте _bin/main/adguard_ заменить строку:
`sed -i '/ipset/,/tls/{//!d};' "${adguard_config}"`
строкой:
`sed -i '/ipset/,/ipset_file/{//!d};' "${adguard_config}"`
при очистке блока ipset, и заменить строку:
`sed -i "s/\(.*\)\(^tls:.*\)/\1  ipset: ${ipset}\n\2/" "${adguard_config}"`
строкой:
`sed -i "s/\(.*\)\(^  ipset_file:.*\)/\1  ipset: ${ipset}\n\2/" "${adguard_config}"`
при вставке блока ipset.

По моему мнению это позволит сохранить параметры, находящиеся между блоками ipset и tls в файле _/opt/etc/AdGuardHome/AdGuardHome.yaml_.

**Comment by qzeleza** [comment]
Доброго дня,
Прошу прощения за задержку с ответом.

> **Дополнительные пояснения.**
> Предлагаю в скрипте _bin/main/adguard_ заменить строку:

Хорошо, в следующей версии подправлю.

**Comment by cjmaxik** [comment]
Кажется, что проблема сохраняется на версии 1.1.4, только конфиг ломается полностью и AGH больше не запускается. Прикладываю файлы конфига AGH:
- Изначальный, отличается от стандартного блоками http.address, dns.upstream_dns и dns.fallback_dns: https://pastebin.com/kmzi6aK0
- Сломанный, генерируется после выполнения kvas add: https://pastebin.com/DbXuD1EL

**Comment by qzeleza** [comment]
> Кажется, что проблема сохраняется на версии 1.1.4, только конфиг ломается полностью и AGH больше не запускается. Прикладываю файлы конфига AGH:
> 
> * Изначальный, отличается от стандартного блоками http.address, dns.upstream_dns и dns.fallback_dns: https://pastebin.com/kmzi6aK0
> * Сломанный, генерируется после выполнения kvas add: https://pastebin.com/DbXuD1EL

Подскажите пожалуйста, какой версии ADH файлы конфигурации Вы мне прислали и что значит "отличается от стандартного блоками" - стандартный это какой?

**Comment by cjmaxik** [comment]
Версия 0.107.38.
Стандартный - сгенерированный при установке AGH.

**Comment by qzeleza** [comment]
Спасибо, релиз обновил - жду обратной связи.

**Comment by cjmaxik** [comment]
Пока безуспешно, AGH падает с фатальной ошибкой, прикладываю лог: https://pastebin.com/Q2MRAB7W
