### ISSUE TITLE
После обновления Keenetic OS с 3.9.2 на 3.9.4 перестали открываться сайты из белого списка

### ISSUE THREAD

**Issue by yamobilkodev** [qzeleza/kvas#43]
**Описание проблемы.**
После обновления Keenetic OS с 3.9.2 на 3.9.4 перестали открываться сайты из белого списка.

**Что делал.**
Обновил  Keenetic OS с 3.9.2 на 3.9.4
Ранее был установлен квас версии 1.0-beta_17. После того как сломалось, установил последнюю версию 1.1.13. Не помогло.

Удалил квас полностью через 
`kvas remove full`
Опять поставил последний. 

Запускал opkg update.
Включал/выключал dns override.
Переустановил Entware.

Ничего не помогло.

При установке кваса с нуля выдавал такую ошибку:

```
Collected errors:
 * resolve_conffiles: Existing conffile /opt/etc/crontab is different from the conffile in the new package. The new conffile will be placed at /opt/etc/crontab-opkg.
 * resolve_conffiles: Existing conffile /opt/etc/dnsmasq.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/dnsmasq.conf-opkg.
 * resolve_conffiles: Existing conffile /opt/etc/shadowsocks.json is different from the conffile in the new package. The new conffile will be placed at /opt/etc/shadowsocks.json-opkg.
```

Вроде, не критично.

При попытке доступа на сайт из белого списка Firefox выдает такое:

'Ошибка при установлении защищённого соединения
При соединении с 2ip.ru произошла ошибка. PR_END_OF_FILE_ERROR
Код ошибки: PR_END_OF_FILE_ERROR'

kvas test и kvas debug ничего критичного не выдают

Приложить kvas,debug не получается почему-то. Могу выслать на почту его + self-test

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 3.9.4 (откат на версию 3.9.2 проблему не решил)
- Тип устройства: Keenetic Giga

**Comment by qzeleza** [comment]
Проблему при переходе  Keenetic OS с 3.9.2 на 3.9.4 подтверждаю.
Буду разбираться в ближайшее время попробую выпустить исправление.

**Comment by qzeleza** [comment]
Проблема оказалась не в Квасе, а в оконченных устройствах, после сброса кеша и перегрузки роутера работоспособность восстановилась. 

Прошу подтвердить или опровергнуть данные выводы.

**Comment by yamobilkodev** [comment]
Проблема решилась после замены Shadowsocks сервера в настройках кваса. Странно, что этот сервер работал уже почти полгода и ровно в момент обновления сломался. Спасибо за помощь, видимо, тикет можно закрывать.
