### ISSUE TITLE
Неправильная выведение команды kvas -h

### ISSUE THREAD

**Issue by Spp595** [qzeleza/kvas#44]
Написано что можно использовать локальный adguard
![image](https://user-images.githubusercontent.com/104263581/222769720-3874d1e8-1b04-488d-a520-e2305e3d75d4.png)
Но на деле: 
![image](https://user-images.githubusercontent.com/104263581/222769913-97c8c4d3-28c6-4e10-b543-22c1fc2b46b2.png)

**Comment by qzeleza** [comment]
В чем вопрос Ваш?
Опишите пожалуйста все по порядку, шаг за шагом, а лучше создайте новый тикет и там все пропишите, по блокам.

**Comment by Spp595** [comment]
Ошибка в выводе команды, написано что можно использовать для adguard другое устройство, но когда вводишь 
kvas adguard on он предлагает только установить его на роутер.

**Comment by qzeleza** [comment]
К сожалению, указанная в справке информация не корректна. Квас будет работать с AGH, установленном на ТОЛЬКО на локальном устройстве.

Подправлю справку в следующей версии.
