### ISSUE TITLE
После обрыва VPN не возобновляется маршрутизация

### ISSUE THREAD

**Issue by wildrun0** [qzeleza/kvas#45]
Некоторые VPN сервера переподключают соединение раз в N часов (как например у некоторых провайдеров для биллинга), и после этого квас падает, спасает `kvas test`

**Мои шаги, приведшие к ошибке/проблеме.**
1. ВПН провайдер обрывает и возобновляет соединение
2. КВАС не работает
3. `kvas test`
4. Теперь работает

**Ожидания о поведении программы.**
Желательно чтобы не падала маршрутизация после обрыва

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
- Windows 10 Pro
- Chrome 110.0.5481.178
- Putty 0.78

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере:  3.9.3
- Тип устройства Giga KN-1011

**Comment by qzeleza** [comment]
Прошу приложить **kvas debug**

**Comment by wildrun0** [comment]
При последующем обрыве приложу, пишу чтобы тикет не закрыли

**Comment by wildrun0** [comment]
Дебаг прикладываю 
[kvas_debug.txt](https://github.com/qzeleza/kvas/files/10917278/kvas_debug.txt)

**Comment by wildrun0** [comment]
Причем проблем нет даже если самому отключить соединение, а потом его вернуть. Квас перестает работать именно когда впн соединеине само сбрасывает сессию

**Comment by qzeleza** [comment]
Попробуйте после обрыва использовать `kvas vpn reset`

**Comment by wildrun0** [comment]
После `kvas vpn reset` маршрутизация не восстанавливается. Разблокированные сайты так же не открываются, 2ip отдает не впновский

**Comment by qzeleza** [comment]
Тогда, в данном случае, пока Вам помочь не смогу, Вы пока только первый человек с такого рода проблемой. Нужна доработка пакета, но занят сейчас написанием **WUI** для **Кваса**. Только после его выпуска смогу заняться доработкой по данному случаю.

**Comment by badigit** [comment]
Столкнулся с такой же проблемой, но kvas vpn reset помогает.
Есть ли возможность как то наладить эту логику в скрипте? 
Может есть способ "поймать" событие переподключения vpn от кинетика, чтобы выполнить триггер 
kvas vpn reset?

**Comment by qzeleza** [comment]
[Вышло исправление](https://github.com/qzeleza/kvas/releases/tag/v1.1.4) в версии Квас 1.1.4, прошу проверить исправление для данного этикета и дать обратную связь.

**Comment by wildrun0** [comment]
> прошу проверить исправление для данного этикета и дать обратную связь.

Ситуация все та же, после обрыва соединения впн провайдером, маршрутизация не возобновляется. Только через kvas test

**Comment by badigit** [comment]
Видимо у меня тикет о том же #73

**Comment by qzeleza** [comment]
> Ситуация все та же, после обрыва соединения впн провайдером, маршрутизация не возобновляется.

Попробуйте запустить `/opt/etc/ndm/fs.d/100-vpn start` после обрыва.

**Comment by qzeleza** [comment]
Еще внес некоторые изменения в код, попробуйте установить новую версию 
 `curl -sOfL https://raw.githubusercontent.com/qzeleza/kvas/main/ipk/install.sh && cat ./install.sh`

**Comment by wildrun0** [comment]
> Еще внес некоторые изменения в код

что -то сломало dnsmasq после обновления на эту версию
![3](https://github.com/qzeleza/kvas/assets/37260144/32e747a6-cf2c-4f56-a1a3-0884028ae9b2)

**Comment by qzeleza** [comment]
Перепроверил на трех устройствах под разные архитектуры - все должно работать корректно, правда пробывал на новых устройствах. Попробуйте полностью удалить и поставить заново пакет.

**Comment by wildrun0** [comment]
Пробовал ставить прошлую версию, ошибка все та же.... Может неправильно пакет удалял, но как мне теперь вернуть dnsmasq...

**Comment by qzeleza** [comment]
пакет теперь используется из репозитория, стандартный - dnsmasq-full

**Comment by wildrun0** [comment]
Я полностью переустановил opkg на флешке, но результат точно такой же

**Comment by wildrun0** [comment]
1. На свежую установку entware (mipsel) ставлю curl
2. после: `curl -sOfL https://raw.githubusercontent.com/qzeleza/kvas/main/ipk/install.sh && sh ./install.sh`
3. запускается kvas setup, выбираю свой впн (хотя квас показывает что он якобы выключен)
4. Дальше все проходит гладко. но на сайты не заходит по ошибке DNS_PROBE_STARTED
5. запускаю kvas test. пишет что с dnsmasq ошибка, запустите kvas debug
6. kvas debug выдает то что выше. якобы в /opt/sbin нету dnsmasq
7. перехожу в эту директорию, dnsmasq действительно нет
8. opkg install dnsmasq-full. пишет что уже установлен в системе

**Comment by qzeleza** [comment]
Доступ можете предоставить?

**Comment by qzeleza** [comment]
Думаю, что нашел в чем проблема. Обновитесь пожалуйста.

**Comment by wildrun0** [comment]
Обновился. Да, теперь проблема ушла, все работает отлично. Отпишу что произойдет после обрыва, как только случится

**Comment by qzeleza** [comment]
В новой версии удалил установку в крон. Теперь если Вы самостоятельно не установите задание в крон, то обновления не должно происходить по часам, а только при добавлении и удалении доменов.

**Comment by wildrun0** [comment]
Сегодня ночью был обрыв впн, маршрутизация не возобновилась.
Судя по логам, квас действительно работал после возобновления соединения, но тщетно
Может быть это связано с тем, что у меня квас перестает работать тоже после команд kvas update / kvas add. Только через kvas test все успешно начинает работать

**Comment by qzeleza** [comment]
> Сегодня ночью был обрыв впн, маршрутизация не возобновилась.

Прошу Вас прислать лог роутера `curl -s -d '{"once": false, "max-lines": 10}' "'http://127.0.0.1:79/rci/show/log'`, сразу после обрыва.

**Comment by qzeleza** [comment]
Прошу дать обратную связь по выявленной Вами проблеме в [крайней версии пакета Квас](https://github.com/qzeleza/kvas/releases/tag/v1.1.5-pr2) - **1.1.5-pr2**. 
Решена ли Ваша проблема в этой версии пакета?

Желательно это сделать вплоть **до 26 ноября** текущего года. Детали описаны на форуме по [этой ссылке](https://forum.keenetic.com/topic/14415-пробуем-квас-shadowsocks-и-другие-vpn-клиенты/?do=findComment&comment=174713).

**Comment by qzeleza** [comment]
Если ошибка воспроизводима в крайней версии Кваса - откройте тикет вновь.
Пока же тикет закрываю из-за отсутствия обратной связи по ошибке.
