### ISSUE TITLE
Ошибка при установке при настройке пакета dnscrypt-proxy2 (beta 17)

### ISSUE THREAD

**Issue by Hazardovich** [qzeleza/kvas#5]
```
BusyBox v1.35.0 (2022-08-08 06:21:00 UTC) built-in shell (ash)

~ # opkg install /opt/etc/kvas_1.0-beta_17_all.ipk
Package kvas (1.0-beta_17) installed in root is up to date.
Configuring kvas.
-----------------------------------------------------------------------------------
Установка пакета КВАС™ версия 1.0-beta-17]
-----------------------------------------------------------------------------------
Настройка файлов конфигурации пакета                                ГОТОВО
Копируем файл со списком разблокировки по умолчанию                 УСПЕШНО
Останавливаем сервис dnsmasq...                                     ГОТОВО
Заменяем файл конфигурации dnsmasq...                               ГОТОВО
Меняем dnsmasq на версию с поддержкой wildcard                      ГОТОВО
Настройка файлов конфигурации dnsmasq                               ГОТОВО
Обнуление таблицы ipset                                             ГОТОВО
Обновление таблицы ipset                                            ГОТОВО
Обновление списка dnsmasq                                           ГОТОВО
Перезапуск службы dnsmasq                                           ГОТОВО
-----------------------------------------------------------------------------------
Системное время обновлено с основного сервера:                      15:33:49
Устанавливаем пакет dnscrypt-proxy2...                              ОШИБКА
Ошибка при установке пакета dnsmasq                                 
Collected errors:
 * pkg_run_script: package "kvas" postinst script returned status 1.
 * opkg_configure: kvas.postinst returned 1.
```
Устанавливал начисто.

**Comment by qzeleza** [comment]
Слишком мало данных, не смог воспроизвести  у себя подобное поведение.
Необходим вывод `netstat -ltunp | grep -e ':53 '`

**Comment by Hazardovich** [comment]
```
BusyBox v1.35.0 (2022-08-08 06:21:00 UTC) built-in shell (ash)

~ # netstat -ltunp | grep -e ':53 '
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      23371/dnsmasq
tcp        0      0 :::53                   :::*                    LISTEN      23371/dnsmasq
udp        0      0 0.0.0.0:53              0.0.0.0:*                           23371/dnsmasq
udp        0      0 :::53                   :::*                                23371/dnsmasq
~ #
```

**Comment by butyc** [comment]
была такая же проблема, решил следующим образом. Поставил квас начисто - ошибка, поставил адгард, настроил и запустил еще раз поверх установку кваса- заработало

**Comment by qzeleza** [comment]
`dnscrypt-proxy`?

**Comment by Hazardovich** [comment]
~ # dnscrypt-proxy
[2022-09-24 15:46:31] [FATAL] Unable to load the configuration file [dnscrypt-pr                                                               oxy.toml] -- Maybe use the -config command-line switch?

**Comment by butyc** [comment]
dnscrypt-proxy - я пробовал включать, не помогало. сейчас все работает в связке с адгард, так что подсказать не могу более по логам

**Comment by qzeleza** [comment]
> ~ # dnscrypt-proxy
> [2022-09-24 15:46:31] [FATAL] Unable to load the configuration file [dnscrypt-pr oxy.toml] -- Maybe use the -config command-line switch?

dnscrypt-proxy -config /opt/etc/dnscrypt-proxy.toml -check

**Comment by Hazardovich** [comment]
~ # dnscrypt-proxy -config /opt/etc/dnscrypt-proxy.toml -check
[2022-09-24 15:54:24] [NOTICE] dnscrypt-proxy 2.1.1
[2022-09-24 15:54:26] [NOTICE] Source [public-resolvers] loaded
[2022-09-24 15:54:26] [NOTICE] Source [relays] loaded
[2022-09-24 15:54:26] [NOTICE] Configuration successfully checked

**Comment by qzeleza** [comment]
Кажется нашел в чем проблема. Пересобрал - [пробуем](https://github.com/qzeleza/kvas/blob/main/ipk/kvas_1.0-beta_17_all.ipk) и жду обратной связи.

**Comment by Hazardovich** [comment]
Установилось

`Collected errors:
 * resolve_conffiles: Existing conffile /opt/etc/dnsmasq.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/dnsmasq.conf-opkg.
`

**Comment by qzeleza** [comment]
> `Collected errors:
> 
> * resolve_conffiles: Existing conffile /opt/etc/dnsmasq.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/dnsmasq.conf-opkg.

Данная ошибка скорее всего связана с тем, что Вы устанавливали не с нуля.

**Comment by Hazardovich** [comment]
Установилось, но не работают сайты из списка разблокировки. Откатился на 15 версию, все работает.

**Comment by qzeleza** [comment]
> Установилось, но не работают сайты из списка разблокировки. Откатился на 15 версию, все работает.

`kvas debug`

**Comment by Hazardovich** [comment]
Переустановил 17 версию. Все заработало сразу.
Не показывает версию

`~ # kvas ver
-----------------------------------------------------------------------------------
Версия скрипта -
`

**Comment by butyc** [comment]
Не показывает версию
подтверждаю

**Comment by qzeleza** [comment]
> Не показывает версию
> подтверждаю
Создайте пожалуйста новый тикет по этому поводу.
