### ISSUE TITLE
Добавить ssr guest (обход блокировок и у VPN клиентов)

### ISSUE THREAD

**Issue by ALTernateF13** [qzeleza/kvas#52]
По сути, вся маршрутизация ssr держится на 4 правилах для **br0** (интерфейса домашней сети):
```
# DNS
iptables -A PREROUTING -w -t nat -i br0 -p tcp --dport 53 -j DNAT --to 192.168.1.1
iptables -A PREROUTING -w -t nat -i br0 -p udp --dport 53 -j DNAT --to 192.168.1.1
# Выборочные IP в Shadowsocks
iptables -A PREROUTING -w -t nat -i br0 -p tcp -m set --match-set unblock dst -j REDIRECT --to-port 1181
iptables -A PREROUTING -w -t nat -i br0 -p udp -m set --match-set unblock dst -j REDIRECT --to-port 1181
```
При разворачивании VPN-сервера на роутере появляется соответствующий ему сетевой интерфейс, для которого эти правила нужно просто размножить. Был проведён эксперимент, связка SS и WireGuard-сервера на роутере прекрасно работают. В подтверждение моих слов — [на Хабре поступали ровно также](https://habr.com/en/articles/669314/#:~:text=iptables%20%2DI%20PREROUTING%20%2Dw%20%2Dt%20nat%20%2Di%20sstp0%20%2Dp,sstp0%20%2Dp%20tcp%20%2D%2Ddport%2053%20%2Dj%20DNAT%20%2D%2Dto%20192.168.1.1).
Аналог **kvas vpn guest**.

**Comment by qzeleza** [comment]
Благодарю.

**Comment by qzeleza** [comment]
[Вышло исправление](https://github.com/qzeleza/kvas/releases/tag/v1.1.4) в версии Квас 1.1.4, прошу проверить исправление для данного этикета и дать обратную связь.
