### ISSUE TITLE
Ошибка S56dnsmasq: not found

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#55]
**Описание проблемы.**
1. Был установлен adguard (из entware)
2. Установлен квас
3. При первом запуске kvas setup, скрипт сообщил что видит работающий adguard, используем его
4. По итогам setup обход блокировок и adguard работают
5. При этом kvas test возвращает ошибки

**Мои шаги, приведшие к ошибке/проблеме.**
Пишем kvas test
Получаем

```
 ~ # kvas test
-----------------------------------------------------------------------------------
Состояние службы dnsmasq                                            /opt/bin/kvas: line 80: /opt/etc/init.d/S56dnsmasq: not found
ОСТАНОВЛЕНА
Перезапускаем еще раз dnsmasq                                       ОШИБКА

Запустите диагностику командой kvas debug
```
 
 запускаем kvas debug

```
~ # kvas debug
-----------------------------------------------------------------------------------
Версия пакета КВАС 1.1.3-
-----------------------------------------------------------------------------------
Текущая дата и время Thu Jun  1 16:39:55 +06 2023

-----------------------------------------------------------------------------------
Информация о роутере
-----------------------------------------------------------------------------------
Страна: RU
Модель: KN-1010
Тип архитектуры: mipsel

Текущее VPN соединение: homedi ikev2 (IKE0)                         ПОДКЛЮЧЕНО
AdGuard Home НАСТРОЕН, как основной DNS сервер
УСТАНОВЛЕН список разблокировки ПО УМОЛЧАНИЮ.
-----------------------------------------------------------------------------------
Установка завершена: 28/05/2023 13:38:54
-----------------------------------------------------------------------------------
Список ошибок из системного журнала
-----------------------------------------------------------------------------------


Состояние службы dnsmasq по команде
/opt/etc/init.d/S56dnsmasq status                                   ОСТАНОВЛЕНА
-----------------------------------------------------------------------------------

dnsmasq: failed to create listening socket for port 53: Address already in use

[] Проблемы при выделении адресов для аренды DHCP

```

**Ожидания о поведении программы.**
Ожидается что ошибок не будет

**Снимки экрана или сам текст с консоли.**
нет

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
---

**Информация о роутере (пожалуйста, заполните следующую информацию):**
Производитель:  Keenetic
Прошивка на роутере: 3.9.5
Тип устройства Giga (KN-1010)

**Дополнительные пояснения.**
Добавьте сюда любые пояснения, которые по Вашему мнению касаются обнаруженной ошибки/проблемы.

**Comment by qzeleza** [comment]
Здесь у Вас явный перехлест двух служб `dnsmasq` и `adguard`. Не ясно почему у Вас тестируется dnsmasq  при включенном adguard. Попробуйте отключить `adguard` - `kvas adguard off` и затем его снова включить `kvas adguard on`, если не поможет, то лучше всего переустановить пакет полностью.

**Comment by badigit** [comment]
Спасибо за ответы. Мне тоже не ясно почему скрипт тестирует dnsmasq хотя сам же при установке говорил мне что видит adguard и использует его. 

Вот лог kvas setup первоначальной установки kvas (при установленном adh)

```
/opt/packages # kvas setup
-----------------------------------------------------------------------------------
  Настройка пакета не завершена, запускаем настройку пакета             
-----------------------------------------------------------------------------------
Установка пакета   КВАС™   версии   1.1.3  
-----------------------------------------------------------------------------------
  Производим сканирование интерфейсов!                                  
  Сохраняйте терпение и спокойствие!                                    
-----------------------------------------------------------------------------------
  Выберите VPN интерфейс для работы пакета                              
-----------------------------------------------------------------------------------
 Интерфейс shadowsocks [текущий]                                      ОТКЛЮЧЕН  
2. Интерфейс homedi ikev2                                             ОТКЛЮЧЕН  
-----------------------------------------------------------------------------------
 [36mВыберите номер варианта VPN соединения [1-2]:                         2
Интерфейс homedi ikev2 подключен                                      УСПЕШНО  
-----------------------------------------------------------------------------------
  На роутере обнаружен AdGuard Home                                     
 Установить AdGuard Home, как основной DNS сервер [Y/N,Q]?             y
AdGuard Home установлен в качестве основного DNS сервера              УСПЕШНО  
-----------------------------------------------------------------------------------
Копируем файл со списком разблокировки по умолчанию                   УСПЕШНО  
Ставим обновление ip адресов по умолчанию - каждые 12 часов...        ГОТОВО  
Запускаем КВАС в работу                                               УСПЕШНО  
-----------------------------------------------------------------------------------
Установка КВАСа завершена.
```
 kvas adguard off и затем kvas adguard on помогли, но немного пришлось поплясать...
 

 
Посмотрел код kvas test,  - dnsmasq проверка выполняется всегда, если проверка cmd_adguardhome_status  не возвращает "ВКЛЮЧЕН".

По хорошему тут хотя бы в echo добавить отображение статуса adguardhome даже если он не "alive"
а также проблема могла быть в значении adguard_is_dns_default.

Сейчас все работает, хотя явно где-то явно загвоздка была..

**Comment by badigit** [comment]
Еще меня немного смутило, что get_adguardhome_ip_port проверяет значение в "bind_host:",
хотя в самом конфиге adguard, настройки DNS лежат в разделе bind_host**S**
dns:
  bind_hosts:
    - 10.9.8.1
  port: 53

**Comment by qzeleza** [comment]
> Еще меня немного смутило, что get_adguardhome_ip_port проверяет значение в "bind_host:",
> хотя в самом конфиге adguard, настройки DNS лежат в разделе bind_host**S**
> dns:

Нам здесь не нужен **DNS** **adguard**, функция **get_adguardhome_ip_port** получает адрес и порт на котором сейчас висит **web**-интерфейс **adguard**.

> `kvas adguard off` и затем `kvas adguard on` помогли

Рад что все удалось решить.
Тикет закрываю.
