### ISSUE TITLE
[Пустить одну из сетей в обход КВАС]

### ISSUE THREAD

**Issue by Goshan4** [qzeleza/kvas#56]
**Описание проблемы.**
В роутере 2 сети, одна является "доступом" в интернет, вторая для умного дома MIHOME, так же с доступом в интернет.
После установки КВАС, почти все устройства умного дома стали offline. При отключении КВАС и всего диска с entware, начинает работать нормально.

**Мои шаги, приведшие к ошибке/проблеме.**
Настройка WARP 
Установка КВАС - по инструкции строго! 
Установка и запуск ADGUARD HOME по инструкции строго.
В AGH добавил DNS с которыми все работало больше года (без КВАС)

**Ожидания о поведении программы.**
Все предложенные КВАСом функции работают штатно.

**Снимки экрана или сам текст с консоли.**
Приложу файл с DEBUG
[01_DEBUG.txt](https://github.com/qzeleza/kvas/files/11859084/01_DEBUG.txt)

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
- Windows 10 22H2
- Google Chrome 114.0.5735.134
- SSH клиент PuTTY 0.78

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Keenetic 
- 4.0 Beta 3
- GIGA KN-1011]

**Дополнительные пояснения.**
Хотелось бы, что бы моя вторая сеть с умным домом работала в обход КВАСа, напрямую в интернет. 

br0 должна идти через КВАС
br1 должна идти в обход

default via 172.16.0.2 dev nwg0
192.168.1.0/24 dev br0 scope link  src 192.168.1.1 - основная сеть, должна работать через КВАС
192.168.2.0/24 dev br1 scope link  src 192.168.2.1 - сеть умного дома, должа идти в обход.

О себе: не сильно разбираюсь в теме, но не новичок. С командной стройкой работаю по шаблонам из интернета, но небольшое понимание есть. Это к тому, что я могу что то не понять в ответах и задавать вопросы, или не точно сначала объяснить проблему.

**Comment by qzeleza** [comment]
Прошу прислать вывод команды на роутере `iptables-save | grep PREROUTING`

**Comment by Goshan4** [comment]
![image](https://github.com/qzeleza/kvas/assets/130301095/267a679b-10a8-426a-b1f6-edf1d6988229)
Подскажите как ее выполнить? у меня windows. не через CLI не через SSH команда не выполняется

**Comment by qzeleza** [comment]
уберите kvas в самом начале

**Comment by Goshan4** [comment]
![image](https://github.com/qzeleza/kvas/assets/130301095/8694417e-d374-4060-8add-775642b98996)

**Comment by qzeleza** [comment]
Здесь не вижу проблемы - **DNAT** работает только по сетке **br0**, для сетки **br1** ничего не видно.
Попробуйте `iptables-save | grep br1 -C2`

**Comment by Goshan4** [comment]
[grep 1921682 C2.txt](https://github.com/qzeleza/kvas/files/11859348/grep.1921682.C2.txt)
[grep br1 C2.txt](https://github.com/qzeleza/kvas/files/11859349/grep.br1.C2.txt)

**Comment by Goshan4** [comment]
Попробовал еще раз. 
С включенным Adguard Home и КВАС - устройства не в сети.
Добавил для подсети 192.168.2.0/24 исключение в adguard - устройства не в сети.
Отключил через КВАС adguard - устройства не в сети.
Отключил всю флешку с entware - все заработало.

Сейчас буду пробовать все с 0ля на другую флешку поставить.

**Comment by qzeleza** [comment]
в присланных Вами списках нет никаких намеков на проблемы  перенаправления трафика сети br1 на какой либо vpn интерфейс. Попробуйте удалить Adguard: `kvas adguard off`

**Comment by Goshan4** [comment]
Переустановил все с 0. без ADGUARD так же ничего не работало. 
Установил ADGUARD в него добавил адреса mihome, которые нашел на просторах:
_@@||fr-app-chat-global-xiaomi-net-1516654448.eu-central-1.elb.amazonaws.com^
@@||api.io.mi.com^
@@||shopapi.io.mi.com^_
Все заработало. Обход через WARP и КВАС - работает

**Comment by qzeleza** [comment]
Значит проблема была все-таки в ADGUARD и его DNS, которые блокировали ваш ресурс.
Раз проблема решена - тикет закрываю.
