### ISSUE TITLE
В wiki более полно описать последствия смены DNS-прокси

### ISSUE THREAD

**Issue by ALTernateF13** [qzeleza/kvas#59]
1. ndhcps (DNS-прокси по умолчанию) всегда [подменяет служебный DNS 78.47.125.180 на адрес роутера](https://help.keenetic.com/hc/ru/articles/360017022999-VPN-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80-IKEv2#:~:text=%D0%92%20%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5%20DNS-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0%20%D0%BF%D0%BE,%D0%B2%D1%81%D0%B5%20DNS-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D1%8B%20%D0%BD%D0%B0%20Keenetic). После _**opkg dns-override**_ в качестве DNS-прокси начинает выступать Dnsmasq, который о таком финте ушами не знает. 
2. Все домашние домены, заведённые до этого командой [_ip host_](https://help.keenetic.com/hc/ru/articles/360011129420-%D0%9E%D0%B1%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA-%D1%81%D0%B5%D1%82%D0%B5%D0%B2%D0%BE%D0%BC%D1%83-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D1%83-%D0%BF%D0%BE-hostname#:~:text=(config)%3E%20ip%20host%20%3C%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D0%B5_%D0%B8%D0%BC%D1%8F_%D1%85%D0%BE%D1%81%D1%82%D0%B0%3E%20%3C%D0%B0%D0%B4%D1%80%D0%B5%D1%81%3E%0A(config)%3E%20system%20configuration%20save), также перестанут работать. Потребуется их перенос в конфиг dnsmasq (директива _address_). 

Сейчас в Вики
> После ввода команды opkg dns-override у Вас должен пропасть интернет. Это нормально. Так и должно быть. Все последующие шаги по установке пакета позволят его реанимировать.

О других последствиях смены DNS-прокси этой командой не предупреждено. Как мне кажется, после
> 6. Для проверки работоспособности, можете запустить проверку пакета командой kvas test

Стоит добавить пункты
> Если используется VPN-сервер IKEv2/IPsec, то в его настройках нужно изменить поле DNS-сервер с 78.47.125.180 на IP-адрес роутера (по умолчанию 192.168.1.1).

> Если использовались домашние домены (добавленные командой ip host), то их можно перенести в конфиг dnsmasq:
>- nano /opt/etc/hosts.dnsmasq
>address=/localdomain1.test/192.168.1.25
>address=/localdomain2.test/192.168.1.27
>- nano /opt/etc/dnsmasq.conf
>server=127.0.0.1#9153
>conf-file=/opt/etc/hosts.dnsmasq # Добавляем эту строчку, если нужны локальные домены
>conf-file=/opt/etc/kvas.dnsmasq
>- /opt/etc/init.d/S56dnsmasq restart

**Comment by qzeleza** [comment]
Доброго дня, спасибо за участие и Ваше предложение. 
Изменения внес в [Wiki](https://github.com/qzeleza/kvas/wiki/Установка-пакета#примечание).
