### ISSUE TITLE
Не работает обход при подключении через VPN

### ISSUE THREAD

**Issue by butyc** [qzeleza/kvas#6]
Добрый день, как уже писал в личке и на форуме, на 17 бете все также не работает обход при подключении к роутеру по впн со смартфона из внешней сети.
в качестве dns сервера выступает adguard. в настройках впн подключения смартфона и роутера прописан dns -роутера (192.168.1.1)

**Comment by qzeleza** [comment]
Доброго дня,
На форуме Вам посоветовали вежде отключить IP6. Удалось ли? Каков результат?

**Comment by butyc** [comment]
Добрый, он отключен, не помогает
![IMG_20220926_154443_640](https://user-images.githubusercontent.com/46633963/192279715-03c97526-d639-4057-b662-7035fd0904c1.jpg)

**Comment by butyc** [comment]
по возможности протестирую 18 бету, отпишусь!

**Comment by qzeleza** [comment]
Добро, жду.

**Comment by qzeleza** [comment]
Вышла бета 19 - прошу проверить на наличие или отсутствие этой ошибки в пакете.

**Comment by qzeleza** [comment]
Тикет закрывается в связи с отсутствием обратной связи от автора тикета.
