### ISSUE TITLE
Добавить в инструкцию по установке шаг с удалением поддержки IPv6 на роутере

### ISSUE THREAD

**Issue by dilame** [qzeleza/kvas#61]
В вики по поводу IPv6 сказано:

> ПРОВЕРЬТЕ, ЧТО ОТКЛЮЧЕНА ПОДДЕРЖКА IPV6 В ЛИЧНОМ КАБИНЕТЕ ПРОВАЙДЕРА, ЕСЛИ ТАКОВОЙ ПУНКТ ИМЕЕТСЯ. А ТАКЖЕ, ПРОВЕРЬТЕ, ЧТО ДАННАЯ ОПЦИЯ (IP6) ОТКЛЮЧЕНА В СВОЙСТВАХ СЕТЕВОГО АДАПТЕРА ВАШЕГО КОМПЬЮТЕРА.

Однако я нашёл более простой способ отключения поддержки IPv6: это можно сделать прямо на роутере: `Компоненты операционной системы` -> `Протокол IPv6`. 
И тогда никакие провайдеры и сетевые адаптеры не страшны. Предлагаю изменить пункт про IPv6 в вики

<img width="1038" alt="Screenshot 2023-07-10 at 06 35 38" src="https://github.com/qzeleza/kvas/assets/9336742/eab0b158-f0ce-462c-b763-7874395f067b">

**Comment by dilame** [comment]
Кстати, ещё предлагаю перенести вики непосредственно в репозиторий, чтобы люди могли делать Pull Request.

**Comment by qzeleza** [comment]
Если Вы опробовали и Ваш метод работает на всех режимах Кваса - дайте знать, поправлю.

> Кстати, ещё предлагаю перенести вики непосредственно в репозиторий, чтобы люди могли делать Pull Request.

Поясните пожалуйста, как Вы это видите.

**Comment by dilame** [comment]
> Поясните пожалуйста, как Вы это видите.

Wiki – это просто `*.md` файлы. Минус раздела Wiki на гитхабе в том, что он не интегрирован в основную кодовую базу. 
Можно в корне проекта создать директорию `wiki` и просто скопировать туда всё содержимое раздела wiki. Таким образом у сообщества будет возможность делать пул реквесты.

**Comment by dilame** [comment]
> Если Вы опробовали и Ваш метод работает на всех режимах Кваса - дайте знать, поправлю

Нет, я не тестировал это во всех режимах. Я просто на последней прошивке keenetic удалил этот модуль, и у меня всё работает. Использую просто shadowsocks и dnsmasq.

Тут вот @impaxel говорит, что можно снять галочку в настройках Ethernet, тоже выглядит как хороший вариант. В любом случае на уровне роутера это решать намного проще и надёжнее.

**Comment by qzeleza** [comment]
> Wiki – это просто `*.md` файлы. Минус раздела Wiki на гитхабе в том, что он не интегрирован в основную кодовую базу.
> Можно в корне проекта создать директорию `wiki` и просто скопировать туда всё содержимое раздела wiki. Таким образом у сообщества будет возможность делать пул реквесты

Да, но как при этом обновлять саму [вики](https://github.com/qzeleza/kvas/wiki)? Есть варианты?

**Comment by qzeleza** [comment]
> Нет, я не тестировал это во всех режимах. Я просто на последней прошивке keenetic удалил этот модуль, и у меня всё работает. Использую просто shadowsocks и dnsmasq.

Где то на просторах форума Keenetiс пользователи Кваса писали, что не всегда помогает простое отключение. Потому решил перестраховаться и написать такое предупреждение. Лучше лишний раз проверить, чем не проверить).

Спасибо за Ваше участие и доработки.

**Comment by qzeleza** [comment]
Спасибо, посмотрю. 
Сейчас немного нет времени - **Самовар** хочу доделать. Потому вернуться к доработкам **Кваса**.

**Comment by qzeleza** [comment]
Тикет закрываю. Возможность доработки WIKI для Кваса буду иметь в виду.
