### ISSUE TITLE
Добавить URL *fbsbx.com в список разблокировки из коробки

### ISSUE THREAD

**Issue by dilame** [qzeleza/kvas#62]
Этот URL используется в приложении Instagram для прохождения капчи. Соответственно, встречается довольно редко, но когда встречается – в аккаунт попасть не получится:)
Ну и до кучи ещё можно было бы `*fb.com` докинуть.

**Comment by qzeleza** [comment]
> Этот URL используется в приложении Instagram для прохождения капчи. Соответственно, встречается довольно редко, но когда встречается – в аккаунт попасть не получится:)
> Ну и до кучи ещё можно было бы `*fb.com` докинуть.

Не проблема добавить, но тогда почему только эти?))
С таким подходом можно забить список до отказа.

Если у Вас есть необходимость - добавляйте самостоятельно.

**Comment by dilame** [comment]
> Не проблема добавить, но тогда почему только эти?))

Только эти потому что, как я понял, KVAS из коробки предлагает работоспособность инстаграма. До отказа список не забьётся двумя урлами, зато будет полностью покрыта задача. А то получается как-то наполовинку:)

В данном случае я говорю в основном про `*fbsbx.com`. От него непосредственно зависит капча в инстаграме.

**Comment by qzeleza** [comment]
Добро, добавлю
