### ISSUE TITLE
Как в ручную обновить квас?

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#67]
**Описание проблемы.**
Последняя сборка 1.1.3 от января месяца, но с тех по было много значимых коммитов в скриптах.
При установке январской версии встаёт вопрос, как правильно подтянуть правки которые произошли с того периода.

**Мои шаги, приведшие к ошибке/проблеме.**
Пробовал просто заменить файлы, взяв из github последнии версии, но после этого квас вообще перестал запускаться.
Есть ли какие-нибудь нюансы?
Или возможно у вас есть возможность собрать свежий релиз?

**Пример ошибки после замены файлов на новые**
~ # kvas list
/opt/bin/kvas: /opt/apps/kvas/bin/libs/ndm: line 204: syntax error: unexpected newline

**Comment by impaxel** [comment]
Тоже утром собрал и хотел обновиться, но столкнулся с той же проблемой. Кажется, ошибка в [этом коммите](https://github.com/qzeleza/kvas/commit/6fcc25e532ceab352fab598fae3f8318fe34cbe9), и я полагаю, исправление должно было быть примерно таким:
```shell
_inface_guest_ent=$(inface_guest_ent)
        rules=$(ip4save | grep "\-j MASQUERADE" | grep "${_inface_guest_ent}")
        if [ -z "${rules}" ] ; then
                _inface_guest_gw4=$(inface_guest_gw4)
                # Маркируем трафик гостевой сети
                {
                        log_warning "Подключаем правила маркировки гостевого трафика."
                        ip4tables PREROUTING -t nat -p udp -d "${_inface_guest_gw4}" --dport ${DNS_PORT} -j DNAT --to "$(inface_gw4):53"
                        ip4tables PREROUTING -t nat -p tcp -d "${_inface_guest_gw4}" --dport ${DNS_PORT} -j DNAT --to "$(inface_gw4):53"
                        ip4tables POSTROUTING -t nat -s "$(guest_net)" -o "${_inface_guest_ent}" -j MASQUERADE
                } &>/dev/null
                when_error "${?}" " ${IPv4} Возникла ошибка при маркировке гостевого трафика ${_inface_guest_ent} [${_inface_guest_gw4}]"
        fi
```
Я думаю @qzeleza скажет наверняка, но у меня после данных изменений все завелось.

**Comment by qzeleza** [comment]
> Или возможно у вас есть возможность собрать свежий релиз?

Постараюсь собрать до конца этой недели, если все сложится.

**Comment by wildrun0** [comment]
> Постараюсь на следующей.

На этой неделе тоже релиза не будет?

**Comment by qzeleza** [comment]
Доброго дня
Постараюсь до середины недели успеть все же выложить.
Прошу прощения - так ситуация складывается - раньше не смогу.
