### ISSUE TITLE
Ошибки при запуске adguard - expected one slash

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#70]
**Описание проблемы.**
Установлен и работает adguard.
Устанавливаем kvas
Запускаем kvas setup
Квас видит adguard  и применяет его как основной DNS (говори ему Y)
Установка завершена, но adguard больше не стартует

**Отладка**
~ # tail -f /opt/var/log/AdGuardHome.log
2023/09/19 09:21:16.125389 [info] AdGuard Home, version v0.107.38
2023/09/19 09:21:20.682226 [info] tls: using default ciphers
2023/09/19 09:21:20.708753 [info] safesearch default: disabled
2023/09/19 09:21:23.706755 [info] Initializing auth module: /opt/etc/AdGuardHome/data/sessions.db
2023/09/19 09:21:23.707873 [info] auth: initialized.  users:1  sessions:3
2023/09/19 09:21:23.708120 [info] AdGuard Home updates are disabled
2023/09/19 09:21:23.708235 [info] web: initializing
2023/09/19 09:21:33.851498 [fatal] dnsServer.Prepare: preparing ipset settings: initializing ipset: ipset: config line at idx 0: invalid value "- 2ip.ru/unblock                          \\n  - astralnalog.ru/unblock\\n  - beeline.ru/unblock\\n  - comss.ru/unblock\\n  - crediteurope.ru/unblock\\n  - gosuslugi.ru/unblock\\n  - livejournal.com/unb                          lock\\n  - livejournal.net/unblock\\n  - memepedia.ru/unblock\\n  - mgfoms.ru/unblock\\n  - mos.ru/unblock\\n  - mosenergosbyt.ru/unblock\\n  - novofon.com/unbl                          ock\\n  - onlinetrade.ru/unblock\\n  - otpbank.ru/unblock\\n  - pochta.ru/unblock\\n  - telegra.ph/unblock\\n  - zadarma.com/unblock\\n  - zbulvar.ru/unblock":                           expected one slash

**Comment by badigit** [comment]
** установка была из kvas_1.1.4_all.ipk, обновленный 3 часа назад (самый свежий)

**Comment by badigit** [comment]
Еще наблюдения и непонятки.
При запуске kvas test - почему то идет проверка Состояние службы dnsmasq, хотя при kvas setup у нас был установлен в качестве сервера adguard. 
При повторном вызове kvas adguard on 
- AdGuard Home установлен в качестве основного DNS сервера            УСПЕШНО

Но kvas test все еще проверяет dnsmasq
Скриншот https://lookmyscreen.tinytake.com/msc/ODcwNDkyOF8yMjA5Njg3NQ

Также прикладываю kvas debug
[1909.log](https://github.com/qzeleza/kvas/files/12658369/1909.log)

**Comment by qzeleza** [comment]
Корни ошибки одни и те же что и предыдущем этикете #69. 
Пожалуйста проверьте сейчас - выложил обновление и пишите в тикете #69.

**Comment by badigit** [comment]
Это не помогло. Ошибка та же.
удаление руками kvas.ipset не помогло - создался новый, но adguard не стартует

**Comment by badigit** [comment]
@qzeleza 
проверил с последним коммитом [7a191cb](https://github.com/qzeleza/kvas/commit/7a191cbeed9ae2f16611490a7d35ca5259360d69)

ошибка сохраняется, суть - та же. Файл kvas.ipset я удалял.

2023/09/19 10:49:53.174819 [fatal] dnsServer.Prepare: preparing ipset settings: initializing ipset: ipset: config line at idx 0: invalid value "2ip.ru/unblock\\n4pda.ru/unblock\\nads-twitter.com/unblock\\nbrowserleaks.com/unblock\\ncdnfacebook.com/unblock\\ncdninstagram.com/unblock\\nf.vision/unblock\\nfacebook.com/unblock\\nfb.com/unblock\\nfbcdn.net/unblock\\nfbsbx.com/unblock\\nfburl.com/unblock\\nig.me/unblock\\ninstagram.com/unblock\\nkinozal.tv/unblock\\nlicdn.com/unblock\\nlinkedin.com/unblock\\nlnkd.in/unblock\\nmeta.com/unblock\\nnetflix.com/unblock\\nopenwrt.org/unblock\\nquora.com/unblock\\nrutracker.org/unblock\\nt.co/unblock\\ntwimg.com/unblock\\ntwitter.co/unblock\\ntwitter.com/unblock\\ntwitteroauth.com/unblock\\ntwttr.com/unblock\\nwhatsapp.net/unblock\\n": expected one slash

**Comment by cjmaxik** [comment]
Обнаружил связанную проблему: `kvas add <domain>` формирует неверный `kvas.ipset`, так как в файл не добавляется разрыв строки последним символом (\n).

```
2023/09/19 17:44:10.430805 [fatal] dnsServer.Prepare: preparing ipset settings: initializing ipset: ipset: config line at idx 30: invalid value "whatsapp.net/**unblockspotify.com**/unblock": expected one slash
```

**Comment by qzeleza** [comment]
пришлите пожалуйста `kvas.ipset` после добавления через ` kvas add <domain>`

**Comment by qzeleza** [comment]
Версию обновил, прошу проверить.

**Comment by cjmaxik** [comment]
Исправлено.

Еще проблема: `kvas del <domain>` и `kvas purge` не удаляют домены из `kvas.ipset`, это ожидаемое поведение? 
Пример: `kvas del 4pda.ru` не удаляет строчку `4pda.ru/unblock` из `kvas.ipset`. `kvas update` также не пересобирает данный список.

**Comment by qzeleza** [comment]
Спасибо. Подправлю. Исправление выложу в конце дня.

**Comment by cjmaxik** [comment]
Работает, спасибо за исправления.
