### ISSUE TITLE
Вопросы и наблюдения при чистой установке kvas 1.1.4 и 1.1.5 pr4

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#74]
**Описание проблемы.**
Удалил квас (версия 1.1.4) - командой kvas rm
удалил руками все зависимые пакеты

после удаления пакетов почему то остался хвост  - 
/opt/etc/cron.5mins/ipset.kvas  удалил руками
/opt/etc/init.d/S22shadowsocks удалил руками

Вопрос 1 - должно ли само удаляться?

2. При установке новой версии, зависимые пакеты установились сами. Но при запуске kvas setup ошибка
![image](https://github.com/qzeleza/kvas/assets/33813448/bf9dd847-d17b-407a-87cf-a6bb9d874171)
/opt/bin/kvas: line 1379: /opt/etc/init.d/S22shadowsocks: not found
видимо само оно не установилось

** Тут ремарка вообще стоит ли устанавливать shadowsocks если его не планируют использовать, и показывать все время его отключенный интерфейс***

3. Почему то автоматом не подтянулся список разблокировки из  
/opt/etc/.kvas/backup/hosts.list
но установился список по умолчанию

4. После kvas setup - интернет заработал (DNS работает и сайты открывает), но обход блокировок - нет.
(проверял через 2ip - вижу свой IP).

5.  сделал kvas purge  и затем kvas import старого списка (у меня он без звездочек, под новый dnsmasq)
6. Все еще не работает обход блокировок
7. Сделал kvas debug - вижу ошибки (файл прикладываю)
![image](https://github.com/qzeleza/kvas/assets/33813448/ea53e1a6-a50e-490b-87e6-1f1b557ce41a)
[123.txt](https://github.com/qzeleza/kvas/files/12739186/123.txt)

Важный момент. Ошибки возникающие при выполнении kvas debug > 123.txt в сам файл не попадают
(но они видны на скрине)

Итого:
1. Не удаляются cron и /opt/etc/init.d/S22shadowsocks, не возвращается скриптS22shadowsocks
2. Не восстанавливает сам прошлый список разблокировки
3. Не работает обход на dnsmasq
4. Ошибки grep: warning: stray \ before 0 в kvas debug

**Comment by badigit** [comment]
После вызова kvas test обход блокировок на базе dnsmasq начинает работать. Посмотрим сколько продержится)

**Comment by badigit** [comment]
Периодически отваливается обход блокировок. 
При вызове kvas update / reset обход не восстанавливается, и видна ошибка без подробностей.
<img width="630" alt="image" src="https://github.com/qzeleza/kvas/assets/33813448/5004d56f-f814-4c9e-88ad-17ab17721f06">

При вызове kvas test ошибок нет, и обход блокировок восстанавливается..

Также - мои наблюдения что traceroute из окружения opkg не показывают обход блокировок никогда,
 traceroute с компьютера в сети покажет корректно трейс с обходом блокировки.
 
 Получается с кинетика нельзя проверить что обход блокировок работает?

**Comment by badigit** [comment]
Добавлю что на текущий момент проблема воспроизводится просто выполнением kvas add. После этого обход блокировок перестает работать.

**Comment by badigit** [comment]
Добавлю, что если не трогать kvas add, и пока основные соединения работают - обход блокировок работает тоже стабильно. При kvas add ломается.

Связываю это с тем что вроде в последних версиях вы отключали автоматическое обновление таблиц через крон. 
Возможно там что то при обновлении проходит не-по-плану...

**Comment by wildrun0** [comment]
Я рад что не только у меня не работает обход без kvas test :)

**Comment by qzeleza** [comment]
Спасибо за  тикет - посмотрю в ближайшее время.

**Comment by kilia07** [comment]
Всем привет! Также не работало после kvas add и периодически просто переставал работать обход блокировок через n-минут после kvas test. При этом если в приоритетах подключения VPN вынести вверх - все ок.
Попробовал удалить 
`rm /opt/etc/cron.5mins/check_vpn`
и вот уже 2 часа работает как надо.

**Comment by badigit** [comment]
Всем привет, с чем столкнулся при установке _1.5_preview_2.

 **Сначала сухо, а потом, ниже подробно**
1. Ошибка /opt/bin/kvas: line 1392: /opt/etc/init.d/S22shadowsocks: not found
2.а) Не нашел нужный интерфейс ikev2 VPN, нашел только со второй попытки (kvas vpn rescan)
2.б) Предлагает интерфейс SS, которым я не пользовался и не собираюсь. 
3. Нужна возможность прерывания setup, на шаге выбора интерфейса.
4. При проблемах kvas setup пропадает интернет и ооочень сильно усложняет отладку, особенно неподготовленным.
5. kvas.install.log пустой, там единственная строка
`ОШИБКА: Не отключено использование DNS провайдера.`
Скорее всего лог затерся, на каком то из шагов отладки.

6. Kvas debug не записывает отладку, если не включен dns override


**Подробнее:**

1. В kvas_1.5_preview_2  также повторяется описанная тут проблема

`
/opt/bin/kvas: line 1392: /opt/etc/init.d/S22shadowsocks: not found
`

Воспроизведение:
```
kvas remove full
Все успешно

Перезагрузка роутера

Установка
opkg install kvas_1.5_preview_2_all.ipk

Выполнение kvas setup

-----------------------------------------------------------------------------------
Настройка пакета не завершена, запускаем настройку пакета
-----------------------------------------------------------------------------------
Установка пакета КВАС™ версии 1.1.5
-----------------------------------------------------------------------------------
Производим сканирование интерфейсов!
Сохраняйте терпение и спокойствие!
-----------------------------------------------------------------------------------
Выберите VPN интерфейс для работы пакета
-----------------------------------------------------------------------------------
/opt/bin/kvas: line 1392: /opt/etc/init.d/S22shadowsocks: not found
1. Интерфейс shadowsocks [78.47.125.180] [текущий]                  ОТКЛЮЧЕН
-----------------------------------------------------------------------------------
Выберите номер варианта VPN соединения [1-1]:
```

2. В списке интерфейсов нет нужного интерфейса VPN Ikev2, который в предыдущей версии был виден.
Ручной запуск kvas vpn rescan - нашел интерфейс ( и ошибка все еще висит)

```
# kvas vpn rescan
-----------------------------------------------------------------------------------
Настройка пакета не завершена, запускаем настройку пакета
-----------------------------------------------------------------------------------
Установка пакета КВАС™ версии 1.1.5
-----------------------------------------------------------------------------------
Обновить список интерфейсов [Y/N,Q]?                                y
-----------------------------------------------------------------------------------
Производим сканирование интерфейсов!
Сохраняйте терпение и спокойствие!
-----------------------------------------------------------------------------------
Выберите VPN интерфейс для работы пакета
-----------------------------------------------------------------------------------
/opt/bin/kvas: line 1392: /opt/etc/init.d/S22shadowsocks: not found
1. Интерфейс shadowsocks [78.47.125.180] [текущий]                  ОТКЛЮЧЕН
2. Интерфейс homedi ikev2 []                                        ГОТОВО
-----------------------------------------------------------------------------------
Выберите номер варианта VPN соединения [1-2]:
 
```

3. При чистой установке пользователь может столкнуться с проблемой: 
Визард установки не предусматривает остановки\отмены на этапе выбора интерфейса.
Если нет находишь нужный интерфейс в списке - не понятно что делать.  Пользователь вынужден что-то выбрать, например не используемый SS (сделать заведомо неправильный выбор).

На этом этапе хорошо бы предусмотреть прерывание setup

4. При прерывании настройки через Ctrl-C получаем себе не-рабочий интернет, и не очевидность того как его восстановить (чтобы написать issue:))
Происходит так, потому что opkg dns override уже включен, и dnsmasq запущен и занял 53 порт, но еще не настроен. 
(Интернет не работает)

Выполнение no opkg dns-override не восстанавливает системный DNS, поскольку порт 53 еще занят и в логах возникает ошибка
failed to bind to 0.0.0.0:53 reason: address in use.

На мой взгляд тут можно подумать об:
- Возможности прерывания setup, с остановкой dnsmaq, и сообщением что для восстановления сети нужно сделать no no opkg dns-override

-Какой то дефолтной конфигурации dnsmasq, чтобы dns хотя бы работал без-обхода-блокировок, в случае проблем на этапе установки

5. kvas.install.log почему то пустой после установки..

6. Очень болезненно составлять issue по проблемах, возникших на этапе setup, потому что:
a) kvas debug требует opkg dns-override, который в свою очередь рвет все сессии и теряешь доступ к интернету и к github) 

b) Запуск kvas debug вызывает запуск dnsmasq, который опять занимает 53 порт, и мешает восстановлению родного dns)) И нужно опять завершать руками dnsmasq, прежде чем выполнить no opkg dns-override.

Хорошо бы чтобы debug собирал информацию "по факту", а не останавливался на этапе требует opkg dns-override"

Как сейчас:
`
-----------------------------------------------------------------------------------
[1;31mНастройка пакета не завершена, запускаем настройку пакета[m           
-----------------------------------------------------------------------------------
Установка пакета [1;32mКВАС™[m версии [1;32m1.1.5[m
-----------------------------------------------------------------------------------
[1;31mДля корректной работы DNS сервера необходимо отключить использование DNS провайдера![m
С этой целью зайдите в админ панель роутера по адресу: [1;32mhttp://10.9.8.1/a[m
и выполните последовательно три следующих команды: 
-----------------------------------------------------------------------------------
1. [1;32mopkg dns-override [m - отключаем использование DNS провайдера,
2. [1;32msystem configuration save [m  - сохраняем изменения,
3. [1;32msystem reboot [m - перегружаем роутер.
-----------------------------------------------------------------------------------
`

**Comment by qzeleza** [comment]
Предварительно, взял тикет в работу. 
Благодарю за столь подробный отчет об ошибке.

**Comment by drfischer2** [comment]
По поводу неработающего интернета полностью поддерживаю! Сам в такой ситуации отказался. В результате через мобильный интернет, с телефона, пытался выяснить в чем проблема. В общем масса приключений тогда у меня было)

**Comment by badigit** [comment]
Спасибо за фиксы по текущему issue.
Апну, наверное последние две проблемы которые остались при обновлении на новые версии.
При обновлении  pr3 > pr4 (adh включен)
1. Затирается список хостов дефолтным, приходится заново настраивать (purge + import)
было бы замечательно оставлять существующий список хостов.

2. Ошибка /opt/bin/kvas: line 1379: /opt/etc/init.d/S22shadowsocks: not found при сканировании интерфейсов (issue 87) 

Обновляю через update последней версии.

**Comment by qzeleza** [comment]
> 1. Затирается список хостов дефолтным, приходится заново настраивать (purge + import)
>    было бы замечательно оставлять существующий список хостов.

В финальной версии 1.1.5 - сделаю

> 2\. Ошибка /opt/bin/kvas: line 1379: /opt/etc/init.d/S22shadowsocks: not found при сканировании интерфейсов (issue  [pr4 Ошибка при сканировании интерфейсов - S22shadowsocks: not found и пустой лог установки #87](https://github.com/qzeleza/kvas/issues/87))

Прокомментировал решение в тикет #87 

Если еще какие либо вопросы по данной ошибке - жду до 26 числа.

**Comment by wildrun0** [comment]
`cp: can't create '/opt/etc/adblock/sources.list': No such file or directory`
при установке крайней версии кваса после kvas remove full предыдущей

**Comment by wildrun0** [comment]
![image](https://github.com/qzeleza/kvas/assets/37260144/f5f25f69-fcbb-4f31-809f-1d195083004a)
`При kvas update`

**Comment by qzeleza** [comment]
> `cp: can't create '/opt/etc/adblock/sources.list': No such file or directory`
> при установке крайней версии кваса после kvas remove full предыдущей

Подправил в крайней версии - проверьте пожалуйста.

> При kvas update

Пока не могу сказать в чем проблема, но на работу она не влияет.

**Comment by qzeleza** [comment]
Доработал код **1.1.5-final**
Если ошибка появится - повторно откройте тикет. 
Сейчас его закрываю.
