### ISSUE TITLE
Не устанавливается КВАС 1.1.4 после установки AGH

### ISSUE THREAD

**Issue by m0graph** [qzeleza/kvas#77]
**Описание проблемы.**
По инструкции было установлено сначала AGH, после попытка установить КВАС 1.1.4

**Мои шаги, приведшие к ошибке/проблеме.**
1. Удалил КВАС 1.1.5 командой kvas remove full (т.к. работало нестабильно)
2. Установил AGH командой opkg install adguardhome-go
3. Выполнил первичную настройку AGH
4. Скачал с гитхаба архив с версией КВАСа 1.1.4
5. Положил файл kvas_1.1.4_all.ipk по пути ENTWARE:/packages/kvas_1.1.4_all.ipk
6. Для настройки пакета КВАС набираю kvas setup 
7. Происходит синтаксическая ошибка

**Ожидания о поведении программы.**
Произойдет установка и настройка КВАСа

**Снимки экрана или сам текст с консоли.**
![изображение](https://github.com/qzeleza/kvas/assets/95464640/50720dd2-a8fa-4cf0-9443-5519e31e42fd)

![изображение](https://github.com/qzeleza/kvas/assets/95464640/0e720081-b2e7-4f02-980a-6385042d0892)

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
- не разобрался, что сюда написать

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.04
- Тип устройства KN-1011

**Дополнительные пояснения.**
Добавьте сюда любые пояснения, которые по Вашему мнению касаются обнаруженной ошибки/проблемы.

**Comment by qzeleza** [comment]
Спасибо за информацию, постараюсь в ближайшее время заняться вопросом.

**Comment by m0graph** [comment]
на версии 1.1.3 завелось. Вылезла другая проблема на 2ip показывает впн, на ресурсы из списка не пускает.

**Comment by qzeleza** [comment]
Данная ошибка исправлена в 1.1.5
