### ISSUE TITLE
Спонтанное временное прекращение работы обхода блокировок 

### ISSUE THREAD

**Issue by Teutonick** [qzeleza/kvas#78]
Конфигурация роутера: Keenetic Ultra (KN-1810) KeeneticOS 4.0.4
Конфигурация Кваса: тип VPN openVPN,  DNS-сервер 8.8.8.8, КВАС 1.1.3

Спонтанное временное прекращение работы обхода блокировок в КВАСе. Данную беду я замечаю с нулевых версий продукта. Из-за чего временно перешел тогда на ADGUARD где работало более стабильно. Но сейчас переустановил на релизную версию без ADGUARD и ошибка вернулась. shadowsocks не использую. Установку производил начисто по инструкции.

Иногда квас стартует корректно и все обходы работают, но после добавления очередного домена, все пропадает. Иногда все пропадает без каких либо конфигурационных изменений. Вообще ни от чего не зависит.   

 Рассказываю по шагам из состояния "не работает разблокировка ресурсов из списка", в логах роутера ошибок нет, инстаграм недоступен ни с каких устройств сети (ноут, мобила):

Шаг 1. Делаю дебаг. [шаг1_log_bad]
[шаг1_log_bad.txt](https://github.com/qzeleza/kvas/files/12790106/1_log_bad.txt)
 (https://forum.keenetic.com/applications/core/interface/file/attachment.php?id=34127&key=dfaceda677a872587f1f488fd1ea5332)  

Шаг 1.1 Делаю netstat

~ # netstat -ltunp | grep "dnscrypt"
tcp        0      0 :::9153                 :::*                    LISTEN      19441/dnscrypt-prox
udp        0      0 :::9153                 :::*                                19441/dnscrypt-prox
 

Шаг 2. Делаю тест [шаг2_test.txt]
[шаг2_test.txt](https://github.com/qzeleza/kvas/files/12790108/2_test.txt)
 (https://forum.keenetic.com/applications/core/interface/file/attachment.php?id=34128&key=2c5ec7e68e510b7756ec3942347d22f7)

По прежнему инста не работает.

Шаг 3. Делаю дебаг [шаг3_log_bad_after_test
[шаг3_log_bad_after_test.txt](https://github.com/qzeleza/kvas/files/12790111/3_log_bad_after_test.txt)
](https://forum.keenetic.com/applications/core/interface/file/attachment.php?id=34129&key=0e2c9fbbc6aac4c385156f1127817944)

По прежнему инста не работает.

Шаг 3.1. Произвожу перезапуск роутера. 

Заметил ошибку в логах роутера 

Сен 8 12:13:57
ndm
Opkg::Manager: /opt/etc/ndm/netfilter.d/100-vpn-mark: exit code 2.
 
По прежнему инста не работает.
 
Шаг 4. Делаю kvas vpn reset 
~ # kvas vpn reset
-----------------------------------------------------------------------------------
Переустановка iptables для vpn завершена                            УСПЕШНО
-----------------------------------------------------------------------------------
 
ИНСТА ЗАРАБОТАЛА 
 
Шаг 5. ЗАписываю дебаг
[шаг5_log_good_after_reset.txt](https://github.com/qzeleza/kvas/files/12790115/5_log_good_after_reset.txt)

**Comment by qzeleza** [comment]
Спасибо, займусь в ближайшее время.

**Comment by PurchaseNachos** [comment]
аналогично, иногда помогает kvas test, иногда - нет

**Comment by qzeleza** [comment]
> Шаг 1. Делаю дебаг. [шаг1_log_bad]
> Шаг 5. ЗАписываю дебаг

Проверил Ваши логи. Ошибку нашел. У Вас, в предоставленных Вами логах, указывается разные getway IP для Вашего VPN соединения, в первом случае (где не работает) он равен  10.8.8.13, во втором (где работает) 10.8.8.4 он равен. 

Первый вариант
```
Таблица заполнения маршрутов VPN списка id=1001
команда: 'ip route show table 1001'
-----------------------------------------------------------------------------------
default via 10.8.8.13 dev ovpn_br0 
10.1.30.0/24 dev br1 scope link  src 10.1.30.1 
10.8.8.0/24 dev ovpn_br0 scope link  src 10.8.8.13 
192.168.2.0/24 dev br0 scope link  src 192.168.2.1
```
Второй вариант 
```
Таблица заполнения маршрутов VPN списка id=1001
команда: 'ip route show table 1001'
-----------------------------------------------------------------------------------
default via 10.8.8.4 dev ovpn_br0 
10.1.30.0/24 dev br1 scope link  src 10.1.30.1 
10.8.8.0/24 dev ovpn_br0 scope link  src 10.8.8.4 
192.168.2.0/24 dev br0 scope link  src 192.168.2.1 
```
Пока нет понимания почему это так и почему происходит их подмена. **Проверьте пожалуйста Вашу VPN конфигурацию.**

**Comment by Teutonick** [comment]
> Проверьте пожалуйста Вашу VPN конфигурацию.

А что в ней проверять? там вообще никаких айпи адресов нет. Вот конфиг VPN, куда смотреть? 
```
client
dev tun
proto udp
remote at-vie.prod.surfshark.com 1194
resolv-retry infinite
nobind
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
persist-key
persist-tun
ping 15
ping-restart 0
ping-timer-rem
reneg-sec 0
remote-cert-tls server
pull-filter ignore "block-outside-dns"
mute-replay-warnings
verb 3
pull
fast-io
cipher AES-256-GCM
auth SHA512
key-direction 1
```

**Comment by qzeleza** [comment]
Прошу дать обратную связь по выявленной Вами проблеме в [крайней версии пакета Квас](https://github.com/qzeleza/kvas/releases/tag/v1.1.5-pr2) - **1.1.5-pr2**. 
Решена ли Ваша проблема в этой версии пакета?

Желательно это сделать вплоть **до 26 ноября** текущего года. Детали описаны на форуме по [этой ссылке](https://forum.keenetic.com/topic/14415-пробуем-квас-shadowsocks-и-другие-vpn-клиенты/?do=findComment&comment=174713).

**Comment by Teutonick** [comment]
> Прошу дать обратную связь по выявленной Вами проблеме в [крайней версии пакета Квас](https://github.com/qzeleza/kvas/releases/tag/v1.1.5-pr2) - **1.1.5-pr2**. Решена ли Ваша проблема в этой версии пакета?

К сожалению, ничего не поменялось((  на роутере все работает стабильно, интернет, ВПН  подключение, ошибок в логах нет. 

Сам КВАС работает вообще хаотично. после настройки - работает, после ребута или добавление хоста - перестает. И потом чтобы его оживить надо либо KVAS TEST либо DEBUG сделать... и то не всегда получается... 
дебаги прилагаю, выполнял в порядке очередности 1, 2, 3, 4 после выполнения операций, названия которых в самих логах 

[1afterreboot_dontwork.txt](https://github.com/qzeleza/kvas/files/13423776/1afterreboot_dontwork.txt)
[2afterresetVPN_work.txt](https://github.com/qzeleza/kvas/files/13423777/2afterresetVPN_work.txt)
[3afterchangehosts_dontwork.txt](https://github.com/qzeleza/kvas/files/13423778/3afterchangehosts_dontwork.txt)
[4aftertest_work.txt](https://github.com/qzeleza/kvas/files/13423779/4aftertest_work.txt)

**Comment by Teutonick** [comment]
Все, что я могу судить на уровне моих скудных познаний в сетях, это то, что НЕ РАБОТАЕТ, когда у меня таблица заполнения маршрутов не содержит VPN маршрутов.


Пример плохого дебага:
```
Таблица заполнения маршрутов VPN списка id=1001
команда: 'ip route show table 1001'
-----------------------------------------------------------------------------------
10.1.30.0/24 dev br1 scope link  src 10.1.30.1 
192.168.2.0/24 dev br0 scope link  src 192.168.2.1 
```

Пример хорошего дебага:
```
Таблица заполнения маршрутов VPN списка id=1001
команда: 'ip route show table 1001'
-----------------------------------------------------------------------------------
default via 10.8.8.17 dev ovpn_br0 
10.1.30.0/24 dev br1 scope link  src 10.1.30.1 
10.8.8.0/24 dev ovpn_br0 scope link  src 10.8.8.17 
192.168.2.0/24 dev br0 scope link  src 192.168.2.1 
```

При том, все остальное в логах идентично... От чего это зависит , я без понятия...

**Comment by qzeleza** [comment]
В данной ситуации необходим доступ к Вашему устройству. 
Если сможете предоставить - напишите.

**Comment by qzeleza** [comment]
Если ошибка появится - повторно откройте тикет. 
Сейчас его закрываю.
