### ISSUE TITLE
Ошибки shadowsocks в syslog

### ISSUE THREAD

**Issue by Cybertank** [qzeleza/kvas#80]
Каждые 5 минут в логе появляются ошибки:

Окт 4 21:55:01 КВАС
Запущен файл /opt/etc/cron.5mins/ipset.kvas
Окт 4 21:55:01 ndm
Network::Interface::Repository: "shadowsocks": missing interface index.
Окт 4 21:55:01 ndm
Network::Interface::Repository: invalid interface name format: "shadowsocks".
Окт 4 21:55:01 ndm
Network::Interface::Base: unable to find shadowsocks as "Network::Interface::Base".
Окт 4 21:55:03 ndm
Network::Interface::Repository: "shadowsocks": missing interface index.
Окт 4 21:55:03 ndm
Network::Interface::Repository: invalid interface name format: "shadowsocks".
Окт 4 21:55:03 ndm
Network::Interface::Base: unable to find shadowsocks as "Network::Interface::Base".

При ручном запуске /opt/etc/cron.5mins/ipset.kvas - ошибок нет
При этом обход блокировок работает.

Информация о роутере:
- Keenetic Viva (KN-1912) EAEU
- Прошивка на роутере: 4.0.4
- Кроме кваса 1.1.5 - ничего не установлено. VPN-SS, свой сервер, AGH не установлен

debug
[debug.txt](https://github.com/qzeleza/kvas/files/12807318/debug.txt)

**Comment by qzeleza** [comment]
Принял к сведению, займусь в ближайшее время.

**Comment by qzeleza** [comment]
Прошу дать обратную связь по выявленной Вами проблеме в [крайней версии пакета Квас](https://github.com/qzeleza/kvas/releases/tag/v1.1.5-pr2) - **1.1.5-pr2**. 
Решена ли Ваша проблема в этой версии пакета?

Желательно это сделать вплоть **до 26 ноября** текущего года. Детали описаны на форуме по [этой ссылке](https://forum.keenetic.com/topic/14415-пробуем-квас-shadowsocks-и-другие-vpn-клиенты/?do=findComment&comment=174713).
