### ISSUE TITLE
При выполнении команды kvas update возникает ошибка заполнения таблицы dnsmasq, режим wildcard не функционирует для адреса *domen.ru, и в журнале роутера повторяются ошибки относительно интерфейса "shadowsocks".

### ISSUE THREAD

**Issue by fatkheev** [qzeleza/kvas#82]
**Описание проблемы.**
При выполнении команды kvas update возникает ошибка при заполнении таблицы dnsmasq. К тому же, режим wildcard не функционирует правильно при добавлении адреса в формате *domen.ru, из-за чего сайты с доменом третьего уровня не загружаются. В дополнение, в журнале роутера часто появляются сообщения об отсутствии интерфейса и неверном формате имени интерфейса "shadowsocks".

**Мои шаги, приведшие к ошибке/проблеме.**
Опишите подробно шаги, которые привели к ошибке:

1. Запустил следующую команду kvas update.
2. Попытался добавить адрес *domen.ru для активации режима wildcard.
3. Для диагностики ввел команду kvas debug (вывод прикреплен отдельно).
4. Обнаружил ошибку при заполнении таблицы dnsmasq и сообщения об ошибках в журнале роутера относительно интерфейса "shadowsocks".

**Ожидания о поведении программы.**
Ожидал, что команда kvas update будет успешно выполнена без ошибок, режим wildcard будет корректно работать с адресом *domen.ru, и не будет ошибок в журнале роутера относительно интерфейса "shadowsocks".

**Снимки экрана или сам текст с консоли.**
**Текст с консоли при выполнении команды kvas update:**
```
-----------------------------------------------------------------------------------
Удаляем все ранее созданные таблицы для утилит ipset и ip           ГОТОВО
Создаем все необходимые таблицы для утилит ipset и ip               ГОТОВО
Создаем таблицу маршрутизации ID#1001 для 'shadowsocks'.            ГОТОВО
Очищаем все ранее созданные iptables правила для SHADOWSOCKS        ГОТОВО
Создаем iptables правила для SHADOWSOCKS соединения.                ГОТОВО
Заполняем ipset таблицу данными из списка разблокировки.            ГОТОВО
Заполняем dnsmasq таблицу данными из списка разблокировки.          ОШИБКА
Перезапускаем сервис dnsmasq                                        ГОТОВО
Перезапускаем сервис dns_crypt                                      ГОТОВО
Синхронизируем дату роутера с сервером времени.                     ГОТОВО
Производим перезапуск подключения к интернету                       ГОТОВО
-----------------------------------------------------------------------------------
```
**Текст сообщений из журнала роутера:**
```
Окт 7 03:20:01 ndm
Network::Interface::Repository: "shadowsocks": missing interface index.
Окт 7 03:20:01 ndm
Network::Interface::Repository: invalid interface name format: "shadowsocks".
Окт 7 03:20:01 ndm
Network::Interface::Base: unable to find shadowsocks as "Network::Interface::Base".
Окт 7 03:20:02 ndm
Network::Interface::Repository: "shadowsocks": missing interface index.
Окт 7 03:20:02 ndm
Network::Interface::Repository: invalid interface name format: "shadowsocks".
Окт 7 03:20:02 ndm
Network::Interface::Base: unable to find shadowsocks as "Network::Interface::Base".
```

Файл с выводом информации, после ввода kvas debug - [kvas.txt](https://github.com/qzeleza/kvas/files/12837207/kvas.txt).

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
- Операционная система Windows 11, версия 22H2, сборка 22621.2361 
- Браузер chrome Версия 117.0.5938.149
- SSH клиент Putty, 0.76

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic (Тип архитектуры: aarch64)
- Прошивка на роутере: 4.0.4
- Тип устройства Ultra KN-1811

**Дополнительные пояснения.**
Ошибки в dnsmasq и сообщения об ошибках интерфейса "shadowsocks" в журнале роутера могут указывать на возможные проблемы в конфигурации программного обеспечения роутера или в самом пакете КВАС или возможные некорректные настройки у меня. Помогите, пожалуйста, устранить эту проблему. Заранее благодарю!

**Comment by badigit** [comment]
Насколько помню в последних версиях квас, не требуется указывать символ * для wildacrd, т.е. добавлять надо в виде 
kvas add domen.ru

А насчет интерфейса - можно попробовать пересканировать и перенастроить.. если вдруг id интерфейса менялся  - через kvas vpn rescan видимо

**Comment by fatkheev** [comment]
Нет, после rescan все таже выходит:

Окт 7 20:50:02 ndm
Network::Interface::Repository: "shadowsocks": missing interface index.
Окт 7 20:50:02 ndm
Network::Interface::Repository: invalid interface name format: "shadowsocks".
Окт 7 20:50:02 ndm
Network::Interface::Base: unable to find shadowsocks as "Network::Interface::Base".
Окт 7 20:50:03 ndm
Network::Interface::Repository: "shadowsocks": missing interface index.
Окт 7 20:50:03 ndm
Network::Interface::Repository: invalid interface name format: "shadowsocks".
Окт 7 20:50:03 ndm
Network::Interface::Base: unable to find shadowsocks as "Network::Interface::Base".

Эти записи в консоли появляются сразу же после запуска /opt/etc/cron.5mins/ipset.kvas

Регулярки также и без звездочки не работают.

**Comment by qzeleza** [comment]
Принял к сведению, займусь в ближайшее время.

**Comment by alekstiler** [comment]
Аналогично.
[debug.txt](https://github.com/qzeleza/kvas/files/13312664/debug.txt)

Network::Interface::Repository: "shadowsocks": missing interface index.
Ноя 9 23:40:03 ndm
Network::Interface::Repository: invalid interface name format: "shadowsocks".
Ноя 9 23:40:03 ndm
Network::Interface::Base: unable to find shadowsocks as "Network::Interface::Base".

**Comment by qzeleza** [comment]
Прошу дать обратную связь по выявленной Вами проблеме в [крайней версии пакета Квас](https://github.com/qzeleza/kvas/releases/tag/v1.1.5-pr2) - **1.1.5-pr2**. 
Решена ли Ваша проблема в этой версии пакета?

Желательно это сделать вплоть **до 26 ноября** текущего года. Детали описаны на форуме по [этой ссылке](https://forum.keenetic.com/topic/14415-пробуем-квас-shadowsocks-и-другие-vpn-клиенты/?do=findComment&comment=174713).

**Comment by fatkheev** [comment]
Большинство проблем решено. Но одна к сожалению осталась. Не грузятся сайты через домен третьего уровня, если добавлять сайт через регулярку через звездочку(*). *domen.ru. test.domen.ru уже не грузится и в hosts.list приходится добавлять множество сайтов, учитывая их домены третьего уровня.

**Comment by fatkheev** [comment]
Под "Не грузятся" я имею ввиду, что они грузятся с ip провайдера, а не через VPN

**Comment by qzeleza** [comment]
Спасибо за обратную связь. Действительно такая ошибка имеет место быть, так как ранее я был введен в заблуждение о том, что сейчас все выпущенные версии dnsmasq под entware поддерживают wildcard. Потому я удалил из пакета собранные с wildcard пакеты dnsmasq. Начиная с версии **1.1.5 pre_relaese_3** верну все как было.

**Comment by qzeleza** [comment]
До выпуска версии **1.1.5 pre_relaese_3** используйте версию пакета под номером **1.1.3**

**Comment by fatkheev** [comment]
Ок, спасибо большое за то что исправляете и не забрасываете проект 🙏

**Comment by fatkheev** [comment]
При команде kvas test выходит:
Проверка заполнения ipset таблицы при посещении сайта.
-----------------------------------------------------------------------------------
Далее, для проверки заполнения, откройте на компьютере браузер
Затем зайдите на сайт https://2ip.ru
На странице должен появиться IP Вашего VDS/VPN провайдера.
После чего вновь перейдите сюда и нажмите на любую клавишу.
-----------------------------------------------------------------------------------
Таблица ipset                                                       ПУСТА
-----------------------------------------------------------------------------------
Попробуйте запустить тест снова
-----------------------------------------------------------------------------------

Пропадает соединение с VPN и пока также не грузятся сайты через домены третьего уровня. Приложил файл debug

[kvas_debug.zip](https://github.com/qzeleza/kvas/files/13454779/kvas_debug.zip)

**Comment by qzeleza** [comment]
> Таблица ipset ПУСТА

Воспроизводится ли сейчас ошибка в версии **1.1.5-pre-release 4**?

**Comment by qzeleza** [comment]
Если ошибка появится - повторно откройте тикет. 
Сейчас его закрываю.
