### ISSUE TITLE
при смене подсети с вида 192.168.х.0/24 на 192.168.х.0/23 перестает работать список обхода

### ISSUE THREAD

**Issue by Paralon4eg** [qzeleza/kvas#83]
при смене подсети с вида 192.168.х.0/24 на 192.168.х.0/23 перестает работать список обхода

команда kvas update выдает ошибки по iptables 

Очищаем все ранее созданные iptables правила для SHADOWSOCKS        ОШИБКА
Создаем iptables правила для SHADOWSOCKS соединения.                ОШИБКА

переустановка kvas эффекта не возымела

при возврате на 192.168.х.0/24 ошибки kvas update пропадают

**Comment by qzeleza** [comment]
К сожалению не волшебник я, не смогу Вам помочь. Ни логов, ни шагов, короче привели к ситуации, ни какой либо полезной информации по тому какие выдаются ошибки. Мало того, не совсем понимаю, где именно Вы делали изменения и самое главное с какой целью.
