### ISSUE TITLE
при обновлении в список разблокировки добавляется whatsapp.net, которого изначально в списке не было

### ISSUE THREAD

**Issue by Paralon4eg** [qzeleza/kvas#84]
при обновлении командой curl -sOfL https://raw.githubusercontent.com/qzeleza/kvas/main/ipk/update.sh && sh ./update.sh в список разблокировки добавляется whatsapp.net, которого изначально в списке не было
после удаления вручную и повторном обновлении whatsapp.net добавляется снова

**Comment by qzeleza** [comment]
К сожалению, не смогу Вам помочь.
