### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Drun555** [qzeleza/kvas#85]
**Описание проблемы.**
Первый (очень страшный) баг при текстовом выводе скрипта. На работоспособность скрипта, по всей видимости, не влияет - скрипт вроде работает.  Я не уверен, в какую сторону копать - но готов скинуть любую информацию (только скажите, какую). 

![изображение](https://github.com/qzeleza/kvas/assets/44411820/23649406-9e5d-4d47-8526-0606c1f4c90c)

ОС Кинетика последняя, а вот Entware был установлен уже довольно давно.

**Comment by qzeleza** [comment]
Пришлите пожалуйста `kvas debug`

**Comment by Drun555** [comment]
<img width="544" alt="Снимок экрана 2023-10-18 в 15 28 20" src="https://github.com/qzeleza/kvas/assets/44411820/1699aa01-15c1-4e69-b7d4-1046f83b05a9">

[debug.txt](https://github.com/qzeleza/kvas/files/13019110/debug.txt)

**Comment by badigit** [comment]
Насколько помню, там как раз нужно послежний entware, под последнюю версию кинетика, потому что были какие то изменения в пакетах ndms, так что можете попробовать

**Comment by qzeleza** [comment]
Прошу дать обратную связь по выявленной Вами проблеме в [крайней версии пакета Квас](https://github.com/qzeleza/kvas/releases/tag/v1.1.5-pr2) - **1.1.5-pr2**. 
Решена ли Ваша проблема в этой версии пакета?

Желательно это сделать вплоть **до 26 ноября** текущего года. Детали описаны на форуме по [этой ссылке](https://forum.keenetic.com/topic/14415-пробуем-квас-shadowsocks-и-другие-vpn-клиенты/?do=findComment&comment=174713).

**Comment by qzeleza** [comment]
Если ошибка воспроизводима в крайней версии Кваса - откройте тикет вновь. 
Пока же тикет закрываю из-за отсутствия обратной связи по ошибке.
