### ISSUE TITLE
Переподключение адаптера

### ISSUE THREAD

**Issue by Drun555** [qzeleza/kvas#86]
**Описание проблемы.**
Не уверен, баг ли это - но скрипт раз в 5 минут (или при добавлении правила) отключает/включает VPN-интерфейс (что приводит к спаму уведомлениями). По всей видимости, неправильно срабатывает условие ping'а.

![изображение](https://github.com/qzeleza/kvas/assets/44411820/1e923295-4215-4920-ba65-1ffa8ef927b7)

Уточню, что скрипт исправно работает, а VPN-соединение стабильно. В качестве временной меры я просто закомментировал часть, которая сбрасывает подключение (мои навыки в sh-скриптах оставляют желать лучшего, поэтому это пока максимум, на который я способен)

![изображение](https://github.com/qzeleza/kvas/assets/44411820/256dec15-0ffe-4081-b548-23f8b7f1ba57)

**Comment by Drun555** [comment]
За сам kvas, кстати, большое спасибо. Очень-очень удобно всё сделано.

**Comment by qzeleza** [comment]
Прошу дать обратную связь по выявленной Вами проблеме в [крайней версии пакета Квас](https://github.com/qzeleza/kvas/releases/tag/v1.1.5-pr2) - **1.1.5-pr2**. 
Решена ли Ваша проблема в этой версии пакета?

Желательно это сделать вплоть **до 26 ноября** текущего года. Детали описаны на форуме по [этой ссылке](https://forum.keenetic.com/topic/14415-пробуем-квас-shadowsocks-и-другие-vpn-клиенты/?do=findComment&comment=174713).

**Comment by qzeleza** [comment]
Если ошибка воспроизводима в крайней версии Кваса - откройте тикет вновь. 
Пока же тикет закрываю из-за отсутствия обратной связи по ошибке.
