### ISSUE TITLE
Не работает обход блокировок с VPN соединением типа L2TP/IKEv2

### ISSUE THREAD

**Issue by wildrun0** [qzeleza/kvas#90]
**Описание проблемы.**
После обновления на крайнюю версию KVAS 1.1.5 перестала работать маршрутизация вообще

**Мои шаги, приведшие к ошибке/проблеме.**
Полностью с нуля (даже со сбросом роутера и переустановкой opkg) установил крайнюю версию пакета, и маршрутизация перестала работать (работало на 1.1.4)

**Информация о системе с которой происходит тестирование пакета на роутере (пожалуйста, заполните следующую информацию):**
- Операционная система (ее кодовое название) и версия: Windows 10 / любое другое устр-во в сети
- Браузер и его версия: Chrome 119.0.6045.200
- SSH клиент и его версия: Putty 0.78

**Информация о роутере (пожалуйста, заполните следующую информацию):**
- Производитель: Keenetic
- Прошивка на роутере: 4.0.7
- Тип устройства Giga KN-1011

**Дополнительные пояснения.**
debug приложил
[debug.txt](https://github.com/qzeleza/kvas/files/13538487/debug.txt)

Мне кажется дело в использовании L2TP vpn т.к. его редко кто использует, соответственно его отладить дело сложное

**Comment by qzeleza** [comment]
Есть ли возможность предоставить доступ к устройству?

**Comment by wildrun0** [comment]
> доступ к устройству

Каким образом?

**Comment by wildrun0** [comment]
> посредством ssh

ssh именно к opkg или прямо в кинетик?

**Comment by wildrun0** [comment]
Как с вами связаться в личных сообщениях?

**Comment by qzeleza** [comment]
https://forum.keenetic.com/profile/20603-zeleza/

**Comment by wildrun0** [comment]
Отписал

**Comment by qzeleza** [comment]
Прошу Вас изменить тему и явно указать, проблему именно с VPN соединением типа L2TP/IKEv2.

**Comment by qzeleza** [comment]
Спасибо

**Comment by qzeleza** [comment]
В версии **1.1.5 final-33** проблема решена. Тикет закрываю.
