### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by Erhesar** [qzeleza/kvas#91]
Решил, значит, начисто установить пакет и получил стоп прямо на старте:

~ # curl -sOfL http://kvas.zeleza.ru/update && sh update
update: line 2: syntax error: unexpected newline

Возможно я что-то упустил?

**Comment by qzeleza** [comment]
Простите моя не доработка - в WIKI забыл подправить ссылку:`curl -sOfL http://kvas.zeleza.ru/upgrade && sh upgrade`
Сейчас подправил. Благодарю Вас.
