### ISSUE TITLE
Пожелания по final 30,31

### ISSUE THREAD

**Issue by badigit** [qzeleza/kvas#93]
Добрый день! 
Похоже пакет достиг высокого уровня автоматизации, что очень радует. (Здоровья автору!)
Несколько моментов которые заметил:

1. При обновлении через curl -sOfL http://kvas.zeleza.ru/upgrade && sh upgrade full
Затирается часть конфига adh, 
-настройки кэша
-настройки имен хостов (весь блок persistent: [])
-потерялся один dns сервер
скрин 1 ![image](https://github.com/qzeleza/kvas/assets/33813448/13455bf3-f87d-4361-9790-89e4a9012dca)
скрин 2 
![image](https://github.com/qzeleza/kvas/assets/33813448/6d7206c0-2501-42c5-af71-e06c92db7fc3)

2. при выполнении kvas debug  с аргументом в виде файла, файл создается но в консоли что то зависает выполнение..
![image](https://github.com/qzeleza/kvas/assets/33813448/e89c98b5-123a-4af0-ac49-5352539bf93c)

3. Был бы благодарен если бы подсказали, какой верный путь перезапуска adh, чтобы все настройки и обход блокировок восстановился. Может быть стоит сделать что то вроде kvas adguard restart?

Сейчас пользуюсь  /opt/etc/init.d/S99adguardhome restart  и это вроде работает! 
Но каждый раз приходится вспоминать этот путь к скрипту)

**Comment by qzeleza** [comment]
Доброго дня
Благодарю за пожелания.

1. Попробуйте обновляться без опции **full**, которая как раз и удаляет все предыдущие данные по проекту.
2. Проверил на **final-30**, не могу подтвердить, все штатно.
3. Специально для Вас ввел новую команду `kvas adguard restart`, хотя можно слать тоже самое командой `kvas update` 

Обновитесь командой `kvas upgrade`

**Comment by badigit** [comment]
За команду спасибо!
Обновился на 31

1. По настройкам adh не изменилась ситуация.
Конфиг затерся, см скрин.
https://lookmyscreen.tinytake.com/msc/OTA3MTI1Ml8yMjU2ODY5NA

2. Ранее, для того чтобы  избежать "зависания" на шаге Заполнение ipset таблицы скриптами КВАСа - я добавлял 
    - 127.0.0.1 в  bind_hosts: (с перезагрузкой adh)

3. Но при обновлении  опять столкнулся с проблемой зависания на этапе заполнения ipset.
Пришлось процесс опять прервать..
(возможно причина что bind host 127.0.0.1 было потеряно в конфиге при переустановке)

4. Решил выключить и включить adh, получил ошибку S09dnscrypt-proxy2 
![image](https://github.com/qzeleza/kvas/assets/33813448/2a096029-dbb2-4994-83e6-e0ee38daaf7a)

5. После этого adh поднялся но все еще не работал dns, пока не вернул в конфиг adh строку  127.0.0.1
dns:
  bind_hosts:
    - 10.9.8.1
    - 127.0.0.1

И не выполнил kvas adguard restart (работает!)

**Comment by qzeleza** [comment]
Попробуйте выполнить следующую последовательность команд:
```
kvas adguard off 
opkg remove adguardhome-go 
rm -f /opt/etc/.kvas/backup/AdGuardHome.yaml
kvas adguard on
kvas test
```

**Comment by badigit** [comment]
Выполнил.
off (Ошибка dnscrypt в наличии, без adh резолвинг не работает.)
удалил бэкап конфига
удалил adh
![image](https://github.com/qzeleza/kvas/assets/33813448/420f09ad-3ba4-41b4-a346-68a45897c51e)

включил adh
![image](https://github.com/qzeleza/kvas/assets/33813448/a32f807d-6e7d-4d8e-8e6a-b588065cdc94)

После установки adh, конфиг adh стал дефолтный, - address и bind_host  - 0.0.0.0.
![image](https://github.com/qzeleza/kvas/assets/33813448/6fee5b39-668c-481a-a9bc-6a2fcacd9adf)

После установи горит надпись что после открытия панели - установка завершится.
Панель открыл, все настроил, но установка не завершилась, надо жать Ctrl C

kvas test выдает ошибки dnsmasq

![image](https://github.com/qzeleza/kvas/assets/33813448/5798c168-74dd-43a2-ab66-8dc2e1913e7e)

kvas debug
```
~ # kvas debug
-----------------------------------------------------------------------------------
Версия пакета 1.1.5 final-31
-----------------------------------------------------------------------------------
Текущая дата и время Thu Dec 21 17:59:27 +06 2023

-----------------------------------------------------------------------------------
Информация о роутере
-----------------------------------------------------------------------------------
Страна: RU
Модель: KN-1010
Страна_: EA
Тип архитектуры: mipsel

Журнал установки пакета:
-----------------------------------------------------------------------------------
Текущее VPN соединение: homedi ikev2 (IKE0)
AdGuard Home НАСТРОЕН, как основной DNS сервер
УСТАНОВЛЕН список разблокировки ПО УМОЛЧАНИЮ.
-----------------------------------------------------------------------------------
Установка завершена: 20/12/2023 12:51:49

-----------------------------------------------------------------------------------
Список ошибок из системного журнала
-----------------------------------------------------------------------------------


Доступные VPN интерфейсы в системе
-----------------------------------------------------------------------------------
shadowsocks = [shadowsocks | shadowsocks]
homedi ikev2 = [IKE0 | homedi ikev2]

-----------------------------------------------------------------------------------
Состояние службы dnsmasq по команде
/opt/etc/init.d/S56dnsmasq status                                   ОСТАНОВЛЕНА
-----------------------------------------------------------------------------------

dnsmasq: failed to create listening socket for port 53: Address already in use

[] Проблемы при выделении адресов для аренды DHCP

```

**Comment by qzeleza** [comment]
Рад что все хорошо. Тикет закрываю.

**Comment by badigit** [comment]
Не совсем решено.. пункты
1. Ошибка dnscrypt  и не рабочий dns после отключения adh
2. Протестировал несколько раз установку adh. Квас не "ловит" завершение первичной настройки adh. 
```
kvas adguard off 
opkg remove adguardhome-go 
rm -f /opt/etc/.kvas/backup/AdGuardHome.yaml
kvas adguard on
```
После начальной установки панели adh,  в  папке /opt/var/log логи отсутствуют. Есть лог в /opt/tmp/adguard.log вот его вид
[adguard.log](https://github.com/qzeleza/kvas/files/13748717/adguard.log)

И невозможно качественно закончить установку.. 

Нужно руками прерывать установку, делать kvas adguard restart и лог создается.

3.  Обновил пакет 31-> 33 через kvas upgrade.
затерлись блоки настроек adh..
-настройки кэша
-настройки имен хостов (весь блок persistent: [])
-настройки dns серверов
-настройки фильтров

**Comment by qzeleza** [comment]
Сегодня занялся Вашим вопросом. 
К сожалению, не смог подтвердить проблему. Обновился, выполнил последовательно все команды - все прошло штатно, без ошибок. 

Попробуйте переустановить заново entware и Квас. 
Если такой возможности или желания нет, то предоставьте доступ к устройству  - попробую понять причину проблемы.

**Comment by badigit** [comment]
Приветствую! Вот что могу добавить:
1. С dnscrypt проблем нет
2. При  выполнении kvas adguard on есть ошибки, но на результат не влияют (косметика)
![image](https://github.com/qzeleza/kvas/assets/33813448/33d0e1ce-034c-487d-841c-2afaaa5791c3)
3. При обновлении 33 -> 1.1.6 stable-1 
Настройки adh не затерлись, все работает как часы.


Большая благодарность вам за внимание к деталям!

**Comment by qzeleza** [comment]
Здравствуйте, чуть подправил (пп.2 ). 
Если критично, то можете обновиться `kvas upgrade force`.
Тикет закрываю. Если что всплывет - смело переоткрывайте его, если тот же вопрос.
