### ISSUE TITLE
В инструкции по установке недействующая ссылка

### ISSUE THREAD

**Issue by furriest** [qzeleza/kvas#94]
В readme указана команда инсталляции вида:
curl -sOfL  https://cutt.ly/kvas_update

Указанная ссылка в настоящий момент недоступна с диагностикой:
That URL has been removed by the user who added it.
The user decided to delete it, therefore this URL will no longer be available.

Возможно планировалось сделать новую ссылку, но не исправили readme?

**Comment by qzeleza** [comment]
Спасибо, исправил.
