### ISSUE TITLE
Падение Adguard Home при добавлении домена

### ISSUE THREAD

**Issue by Yevgen16** [qzeleza/kvas#95]
При добавлении **любого** домена командой `kvas add` происходит падение Adguard Home.
Ошибка в логе Adguard Home:
`2023/12/22 19:41:31.076183 [error] querylog: closing: flushing log buffer: nothing to write to a file
2023/12/22 19:41:31.076452 [fatal] dnsServer.Prepare: preparing ipset settings: initializing ipset: ipset: getting ipsets: config line at idx 43: invalid value "ya.ru": expected one slash`

![Screenshot_3](https://github.com/qzeleza/kvas/assets/37027719/61e47897-dd47-425e-b203-bb5fec254edc)

Пока не перезапустишь вручную Adguard Home соответственно интернет не работает. После перезапуска всё работает штатно.

Версия kvas 1.1.5 final-33
Роутер KN1010, прошивка на роутере 4.0.7.
Проверка проводилась на WIN10, SSH клиент PuTTY.

**Comment by qzeleza** [comment]
Оформите пожалуйста тикет по шаблону или как минимум приложите файл с отладочной информацией.
